In [1]:
# JY, - Import dictionaries
# Import OWLReady
import owlready2
from owlready2 import *
from itertools import chain
import rdflib
#import sparql
from SPARQLWrapper import SPARQLWrapper, JSON
from rdflib import Graph, Literal, RDF, URIRef
from rdflib.namespace import FOAF, XSD
graph = default_world.as_rdflib_graph()

# Import Pandas, Numpy
import pandas as pd
from pprint import pprint
import numpy as np
import re
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)


print('ok - import dictionaries')

ok - import dictionaries

In [2]:
import owlready2
from owlready2 import *
from itertools import chain
import rdflib
#import sparql
from SPARQLWrapper import SPARQLWrapper, JSON
from rdflib import Graph, Literal, RDF, URIRef
from rdflib.namespace import FOAF, XSD
graph = default_world.as_rdflib_graph()

onto = get_ontology("http://test.org/onto.owl")

with onto:
     
    class Food(Thing):
        pass
    class Vegetable(Food):
        pass
    class Fruit(Food):
        pass
    class Meat(Food):
        pass  
    class Fish(Food):
        pass
    class Grain(Food):
        pass
    class Dairy(Food):
        pass    
    
    class Tool(Thing):
        pass
    class Kitchenware(Tool):
        pass
    class Tableware(Tool):
        pass

    
    class Taste(Thing):
        pass
    class Country(Thing):
        pass
    class Color(Thing):
        pass   
    class Nutrition(Thing):
        pass  
    class Function(Thing):
        pass 
    class Shape(Thing):
        pass 
    
     
    class original_from(ObjectProperty):
        domain    = [Food]
        range     = [Country]
    class has_taste(ObjectProperty):
        domain    = [Food]
        range     = [Taste]
    class has_child_food(ObjectProperty):
        domain = [Food]
        range  = [Food]
    class has_color(ObjectProperty):
        domain    = [Food]
        range     = [Color]    
    class has_nutrition(ObjectProperty):
        domain    = [Food]
        range     = [Nutrition] 
        
    class has_function(ObjectProperty):
        domain    = [Tool]
        range     = [Function] 
    class has_shape(ObjectProperty):
        domain    = [Tool]
        range     = [Shape] 
    class has_sub_function(ObjectProperty):
        domain = [Tool]
        range  = [Tool]
        
           
        
    juicy = Taste('juicy')
    sweet = Taste('sweet')
    sour = Taste('sour')
    bitter = Taste('bitter')
    salty = Taste('salty')
    spicy = Taste('spicy')
    fruity = Taste('fruity')
    grassy = Taste('grassy')
    woody = Taste('woody')
    pungent = Taste('pungent')
    meaty = Taste('meaty')
    fishy = Taste('fishy')
    tangy = Taste('tangy')
    
    
    australia = Country('australia')
    new_zealand = Country('new_zealand')
    china = Country('china')
    canada = Country('canada')
    mexica = Country('mexica')
    america = Country('america')
    europe = Country('europe')
    asia = Country('asia')
    egypt = Country('egypt')
    india = Country('india')
    
    green = Color('green')
    red = Color('red')
    yellow = Color('yellow')
    white = Color('white')
    purple = Color('purple')
    
    protein = Nutrition('protein')
    fat = Nutrition('fat')
    
    fry = Function('fry')
    boil = Function('boil')
    drinking = Function('drinking')
    poking = Function('poking')
    stabbing = Function('stabbing')
    cutting = Function('cutting')
    servefood = Function('servefood')
    
    
    long = Shape('long')
    round = Shape('round')
    circular = Shape('circular')
    solid = Shape('solid')
    liquid = Shape('liquid')
    

    tomato = Vegetable("tomato", has_shape=[round], has_color=[red], has_taste=[juicy, sweet], original_from=[america])
    broccoli = Vegetable("broccoli", has_color=[green], has_taste=[juicy, sweet])
#     bean = Vegetable("bean", has_color=[green], original_from=[australia, new_zealand]) 
    chilli = Vegetable("chilli", has_taste=[spicy], has_color=[green, red, yellow], original_from=[america])
    carrot = Vegetable("carrot", has_shape=[long], has_color=[yellow], has_taste=[woody])
    capsicum = Vegetable("capsicum", has_taste=[spicy], has_color=[green, red, yellow], original_from=[america])
    cucumber = Vegetable("cucumber", has_shape=[long], has_color=[green], has_taste=[juicy], original_from=[india])
#     squash = Vegetable("squash", has_shape=[long], has_color=[green])
    cabbage = Vegetable("cabbage", has_taste=[sweet])
#     ginger = Vegetable("ginger", has_taste=[pungent], original_from=[asia])
    garlic = Vegetable("garlic", has_color=[white], has_taste=[pungent], original_from=[asia])
#     leek = Vegetable("leek", has_taste=[pungent], original_from=[australia, new_zealand])
    lettuce = Vegetable("lettuce", has_shape=[round], has_color=[green], original_from=[egypt])
    mushroom = Vegetable("mushroom", has_color=[white])
    onion = Vegetable("onion", has_shape=[round], has_color=[yellow, purple], has_taste=[pungent], original_from=[australia, new_zealand])
    potato = Vegetable("potato", has_taste=[sweet], original_from=[america])
    pumpkin = Vegetable("pumpkin", has_taste=[sweet],has_color=[yellow], original_from=[mexica])
#     parsley = Vegetable("parsley", has_color=[green], original_from=[mexica])
#     green_onion = Vegetable("green_onion", has_shape=[long], has_color=[white, green], has_taste=[pungent], original_from=[australia, new_zealand]) 
    eggplant= Vegetable("eggplant", has_shape=[long], has_color=[purple], has_taste=[sweet] )
#     asparagus= Vegetable("asparagus", has_shape=[long], has_color=[green], has_taste=[sweet])
    pepper = Vegetable("pepper", has_color=[green, red, yellow], has_taste=[spicy])
    
    
    orange = Fruit("orange", has_color=[yellow], has_for_taste=[sweet, sour, juicy])
    apple = Fruit("apple", has_color=[green, red], has_for_taste=[sweet], original_from=[america])
    banana = Fruit("banana", has_shape=[long], has_color=[yellow], has_for_taste=[sweet])
    lemon = Fruit("lemon", has_color=[yellow], has_taste=[sweet, sour, juicy], original_from=[china])
    plum = Fruit("plum", has_color=[purple], has_taste=[sweet, sour, juicy], original_from=[china])
    lime = Fruit("lime", has_color=[green], has_taste=[sweet, sour, juicy], original_from=[china])

    
#     melon = Fruit("melon", has_taste=[sweet])
    kiwifruit = Fruit("kiwifruit", has_shape=[round], has_color=[green], original_from=[new_zealand])
#     strawberry = Fruit("strawberry", has_color=[red], has_taste=[sweet])
#     raspberry = Fruit("raspberry", has_color=[red], has_taste=[sweet])
#     pineapple = Fruit("pineapple", has_color=[yellow], has_taste=[sweet])
#     mandarin = Fruit("mandarin", has_color=[yellow], has_taste=[sweet, juicy])
    avocado = Fruit("avocado", has_shape=[round], has_color=[green], has_taste=[grassy], original_from=[america])
#     watermelon = Fruit("watermelon", has_color=[green, red], has_taste=[sweet, juicy])
#     grape = Fruit("grape", has_color=[green, red], has_taste=[juicy, sweet])
#     cherry = Fruit("cherry", has_color=[red], has_taste=[sweet])
    pear = Fruit("pear", has_shape=[round], has_color=[green, yellow], has_taste=[juicy, sweet])
   

    green_apple = Fruit("green_apple", has_color=[green], has_taste=[sweet], original_from=[america])
    red_apple = Fruit("red_apple", has_color=[red], has_taste=[sweet], original_from=[america])

    apple = Fruit("apple", has_child_food=[red_apple])
    apple = Fruit("apple", has_child_food=[green_apple])
    
    beaf = Meat("beaf", has_taste=[meaty], has_color=[red])
    chicken = Meat("chicken", has_taste=[meaty], has_color=[white])
    lamb = Meat("lamb", has_taste=[meaty], has_color=[red])
    pork = Meat("pork", has_taste=[meaty], has_color=[red])
    
    salmon = Fish("salmon", has_taste=[fishy], has_nutrition=[fat, protein])
    shrimp = Fish("shrimp", has_taste=[fishy], has_nutrition=[protein])
    squid = Fish("squid", has_taste=[fishy], has_nutrition=[protein])
    fillet = Fish("fillet", has_taste=[fishy], has_nutrition=[fat, protein])
    
    egg = Dairy("egg", has_nutrition=[protein])
    yoghurt = Dairy("yoghurt", has_taste=[sweet], has_nutrition=[protein])
    cheese = Dairy("cheese", has_nutrition=[protein, fat])
    milk = Dairy("milk", has_nutrition=[protein, fat], has_taste = [sweet])
    
    rice = Grain("rice", has_shape=[round, long])
    noodle = Grain("noodle", has_shape=[long])
    pasta = Grain("pasta", has_shape=[round, long])
    bread = Grain("bread", has_shape=[long], has_taste=[tangy])
    corn = Grain("corn", has_color=[yellow], original_from=[america])
    
    
    pan = Kitchenware('pan', has_function=[fry], has_color=[red])   
    pot = Kitchenware('pot', has_function=[boil], has_color=[red])  
    chopping_board = Kitchenware('chopping_board', has_function=[cutting])  

    spoon = Tableware('spoon', has_function=[drinking])
    fork = Tableware('fork', has_function=[poking, stabbing])
    knife = Tableware('knife', has_function=[cutting])
    plate = Tableware('plate', has_function=[servefood], has_shape=[circular])

    plate = Tableware('plate', has_function=[servefood], has_shape=[circular], has_sub_function=[chopping_board])

  
    print('ok-onto1')

ok-onto1

In [3]:
# JY, - First part - Unroll ontology 
# --- First method set, recursive methods to turn objects and relations into some sort of consistent format ---
# --- Output: list of tuples to represent the entity and all its relationships including a depth tracker ---

# recursive method to get class hierarchy
def get_types_hierarchy(x):
    if issubclass(x, Thing):
        # to filter out Thing's, uncomment below
        # if x is not Thing:
        return [x, *get_types_hierarchy(x.__bases__[0])]
    return []

# gets a tuple representing a relationship (recursive with get_object_pairs)
def get_relation_pairs(o, depth=1):
    if depth>=10:
        print('Warning, depth of 10 hit, check for cycles')
        return []
    return [('relation', p, get_object_pairs(getattr(o, p._name), depth=depth+1)) 
    for p in o.get_properties() if ObjectPropertyClass]

# gets a tuple representing a pair of objects (recursive with get_relation_pairs), [0, 1, 2, 3] = [entity, types, x, relation_pairs]
def get_object_pairs(objects, limit_domain=[], depth=1):
    return [(
        'entity',
        get_types_hierarchy(type(x)),
        x,
        get_relation_pairs(x, depth))
        for x in objects 
        if len(limit_domain)==0 or any([isinstance(x, y) for y in limit_domain])]


# --- JY - Get ready to build a table from unrolled ontology. 
# --- Second method set, recursive method sets to unroll the hierarchy, ---
# --- Output: collapsed list of dicts with each level of entity/relationship numbered as e1/r1, e2/r2 etc. ---

# works with dictify to flatten out the hierarchy to a one-dict per entity/relationship combination including recurse
def dict_collapse(e, depth=1):
    has_relationships = len(e[3])>0
    if has_relationships:
        return [{f'e{depth}': e[0:3], f'r{depth}': r[0:2], 'n': dictify(r[2], depth+1)} for r in e[3]]
    else:
        return [{f'e{depth}': e[0:3], f'r{depth}': None, 'n': []}]

# removes the "n" column which is used to indicate another level of recursion
def drop_n(d):
    return {k:v for k,v in d.items() if k!='n'}

# helper to flatten nested lists, put two sublists into a combined list. 
def flatten(l):
    return list(chain.from_iterable(l))

# Removes a single level of recursion then calls itself again
def flatten_dicts(dict_list):
    # handle case of no next level and case of having a next level then recurse
    recursed_set = [{**drop_n(e), **n} for e in dict_list for n in e['n']]
    if any(['n' in e for e in recursed_set]):
        recursed_set = flatten_dicts(recursed_set)
    return recursed_set + \
        [drop_n(e) for e in dict_list if len(e['n'])==0]

# controller method to orchestrate the other 2
def dictify(object_pairs, depth=1):
    if depth >= 10:
        print('Warning, depth of 10 hit, check for cycles')
        return []
    collapsed_dicts = flatten([dict_collapse(e, depth) for e in object_pairs])
    return flatten_dicts(collapsed_dicts)

# --- JY Build the table 
# --- Third method set, no more recursion, these methods are just helpful to coerce to a table-like format, could easily write your own methods instead :) ---
# --- Output: dictionary with an entity or list of classes per column making it easier to filter and work with ---

# convert the whole ontology to a table format
from collections import ChainMap
def tablify(object_tuple_dict):
    def generate_entity_dict(k, v):
        if v is None:
            return {}
        elif v[0]=='entity':
            return {f'{k}_classes': v[1], f'{k}_entity': v[2]}
        else:
            return {f'{k}_relation': v[1]}
        
    return [dict(ChainMap(*[generate_entity_dict(k,v) for k,v in x.items()])) for x in object_tuple_dict]

# convert all the entities and classes to strings for easy sentence generation
def stringify_table(dict_table_format):
    return [{k: [x.name for x in v] if isinstance(v, list) else v._name for k,v in x.items()} for x in dict_table_format]

print('ok-Unroll Ontology Functions')
# --- Actually using the above methods! ---

ok-Unroll Ontology Functions

In [61]:
print([onto.Food])

[onto.Food]

In [4]:
# these 2 do the main bulk of the work, you could happily write a function to process object_tuple_dict directly
object_pairs = get_object_pairs(onto.individuals(), [onto.Food])
object_tuple_dict = dictify(object_pairs)

# or use these to get a table sort of format that we can do further processing on to generate questions!
dict_table_format = tablify(object_tuple_dict)
string_table = stringify_table(dict_table_format)

table_cols_threelevels = ['e1_classes', 'e1_entity', 'r1_relation', 'e2_classes', 'e2_entity', 'r2_relation', 'e3_classes', 'e3_entity']

string_df = pd.DataFrame(string_table)[table_cols_threelevels]
print('Table: string_df, Onto: Food')
string_df[0:10]

Table: string_df, Onto: Food

,e1_classes,e1_entity,r1_relation,e2_classes,e2_entity,r2_relation,e3_classes,e3_entity
0,"[Vegetable, Food, Thing]",tomato,original_from,"[Country, Thing]",america,NaN,NaN,NaN
1,"[Vegetable, Food, Thing]",tomato,has_shape,"[Shape, Thing]",round,NaN,NaN,NaN
2,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",juicy,NaN,NaN,NaN
3,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",sweet,NaN,NaN,NaN
4,"[Vegetable, Food, Thing]",tomato,has_color,"[Color, Thing]",red,NaN,NaN,NaN
5,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",juicy,NaN,NaN,NaN
6,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",sweet,NaN,NaN,NaN
7,"[Vegetable, Food, Thing]",broccoli,has_color,"[Color, Thing]",green,NaN,NaN,NaN
8,"[Vegetable, Food, Thing]",chilli,original_from,"[Country, Thing]",america,NaN,NaN,NaN
9,"[Vegetable, Food, Thing]",chilli,has_taste,"[Taste, Thing]",spicy,NaN,NaN,NaN

In [5]:
# these 2 do the main bulk of the work, you could happily write a function to process object_tuple_dict directly
object_pairs = get_object_pairs(onto.individuals(), [onto.Food])
object_tuple_dict = dictify(object_pairs)

# or use these to get a table sort of format that we can do further processing on to generate questions!
dict_table_format = tablify(object_tuple_dict)
string_table = stringify_table(dict_table_format)

# can make an entity df with the individuals/classes if you want to access properties and inspect them, etc.
# entity_df = pd.DataFrame(dict_table_format)
# entity_df.explode('e2_classes').explode('e1_classes')
table_cols_threelevels = ['e1_classes', 'e1_entity', 'r1_relation', 'e2_classes', 'e2_entity', 'r2_relation', 'e3_classes', 'e3_entity']

# or can make a string df use the "string_table" for sentence generation purposes
string_df1 = pd.DataFrame(string_table)[table_cols_threelevels].fillna('').query("r1_relation!=''")
print('print ok-Table0: string_df1. fillna ''and r1_relation is not null')
string_df1

print ok-Table0: string_df1. fillna and r1_relation is not null

,e1_classes,e1_entity,r1_relation,e2_classes,e2_entity,r2_relation,e3_classes,e3_entity
0,"[Vegetable, Food, Thing]",tomato,original_from,"[Country, Thing]",america,,,
1,"[Vegetable, Food, Thing]",tomato,has_shape,"[Shape, Thing]",round,,,
2,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",juicy,,,
3,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",sweet,,,
4,"[Vegetable, Food, Thing]",tomato,has_color,"[Color, Thing]",red,,,
5,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",juicy,,,
6,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",sweet,,,
7,"[Vegetable, Food, Thing]",broccoli,has_color,"[Color, Thing]",green,,,
8,"[Vegetable, Food, Thing]",chilli,original_from,"[Country, Thing]",america,,,
9,"[Vegetable, Food, Thing]",chilli,has_taste,"[Taste, Thing]",spicy,,,
10,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",green,,,
11,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",red,,,
12,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",yellow,,,
13,"[Vegetable, Food, Thing]",carrot,has_shape,"[Shape, Thing]",long,,,
14,"[Vegetable, Food, Thing]",carrot,has_taste,"[Taste, Thing]",woody,,,
15,"[Vegetable, Food, Thing]",carrot,has_color,"[Color, Thing]",yellow,,,
16,"[Vegetable, Food, Thing]",capsicum,original_from,"[Country, Thing]",america,,,
17,"[Vegetable, Food, Thing]",capsicum,has_taste,"[Taste, Thing]",spicy,,,
18,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",green,,,
19,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",red,,,
20,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",yellow,,,
21,"[Vegetable, Food, Thing]",cucumber,original_from,"[Country, Thing]",india,,,
22,"[Vegetable, Food, Thing]",cucumber,has_shape,"[Shape, Thing]",long,,,
23,"[Vegetable, Food, Thing]",cucumber,has_taste,"[Taste, Thing]",juicy,,,
24,"[Vegetable, Food, Thing]",cucumber,has_color,"[Color, Thing]",green,,,
25,"[Vegetable, Food, Thing]",cabbage,has_taste,"[Taste, Thing]",sweet,,,
26,"[Vegetable, Food, Thing]",garlic,original_from,"[Country, Thing]",asia,,,
27,"[Vegetable, Food, Thing]",garlic,has_taste,"[Taste, Thing]",pungent,,,
28,"[Vegetable, Food, Thing]",garlic,has_color,"[Color, Thing]",white,,,
29,"[Vegetable, Food, Thing]",lettuce,original_from,"[Country, Thing]",egypt,,,
30,"[Vegetable, Food, Thing]",lettuce,has_shape,"[Shape, Thing]",round,,,
31,"[Vegetable, Food, Thing]",lettuce,has_color,"[Color, Thing]",green,,,
32,"[Vegetable, Food, Thing]",mushroom,has_color,"[Color, Thing]",white,,,
33,"[Vegetable, Food, Thing]",onion,original_from,"[Country, Thing]",australia,,,
34,"[Vegetable, Food, Thing]",onion,original_from,"[Country, Thing]",new_zealand,,,
35,"[Vegetable, Food, Thing]",onion,has_shape,"[Shape, Thing]",round,,,
36,"[Vegetable, Food, Thing]",onion,has_taste,"[Taste, Thing]",pungent,,,
37,"[Vegetable, Food, Thing]",onion,has_color,"[Color, Thing]",yellow,,,
38,"[Vegetable, Food, Thing]",onion,has_color,"[Color, Thing]",purple,,,
39,"[Vegetable, Food, Thing]",potato,original_from,"[Country, Thing]",america,,,
40,"[Vegetable, Food, Thing]",potato,has_taste,"[Taste, Thing]",sweet,,,
41,"[Vegetable, Food, Thing]",pumpkin,original_from,"[Country, Thing]",mexica,,,
42,"[Vegetable, Food, Thing]",pumpkin,has_taste,"[Taste, Thing]",sweet,,,
43,"[Vegetable, Food, Thing]",pumpkin,has_color,"[Color, Thing]",yellow,,,
44,"[Vegetable, Food, Thing]",eggplant,has_shape,"[Shape, Thing]",long,,,
45,"[Vegetable, Food, Thing]",eggplant,has_taste,"[Taste, Thing]",sweet,,,
46,"[Vegetable, Food, Thing]",eggplant,has_color,"[Color, Thing]",purple,,,
47,"[Vegetable, Food, Thing]",pepper,has_taste,"[Taste, Thing]",spicy,,,
48,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",green,,,
49,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",red,,,
50,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",yellow,,,
51,"[Fruit, Food, Thing]",orange,has_color,"[Color, Thing]",yellow,,,
52,"[Fruit, Food, Thing]",apple,original_from,"[Country, Thing]",america,,,
53,"[Fruit, Food, Thing]",apple,has_color,"[Color, Thing]",green,,,
54,"[Fruit, Food, Thing]",apple,has_color,"[Color, Thing]",red,,,
55,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,original_from,"[Country, Thing]",america
56,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,has_taste,"[Taste, Thing]",sweet
57,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,has_color,"[Color, Thing]",green
58,"[Fruit, Food, Thing]",banana,has_shape,"[Shape, Thing]",long,,,
59,"[Fruit, Food, Thing]",banana,has_color,"[Color, Thing]",yellow,,,
60,"[Fruit, Food, Thing]",lemon,original_from,"[Country, Thing]",china,,,
61,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",sweet,,,
62,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",sour,,,
63,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",juicy,,,
64,"[Fruit, Food, Thing]",lemon,has_color,"[Color, Thing]",yellow,,,
65,"[Fruit, Food, Thing]",plum,original_from,"[Country, Thing]",china,,,
66,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",sweet,,,
67,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",sour,,,
68,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",juicy,,,
69,"[Fruit, Food, Thing]",plum,has_color,"[Color, Thing]",purple,,,
70,"[Fruit, Food, Thing]",lime,original_from,"[Country, Thing]",china,,,
71,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",sweet,,,
72,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",sour,,,
73,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",juicy,,,
74,"[Fruit, Food, Thing]",lime,has_color,"[Color, Thing]",green,,,
75,"[Fruit, Food, Thing]",kiwifruit,original_from,"[Country, Thing]",new_zealand,,,
76,"[Fruit, Food, Thing]",kiwifruit,has_shape,"[Shape, Thing]",round,,,
77,"[Fruit, Food, Thing]",kiwifruit,has_color,"[Color, Thing]",green,,,
78,"[Fruit, Food, Thing]",avocado,original_from,"[Country, Thing]",america,,,
79,"[Fruit, Food, Thing]",avocado,has_shape,"[Shape, Thing]",round,,,
80,"[Fruit, Food, Thing]",avocado,has_taste,"[Taste, Thing]",grassy,,,
81,"[Fruit, Food, Thing]",avocado,has_color,"[Color, Thing]",green,,,
82,"[Fruit, Food, Thing]",pear,has_shape,"[Shape, Thing]",round,,,
83,"[Fruit, Food, Thing]",pear,has_taste,"[Taste, Thing]",juicy,,,
84,"[Fruit, Food, Thing]",pear,has_taste,"[Taste, Thing]",sweet,,,
85,"[Fruit, Food, Thing]",pear,has_color,"[Color, Thing]",green,,,
86,"[Fruit, Food, Thing]",pear,has_color,"[Color, Thing]",yellow,,,
87,"[Fruit, Food, Thing]",green_apple,original_from,"[Country, Thing]",america,,,
88,"[Fruit, Food, Thing]",green_apple,has_taste,"[Taste, Thing]",sweet,,,
89,"[Fruit, Food, Thing]",green_apple,has_color,"[Color, Thing]",green,,,
90,"[Fruit, Food, Thing]",red_apple,original_from,"[Country, Thing]",america,,,
91,"[Fruit, Food, Thing]",red_apple,has_taste,"[Taste, Thing]",sweet,,,
92,"[Fruit, Food, Thing]",red_apple,has_color,"[Color, Thing]",red,,,
93,"[Meat, Food, Thing]",beaf,has_taste,"[Taste, Thing]",meaty,,,
94,"[Meat, Food, Thing]",beaf,has_color,"[Color, Thing]",red,,,
95,"[Meat, Food, Thing]",chicken,has_taste,"[Taste, Thing]",meaty,,,
96,"[Meat, Food, Thing]",chicken,has_color,"[Color, Thing]",white,,,
97,"[Meat, Food, Thing]",lamb,has_taste,"[Taste, Thing]",meaty,,,
98,"[Meat, Food, Thing]",lamb,has_color,"[Color, Thing]",red,,,
99,"[Meat, Food, Thing]",pork,has_taste,"[Taste, Thing]",meaty,,,
100,"[Meat, Food, Thing]",pork,has_color,"[Color, Thing]",red,,,
101,"[Fish, Food, Thing]",salmon,has_nutrition,"[Nutrition, Thing]",fat,,,
102,"[Fish, Food, Thing]",salmon,has_nutrition,"[Nutrition, Thing]",protein,,,
103,"[Fish, Food, Thing]",salmon,has_taste,"[Taste, Thing]",fishy,,,
104,"[Fish, Food, Thing]",shrimp,has_nutrition,"[Nutrition, Thing]",protein,,,
105,"[Fish, Food, Thing]",shrimp,has_taste,"[Taste, Thing]",fishy,,,
106,"[Fish, Food, Thing]",squid,has_nutrition,"[Nutrition, Thing]",protein,,,
107,"[Fish, Food, Thing]",squid,has_taste,"[Taste, Thing]",fishy,,,
108,"[Fish, Food, Thing]",fillet,has_nutrition,"[Nutrition, Thing]",fat,,,
109,"[Fish, Food, Thing]",fillet,has_nutrition,"[Nutrition, Thing]",protein,,,
110,"[Fish, Food, Thing]",fillet,has_taste,"[Taste, Thing]",fishy,,,
111,"[Dairy, Food, Thing]",egg,has_nutrition,"[Nutrition, Thing]",protein,,,
112,"[Dairy, Food, Thing]",yoghurt,has_nutrition,"[Nutrition, Thing]",protein,,,
113,"[Dairy, Food, Thing]",yoghurt,has_taste,"[Taste, Thing]",sweet,,,
114,"[Dairy, Food, Thing]",cheese,has_nutrition,"[Nutrition, Thing]",protein,,,
115,"[Dairy, Food, Thing]",cheese,has_nutrition,"[Nutrition, Thing]",fat,,,
116,"[Dairy, Food, Thing]",milk,has_nutrition,"[Nutrition, Thing]",protein,,,
117,"[Dairy, Food, Thing]",milk,has_nutrition,"[Nutrition, Thing]",fat,,,
118,"[Dairy, Food, Thing]",milk,has_taste,"[Taste, Thing]",sweet,,,
119,"[Grain, Food, Thing]",rice,has_shape,"[Shape, Thing]",round,,,
120,"[Grain, Food, Thing]",rice,has_shape,"[Shape, Thing]",long,,,
121,"[Grain, Food, Thing]",noodle,has_shape,"[Shape, Thing]",long,,,
122,"[Grain, Food, Thing]",pasta,has_shape,"[Shape, Thing]",round,,,
123,"[Grain, Food, Thing]",pasta,has_shape,"[Shape, Thing]",long,,,
124,"[Grain, Food, Thing]",bread,has_shape,"[Shape, Thing]",long,,,
125,"[Grain, Food, Thing]",bread,has_taste,"[Taste, Thing]",tangy,,,
126,"[Grain, Food, Thing]",corn,original_from,"[Country, Thing]",america,,,
127,"[Grain, Food, Thing]",corn,has_color,"[Color, Thing]",yellow,,,

In [6]:
# Print some test questions

exp = string_df1.explode('e2_classes').explode('e1_classes')

some_questions = (
    ('Count how many ' + string_df1.e1_entity + ' ' + string_df1.r1_relation + ' ' + string_df1.e2_entity).unique().tolist() +
    ('Count how many ' + exp.e1_classes + ' ' + exp.r1_relation + ' ' + exp.e2_entity).unique().tolist()
)

pprint(some_questions)

['Count how many tomato original_from america',
 'Count how many tomato has_shape round',
 'Count how many tomato has_taste juicy',
 'Count how many tomato has_taste sweet',
 'Count how many tomato has_color red',
 'Count how many broccoli has_taste juicy',
 'Count how many broccoli has_taste sweet',
 'Count how many broccoli has_color green',
 'Count how many chilli original_from america',
 'Count how many chilli has_taste spicy',
 'Count how many chilli has_color green',
 'Count how many chilli has_color red',
 'Count how many chilli has_color yellow',
 'Count how many carrot has_shape long',
 'Count how many carrot has_taste woody',
 'Count how many carrot has_color yellow',
 'Count how many capsicum original_from america',
 'Count how many capsicum has_taste spicy',
 'Count how many capsicum has_color green',
 'Count how many capsicum has_color red',
 'Count how many capsicum has_color yellow',
 'Count how many cucumber original_from india',
 'Count how many cucumber has_shape long',
 'Count how many cucumber has_taste juicy',
 'Count how many cucumber has_color green',
 'Count how many cabbage has_taste sweet',
 'Count how many garlic original_from asia',
 'Count how many garlic has_taste pungent',
 'Count how many garlic has_color white',
 'Count how many lettuce original_from egypt',
 'Count how many lettuce has_shape round',
 'Count how many lettuce has_color green',
 'Count how many mushroom has_color white',
 'Count how many onion original_from australia',
 'Count how many onion original_from new_zealand',
 'Count how many onion has_shape round',
 'Count how many onion has_taste pungent',
 'Count how many onion has_color yellow',
 'Count how many onion has_color purple',
 'Count how many potato original_from america',
 'Count how many potato has_taste sweet',
 'Count how many pumpkin original_from mexica',
 'Count how many pumpkin has_taste sweet',
 'Count how many pumpkin has_color yellow',
 'Count how many eggplant has_shape long',
 'Count how many eggplant has_taste sweet',
 'Count how many eggplant has_color purple',
 'Count how many pepper has_taste spicy',
 'Count how many pepper has_color green',
 'Count how many pepper has_color red',
 'Count how many pepper has_color yellow',
 'Count how many orange has_color yellow',
 'Count how many apple original_from america',
 'Count how many apple has_color green',
 'Count how many apple has_color red',
 'Count how many apple has_child_food green_apple',
 'Count how many banana has_shape long',
 'Count how many banana has_color yellow',
 'Count how many lemon original_from china',
 'Count how many lemon has_taste sweet',
 'Count how many lemon has_taste sour',
 'Count how many lemon has_taste juicy',
 'Count how many lemon has_color yellow',
 'Count how many plum original_from china',
 'Count how many plum has_taste sweet',
 'Count how many plum has_taste sour',
 'Count how many plum has_taste juicy',
 'Count how many plum has_color purple',
 'Count how many lime original_from china',
 'Count how many lime has_taste sweet',
 'Count how many lime has_taste sour',
 'Count how many lime has_taste juicy',
 'Count how many lime has_color green',
 'Count how many kiwifruit original_from new_zealand',
 'Count how many kiwifruit has_shape round',
 'Count how many kiwifruit has_color green',
 'Count how many avocado original_from america',
 'Count how many avocado has_shape round',
 'Count how many avocado has_taste grassy',
 'Count how many avocado has_color green',
 'Count how many pear has_shape round',
 'Count how many pear has_taste juicy',
 'Count how many pear has_taste sweet',
 'Count how many pear has_color green',
 'Count how many pear has_color yellow',
 'Count how many green_apple original_from america',
 'Count how many green_apple has_taste sweet',
 'Count how many green_apple has_color green',
 'Count how many red_apple original_from america',
 'Count how many red_apple has_taste sweet',
 'Count how many red_apple has_color red',
 'Count how many beaf has_taste meaty',
 'Count how many beaf has_color red',
 'Count how many chicken has_taste meaty',
 'Count how many chicken has_color white',
 'Count how many lamb has_taste meaty',
 'Count how many lamb has_color red',
 'Count how many pork has_taste meaty',
 'Count how many pork has_color red',
 'Count how many salmon has_nutrition fat',
 'Count how many salmon has_nutrition protein',
 'Count how many salmon has_taste fishy',
 'Count how many shrimp has_nutrition protein',
 'Count how many shrimp has_taste fishy',
 'Count how many squid has_nutrition protein',
 'Count how many squid has_taste fishy',
 'Count how many fillet has_nutrition fat',
 'Count how many fillet has_nutrition protein',
 'Count how many fillet has_taste fishy',
 'Count how many egg has_nutrition protein',
 'Count how many yoghurt has_nutrition protein',
 'Count how many yoghurt has_taste sweet',
 'Count how many cheese has_nutrition protein',
 'Count how many cheese has_nutrition fat',
 'Count how many milk has_nutrition protein',
 'Count how many milk has_nutrition fat',
 'Count how many milk has_taste sweet',
 'Count how many rice has_shape round',
 'Count how many rice has_shape long',
 'Count how many noodle has_shape long',
 'Count how many pasta has_shape round',
 'Count how many pasta has_shape long',
 'Count how many bread has_shape long',
 'Count how many bread has_taste tangy',
 'Count how many corn original_from america',
 'Count how many corn has_color yellow',
 'Count how many Vegetable original_from america',
 'Count how many Food original_from america',
 'Count how many Thing original_from america',
 'Count how many Vegetable has_shape round',
 'Count how many Food has_shape round',
 'Count how many Thing has_shape round',
 'Count how many Vegetable has_taste juicy',
 'Count how many Food has_taste juicy',
 'Count how many Thing has_taste juicy',
 'Count how many Vegetable has_taste sweet',
 'Count how many Food has_taste sweet',
 'Count how many Thing has_taste sweet',
 'Count how many Vegetable has_color red',
 'Count how many Food has_color red',
 'Count how many Thing has_color red',
 'Count how many Vegetable has_color green',
 'Count how many Food has_color green',
 'Count how many Thing has_color green',
 'Count how many Vegetable has_taste spicy',
 'Count how many Food has_taste spicy',
 'Count how many Thing has_taste spicy',
 'Count how many Vegetable has_color yellow',
 'Count how many Food has_color yellow',
 'Count how many Thing has_color yellow',
 'Count how many Vegetable has_shape long',
 'Count how many Food has_shape long',
 'Count how many Thing has_shape long',
 'Count how many Vegetable has_taste woody',
 'Count how many Food has_taste woody',
 'Count how many Thing has_taste woody',
 'Count how many Vegetable original_from india',
 'Count how many Food original_from india',
 'Count how many Thing original_from india',
 'Count how many Vegetable original_from asia',
 'Count how many Food original_from asia',
 'Count how many Thing original_from asia',
 'Count how many Vegetable has_taste pungent',
 'Count how many Food has_taste pungent',
 'Count how many Thing has_taste pungent',
 'Count how many Vegetable has_color white',
 'Count how many Food has_color white',
 'Count how many Thing has_color white',
 'Count how many Vegetable original_from egypt',
 'Count how many Food original_from egypt',
 'Count how many Thing original_from egypt',
 'Count how many Vegetable original_from australia',
 'Count how many Food original_from australia',
 'Count how many Thing original_from australia',
 'Count how many Vegetable original_from new_zealand',
 'Count how many Food original_from new_zealand',
 'Count how many Thing original_from new_zealand',
 'Count how many Vegetable has_color purple',
 'Count how many Food has_color purple',
 'Count how many Thing has_color purple',
 'Count how many Vegetable original_from mexica',
 'Count how many Food original_from mexica',
 'Count how many Thing original_from mexica',
 'Count how many Fruit has_color yellow',
 'Count how many Fruit original_from america',
 'Count how many Fruit has_color green',
 'Count how many Fruit has_color red',
 'Count how many Fruit has_child_food green_apple',
 'Count how many Food has_child_food green_apple',
 'Count how many Thing has_child_food green_apple',
 'Count how many Fruit has_shape long',
 'Count how many Fruit original_from china',
 'Count how many Food original_from china',
 'Count how many Thing original_from china',
 'Count how many Fruit has_taste sweet',
 'Count how many Fruit has_taste sour',
 'Count how many Food has_taste sour',
 'Count how many Thing has_taste sour',
 'Count how many Fruit has_taste juicy',
 'Count how many Fruit has_color purple',
 'Count how many Fruit original_from new_zealand',
 'Count how many Fruit has_shape round',
 'Count how many Fruit has_taste grassy',
 'Count how many Food has_taste grassy',
 'Count how many Thing has_taste grassy',
 'Count how many Meat has_taste meaty',
 'Count how many Food has_taste meaty',
 'Count how many Thing has_taste meaty',
 'Count how many Meat has_color red',
 'Count how many Meat has_color white',
 'Count how many Fish has_nutrition fat',
 'Count how many Food has_nutrition fat',
 'Count how many Thing has_nutrition fat',
 'Count how many Fish has_nutrition protein',
 'Count how many Food has_nutrition protein',
 'Count how many Thing has_nutrition protein',
 'Count how many Fish has_taste fishy',
 'Count how many Food has_taste fishy',
 'Count how many Thing has_taste fishy',
 'Count how many Dairy has_nutrition protein',
 'Count how many Dairy has_taste sweet',
 'Count how many Dairy has_nutrition fat',
 'Count how many Grain has_shape round',
 'Count how many Grain has_shape long',
 'Count how many Grain has_taste tangy',
 'Count how many Food has_taste tangy',
 'Count how many Thing has_taste tangy',
 'Count how many Grain original_from america',
 'Count how many Grain has_color yellow']

In [7]:
string_df1.head()

,e1_classes,e1_entity,r1_relation,e2_classes,e2_entity,r2_relation,e3_classes,e3_entity
0,"[Vegetable, Food, Thing]",tomato,original_from,"[Country, Thing]",america,,,
1,"[Vegetable, Food, Thing]",tomato,has_shape,"[Shape, Thing]",round,,,
2,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",juicy,,,
3,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",sweet,,,
4,"[Vegetable, Food, Thing]",tomato,has_color,"[Color, Thing]",red,,,

In [8]:
exp.head()

,e1_classes,e1_entity,r1_relation,e2_classes,e2_entity,r2_relation,e3_classes,e3_entity
0,Vegetable,tomato,original_from,Country,america,,,
0,Food,tomato,original_from,Country,america,,,
0,Thing,tomato,original_from,Country,america,,,
0,Vegetable,tomato,original_from,Thing,america,,,
0,Food,tomato,original_from,Thing,america,,,

In [9]:
# --- Time for logic - part1 ---
import re
multi_space = re.compile('\\s+')
multi_space_v = np.vectorize(lambda x: multi_space.sub(' ', x))

def unique_concat(*args):
    return np.char.array(multi_space_v(np.unique(np.concatenate(args))))

# The below code is the print the unique indices of np.unique. 
# np.unique has a return which is the indices of the input array that give the unique values

# def unique_concat(*args):
#     print(f"{args}")
#     np_unique_index = np.unique(np.concatenate(args), return_index=True)
#     print(list(np_unique_index[1]))
# #     sys.exit()
# #     print(list(np_unique_index[0]))
#     return np.char.array(multi_space_v(np_unique_index[0]))

print('ok-Time for logic: run unique_concat function')

ok-Time for logic: run unique_concat function

In [10]:
# Time for logic: Table adding "not" column first. 
# key goal here is to add a column which has either "" or "not" and then simply explode and insert into question

print('OK-Table1: not_df, and cls_not_df')

not_df = string_df1.copy()
not_df['not'] = [['', 'not'] for i in not_df.index]
ent_not_df = not_df.explode('not')
cls_not_df = ent_not_df.explode('e1_classes')
cls_not_df[500:600]

OK-Table1: not_df, and cls_not_df

,e1_classes,e1_entity,r1_relation,e2_classes,e2_entity,r2_relation,e3_classes,e3_entity,not
83,Thing,pear,has_taste,"[Taste, Thing]",juicy,,,,
83,Fruit,pear,has_taste,"[Taste, Thing]",juicy,,,,not
83,Food,pear,has_taste,"[Taste, Thing]",juicy,,,,not
83,Thing,pear,has_taste,"[Taste, Thing]",juicy,,,,not
84,Fruit,pear,has_taste,"[Taste, Thing]",sweet,,,,
84,Food,pear,has_taste,"[Taste, Thing]",sweet,,,,
84,Thing,pear,has_taste,"[Taste, Thing]",sweet,,,,
84,Fruit,pear,has_taste,"[Taste, Thing]",sweet,,,,not
84,Food,pear,has_taste,"[Taste, Thing]",sweet,,,,not
84,Thing,pear,has_taste,"[Taste, Thing]",sweet,,,,not
85,Fruit,pear,has_color,"[Color, Thing]",green,,,,
85,Food,pear,has_color,"[Color, Thing]",green,,,,
85,Thing,pear,has_color,"[Color, Thing]",green,,,,
85,Fruit,pear,has_color,"[Color, Thing]",green,,,,not
85,Food,pear,has_color,"[Color, Thing]",green,,,,not
85,Thing,pear,has_color,"[Color, Thing]",green,,,,not
86,Fruit,pear,has_color,"[Color, Thing]",yellow,,,,
86,Food,pear,has_color,"[Color, Thing]",yellow,,,,
86,Thing,pear,has_color,"[Color, Thing]",yellow,,,,
86,Fruit,pear,has_color,"[Color, Thing]",yellow,,,,not
86,Food,pear,has_color,"[Color, Thing]",yellow,,,,not
86,Thing,pear,has_color,"[Color, Thing]",yellow,,,,not
87,Fruit,green_apple,original_from,"[Country, Thing]",america,,,,
87,Food,green_apple,original_from,"[Country, Thing]",america,,,,
87,Thing,green_apple,original_from,"[Country, Thing]",america,,,,
87,Fruit,green_apple,original_from,"[Country, Thing]",america,,,,not
87,Food,green_apple,original_from,"[Country, Thing]",america,,,,not
87,Thing,green_apple,original_from,"[Country, Thing]",america,,,,not
88,Fruit,green_apple,has_taste,"[Taste, Thing]",sweet,,,,
88,Food,green_apple,has_taste,"[Taste, Thing]",sweet,,,,
88,Thing,green_apple,has_taste,"[Taste, Thing]",sweet,,,,
88,Fruit,green_apple,has_taste,"[Taste, Thing]",sweet,,,,not
88,Food,green_apple,has_taste,"[Taste, Thing]",sweet,,,,not
88,Thing,green_apple,has_taste,"[Taste, Thing]",sweet,,,,not
89,Fruit,green_apple,has_color,"[Color, Thing]",green,,,,
89,Food,green_apple,has_color,"[Color, Thing]",green,,,,
89,Thing,green_apple,has_color,"[Color, Thing]",green,,,,
89,Fruit,green_apple,has_color,"[Color, Thing]",green,,,,not
89,Food,green_apple,has_color,"[Color, Thing]",green,,,,not
89,Thing,green_apple,has_color,"[Color, Thing]",green,,,,not
90,Fruit,red_apple,original_from,"[Country, Thing]",america,,,,
90,Food,red_apple,original_from,"[Country, Thing]",america,,,,
90,Thing,red_apple,original_from,"[Country, Thing]",america,,,,
90,Fruit,red_apple,original_from,"[Country, Thing]",america,,,,not
90,Food,red_apple,original_from,"[Country, Thing]",america,,,,not
90,Thing,red_apple,original_from,"[Country, Thing]",america,,,,not
91,Fruit,red_apple,has_taste,"[Taste, Thing]",sweet,,,,
91,Food,red_apple,has_taste,"[Taste, Thing]",sweet,,,,
91,Thing,red_apple,has_taste,"[Taste, Thing]",sweet,,,,
91,Fruit,red_apple,has_taste,"[Taste, Thing]",sweet,,,,not
91,Food,red_apple,has_taste,"[Taste, Thing]",sweet,,,,not
91,Thing,red_apple,has_taste,"[Taste, Thing]",sweet,,,,not
92,Fruit,red_apple,has_color,"[Color, Thing]",red,,,,
92,Food,red_apple,has_color,"[Color, Thing]",red,,,,
92,Thing,red_apple,has_color,"[Color, Thing]",red,,,,
92,Fruit,red_apple,has_color,"[Color, Thing]",red,,,,not
92,Food,red_apple,has_color,"[Color, Thing]",red,,,,not
92,Thing,red_apple,has_color,"[Color, Thing]",red,,,,not
93,Meat,beaf,has_taste,"[Taste, Thing]",meaty,,,,
93,Food,beaf,has_taste,"[Taste, Thing]",meaty,,,,
93,Thing,beaf,has_taste,"[Taste, Thing]",meaty,,,,
93,Meat,beaf,has_taste,"[Taste, Thing]",meaty,,,,not
93,Food,beaf,has_taste,"[Taste, Thing]",meaty,,,,not
93,Thing,beaf,has_taste,"[Taste, Thing]",meaty,,,,not
94,Meat,beaf,has_color,"[Color, Thing]",red,,,,
94,Food,beaf,has_color,"[Color, Thing]",red,,,,
94,Thing,beaf,has_color,"[Color, Thing]",red,,,,
94,Meat,beaf,has_color,"[Color, Thing]",red,,,,not
94,Food,beaf,has_color,"[Color, Thing]",red,,,,not
94,Thing,beaf,has_color,"[Color, Thing]",red,,,,not
95,Meat,chicken,has_taste,"[Taste, Thing]",meaty,,,,
95,Food,chicken,has_taste,"[Taste, Thing]",meaty,,,,
95,Thing,chicken,has_taste,"[Taste, Thing]",meaty,,,,
95,Meat,chicken,has_taste,"[Taste, Thing]",meaty,,,,not
95,Food,chicken,has_taste,"[Taste, Thing]",meaty,,,,not
95,Thing,chicken,has_taste,"[Taste, Thing]",meaty,,,,not
96,Meat,chicken,has_color,"[Color, Thing]",white,,,,
96,Food,chicken,has_color,"[Color, Thing]",white,,,,
96,Thing,chicken,has_color,"[Color, Thing]",white,,,,
96,Meat,chicken,has_color,"[Color, Thing]",white,,,,not
96,Food,chicken,has_color,"[Color, Thing]",white,,,,not
96,Thing,chicken,has_color,"[Color, Thing]",white,,,,not
97,Meat,lamb,has_taste,"[Taste, Thing]",meaty,,,,
97,Food,lamb,has_taste,"[Taste, Thing]",meaty,,,,
97,Thing,lamb,has_taste,"[Taste, Thing]",meaty,,,,
97,Meat,lamb,has_taste,"[Taste, Thing]",meaty,,,,not
97,Food,lamb,has_taste,"[Taste, Thing]",meaty,,,,not
97,Thing,lamb,has_taste,"[Taste, Thing]",meaty,,,,not
98,Meat,lamb,has_color,"[Color, Thing]",red,,,,
98,Food,lamb,has_color,"[Color, Thing]",red,,,,
98,Thing,lamb,has_color,"[Color, Thing]",red,,,,
98,Meat,lamb,has_color,"[Color, Thing]",red,,,,not
98,Food,lamb,has_color,"[Color, Thing]",red,,,,not
98,Thing,lamb,has_color,"[Color, Thing]",red,,,,not
99,Meat,pork,has_taste,"[Taste, Thing]",meaty,,,,
99,Food,pork,has_taste,"[Taste, Thing]",meaty,,,,
99,Thing,pork,has_taste,"[Taste, Thing]",meaty,,,,
99,Meat,pork,has_taste,"[Taste, Thing]",meaty,,,,not
99,Food,pork,has_taste,"[Taste, Thing]",meaty,,,,not
99,Thing,pork,has_taste,"[Taste, Thing]",meaty,,,,not

In [11]:
# Print some test questions with not
incl_not_questions = 'Count how many ' + unique_concat(
    ent_not_df.e1_entity.str.cat(sep=' ', others=[ent_not_df['not'], ent_not_df.r1_relation, ent_not_df.e2_entity]),
    cls_not_df.e1_classes.str.cat(sep=' ', others=[cls_not_df['not'], cls_not_df.r1_relation, cls_not_df.e2_entity])
)

pprint(f'{len(incl_not_questions)} questions in total')
pprint(incl_not_questions)

'458 questions in total'
chararray(['Count how many Dairy has_nutrition fat',
           'Count how many Dairy has_nutrition protein',
           'Count how many Dairy has_taste sweet',
           'Count how many Dairy not has_nutrition fat',
           'Count how many Dairy not has_nutrition protein',
           'Count how many Dairy not has_taste sweet',
           'Count how many Fish has_nutrition fat',
           'Count how many Fish has_nutrition protein',
           'Count how many Fish has_taste fishy',
           'Count how many Fish not has_nutrition fat',
           'Count how many Fish not has_nutrition protein',
           'Count how many Fish not has_taste fishy',
           'Count how many Food has_child_food green_apple',
           'Count how many Food has_color green',
           'Count how many Food has_color purple',
           'Count how many Food has_color red',
           'Count how many Food has_color white',
           'Count how many Food has_color yellow',
           'Count how many Food has_nutrition fat',
           'Count how many Food has_nutrition protein',
           'Count how many Food has_shape long',
           'Count how many Food has_shape round',
           'Count how many Food has_taste fishy',
           'Count how many Food has_taste grassy',
           'Count how many Food has_taste juicy',
           'Count how many Food has_taste meaty',
           'Count how many Food has_taste pungent',
           'Count how many Food has_taste sour',
           'Count how many Food has_taste spicy',
           'Count how many Food has_taste sweet',
           'Count how many Food has_taste tangy',
           'Count how many Food has_taste woody',
           'Count how many Food original_from america',
           'Count how many Food original_from asia',
           'Count how many Food original_from australia',
           'Count how many Food original_from china',
           'Count how many Food original_from egypt',
           'Count how many Food original_from india',
           'Count how many Food original_from mexica',
           'Count how many Food original_from new_zealand',
           'Count how many Food not has_child_food green_apple',
           'Count how many Food not has_color green',
           'Count how many Food not has_color purple',
           'Count how many Food not has_color red',
           'Count how many Food not has_color white',
           'Count how many Food not has_color yellow',
           'Count how many Food not has_nutrition fat',
           'Count how many Food not has_nutrition protein',
           'Count how many Food not has_shape long',
           'Count how many Food not has_shape round',
           'Count how many Food not has_taste fishy',
           'Count how many Food not has_taste grassy',
           'Count how many Food not has_taste juicy',
           'Count how many Food not has_taste meaty',
           'Count how many Food not has_taste pungent',
           'Count how many Food not has_taste sour',
           'Count how many Food not has_taste spicy',
           'Count how many Food not has_taste sweet',
           'Count how many Food not has_taste tangy',
           'Count how many Food not has_taste woody',
           'Count how many Food not original_from america',
           'Count how many Food not original_from asia',
           'Count how many Food not original_from australia',
           'Count how many Food not original_from china',
           'Count how many Food not original_from egypt',
           'Count how many Food not original_from india',
           'Count how many Food not original_from mexica',
           'Count how many Food not original_from new_zealand',
           'Count how many Fruit has_child_food green_apple',
           'Count how many Fruit has_color green',
           'Count how many Fruit has_color purple',
           'Count how many Fruit has_color red',
           'Count how many Fruit has_color yellow',
           'Count how many Fruit has_shape long',
           'Count how many Fruit has_shape round',
           'Count how many Fruit has_taste grassy',
           'Count how many Fruit has_taste juicy',
           'Count how many Fruit has_taste sour',
           'Count how many Fruit has_taste sweet',
           'Count how many Fruit original_from america',
           'Count how many Fruit original_from china',
           'Count how many Fruit original_from new_zealand',
           'Count how many Fruit not has_child_food green_apple',
           'Count how many Fruit not has_color green',
           'Count how many Fruit not has_color purple',
           'Count how many Fruit not has_color red',
           'Count how many Fruit not has_color yellow',
           'Count how many Fruit not has_shape long',
           'Count how many Fruit not has_shape round',
           'Count how many Fruit not has_taste grassy',
           'Count how many Fruit not has_taste juicy',
           'Count how many Fruit not has_taste sour',
           'Count how many Fruit not has_taste sweet',
           'Count how many Fruit not original_from america',
           'Count how many Fruit not original_from china',
           'Count how many Fruit not original_from new_zealand',
           'Count how many Grain has_color yellow',
           'Count how many Grain has_shape long',
           'Count how many Grain has_shape round',
           'Count how many Grain has_taste tangy',
           'Count how many Grain original_from america',
           'Count how many Grain not has_color yellow',
           'Count how many Grain not has_shape long',
           'Count how many Grain not has_shape round',
           'Count how many Grain not has_taste tangy',
           'Count how many Grain not original_from america',
           'Count how many Meat has_color red',
           'Count how many Meat has_color white',
           'Count how many Meat has_taste meaty',
           'Count how many Meat not has_color red',
           'Count how many Meat not has_color white',
           'Count how many Meat not has_taste meaty',
           'Count how many Thing has_child_food green_apple',
           'Count how many Thing has_color green',
           'Count how many Thing has_color purple',
           'Count how many Thing has_color red',
           'Count how many Thing has_color white',
           'Count how many Thing has_color yellow',
           'Count how many Thing has_nutrition fat',
           'Count how many Thing has_nutrition protein',
           'Count how many Thing has_shape long',
           'Count how many Thing has_shape round',
           'Count how many Thing has_taste fishy',
           'Count how many Thing has_taste grassy',
           'Count how many Thing has_taste juicy',
           'Count how many Thing has_taste meaty',
           'Count how many Thing has_taste pungent',
           'Count how many Thing has_taste sour',
           'Count how many Thing has_taste spicy',
           'Count how many Thing has_taste sweet',
           'Count how many Thing has_taste tangy',
           'Count how many Thing has_taste woody',
           'Count how many Thing original_from america',
           'Count how many Thing original_from asia',
           'Count how many Thing original_from australia',
           'Count how many Thing original_from china',
           'Count how many Thing original_from egypt',
           'Count how many Thing original_from india',
           'Count how many Thing original_from mexica',
           'Count how many Thing original_from new_zealand',
           'Count how many Thing not has_child_food green_apple',
           'Count how many Thing not has_color green',
           'Count how many Thing not has_color purple',
           'Count how many Thing not has_color red',
           'Count how many Thing not has_color white',
           'Count how many Thing not has_color yellow',
           'Count how many Thing not has_nutrition fat',
           'Count how many Thing not has_nutrition protein',
           'Count how many Thing not has_shape long',
           'Count how many Thing not has_shape round',
           'Count how many Thing not has_taste fishy',
           'Count how many Thing not has_taste grassy',
           'Count how many Thing not has_taste juicy',
           'Count how many Thing not has_taste meaty',
           'Count how many Thing not has_taste pungent',
           'Count how many Thing not has_taste sour',
           'Count how many Thing not has_taste spicy',
           'Count how many Thing not has_taste sweet',
           'Count how many Thing not has_taste tangy',
           'Count how many Thing not has_taste woody',
           'Count how many Thing not original_from america',
           'Count how many Thing not original_from asia',
           'Count how many Thing not original_from australia',
           'Count how many Thing not original_from china',
           'Count how many Thing not original_from egypt',
           'Count how many Thing not original_from india',
           'Count how many Thing not original_from mexica',
           'Count how many Thing not original_from new_zealand',
           'Count how many Vegetable has_color green',
           'Count how many Vegetable has_color purple',
           'Count how many Vegetable has_color red',
           'Count how many Vegetable has_color white',
           'Count how many Vegetable has_color yellow',
           'Count how many Vegetable has_shape long',
           'Count how many Vegetable has_shape round',
           'Count how many Vegetable has_taste juicy',
           'Count how many Vegetable has_taste pungent',
           'Count how many Vegetable has_taste spicy',
           'Count how many Vegetable has_taste sweet',
           'Count how many Vegetable has_taste woody',
           'Count how many Vegetable original_from america',
           'Count how many Vegetable original_from asia',
           'Count how many Vegetable original_from australia',
           'Count how many Vegetable original_from egypt',
           'Count how many Vegetable original_from india',
           'Count how many Vegetable original_from mexica',
           'Count how many Vegetable original_from new_zealand',
           'Count how many Vegetable not has_color green',
           'Count how many Vegetable not has_color purple',
           'Count how many Vegetable not has_color red',
           'Count how many Vegetable not has_color white',
           'Count how many Vegetable not has_color yellow',
           'Count how many Vegetable not has_shape long',
           'Count how many Vegetable not has_shape round',
           'Count how many Vegetable not has_taste juicy',
           'Count how many Vegetable not has_taste pungent',
           'Count how many Vegetable not has_taste spicy',
           'Count how many Vegetable not has_taste sweet',
           'Count how many Vegetable not has_taste woody',
           'Count how many Vegetable not original_from america',
           'Count how many Vegetable not original_from asia',
           'Count how many Vegetable not original_from australia',
           'Count how many Vegetable not original_from egypt',
           'Count how many Vegetable not original_from india',
           'Count how many Vegetable not original_from mexica',
           'Count how many Vegetable not original_from new_zealand',
           'Count how many apple has_child_food green_apple',
           'Count how many apple has_color green',
           'Count how many apple has_color red',
           'Count how many apple original_from america',
           'Count how many apple not has_child_food green_apple',
           'Count how many apple not has_color green',
           'Count how many apple not has_color red',
           'Count how many apple not original_from america',
           'Count how many avocado has_color green',
           'Count how many avocado has_shape round',
           'Count how many avocado has_taste grassy',
           'Count how many avocado original_from america',
           'Count how many avocado not has_color green',
           'Count how many avocado not has_shape round',
           'Count how many avocado not has_taste grassy',
           'Count how many avocado not original_from america',
           'Count how many banana has_color yellow',
           'Count how many banana has_shape long',
           'Count how many banana not has_color yellow',
           'Count how many banana not has_shape long',
           'Count how many beaf has_color red',
           'Count how many beaf has_taste meaty',
           'Count how many beaf not has_color red',
           'Count how many beaf not has_taste meaty',
           'Count how many bread has_shape long',
           'Count how many bread has_taste tangy',
           'Count how many bread not has_shape long',
           'Count how many bread not has_taste tangy',
           'Count how many broccoli has_color green',
           'Count how many broccoli has_taste juicy',
           'Count how many broccoli has_taste sweet',
           'Count how many broccoli not has_color green',
           'Count how many broccoli not has_taste juicy',
           'Count how many broccoli not has_taste sweet',
           'Count how many cabbage has_taste sweet',
           'Count how many cabbage not has_taste sweet',
           'Count how many capsicum has_color green',
           'Count how many capsicum has_color red',
           'Count how many capsicum has_color yellow',
           'Count how many capsicum has_taste spicy',
           'Count how many capsicum original_from america',
           'Count how many capsicum not has_color green',
           'Count how many capsicum not has_color red',
           'Count how many capsicum not has_color yellow',
           'Count how many capsicum not has_taste spicy',
           'Count how many capsicum not original_from america',
           'Count how many carrot has_color yellow',
           'Count how many carrot has_shape long',
           'Count how many carrot has_taste woody',
           'Count how many carrot not has_color yellow',
           'Count how many carrot not has_shape long',
           'Count how many carrot not has_taste woody',
           'Count how many cheese has_nutrition fat',
           'Count how many cheese has_nutrition protein',
           'Count how many cheese not has_nutrition fat',
           'Count how many cheese not has_nutrition protein',
           'Count how many chicken has_color white',
           'Count how many chicken has_taste meaty',
           'Count how many chicken not has_color white',
           'Count how many chicken not has_taste meaty',
           'Count how many chilli has_color green',
           'Count how many chilli has_color red',
           'Count how many chilli has_color yellow',
           'Count how many chilli has_taste spicy',
           'Count how many chilli original_from america',
           'Count how many chilli not has_color green',
           'Count how many chilli not has_color red',
           'Count how many chilli not has_color yellow',
           'Count how many chilli not has_taste spicy',
           'Count how many chilli not original_from america',
           'Count how many corn has_color yellow',
           'Count how many corn original_from america',
           'Count how many corn not has_color yellow',
           'Count how many corn not original_from america',
           'Count how many cucumber has_color green',
           'Count how many cucumber has_shape long',
           'Count how many cucumber has_taste juicy',
           'Count how many cucumber original_from india',
           'Count how many cucumber not has_color green',
           'Count how many cucumber not has_shape long',
           'Count how many cucumber not has_taste juicy',
           'Count how many cucumber not original_from india',
           'Count how many egg has_nutrition protein',
           'Count how many egg not has_nutrition protein',
           'Count how many eggplant has_color purple',
           'Count how many eggplant has_shape long',
           'Count how many eggplant has_taste sweet',
           'Count how many eggplant not has_color purple',
           'Count how many eggplant not has_shape long',
           'Count how many eggplant not has_taste sweet',
           'Count how many fillet has_nutrition fat',
           'Count how many fillet has_nutrition protein',
           'Count how many fillet has_taste fishy',
           'Count how many fillet not has_nutrition fat',
           'Count how many fillet not has_nutrition protein',
           'Count how many fillet not has_taste fishy',
           'Count how many garlic has_color white',
           'Count how many garlic has_taste pungent',
           'Count how many garlic original_from asia',
           'Count how many garlic not has_color white',
           'Count how many garlic not has_taste pungent',
           'Count how many garlic not original_from asia',
           'Count how many green_apple has_color green',
           'Count how many green_apple has_taste sweet',
           'Count how many green_apple original_from america',
           'Count how many green_apple not has_color green',
           'Count how many green_apple not has_taste sweet',
           'Count how many green_apple not original_from america',
           'Count how many kiwifruit has_color green',
           'Count how many kiwifruit has_shape round',
           'Count how many kiwifruit original_from new_zealand',
           'Count how many kiwifruit not has_color green',
           'Count how many kiwifruit not has_shape round',
           'Count how many kiwifruit not original_from new_zealand',
           'Count how many lamb has_color red',
           'Count how many lamb has_taste meaty',
           'Count how many lamb not has_color red',
           'Count how many lamb not has_taste meaty',
           'Count how many lemon has_color yellow',
           'Count how many lemon has_taste juicy',
           'Count how many lemon has_taste sour',
           'Count how many lemon has_taste sweet',
           'Count how many lemon original_from china',
           'Count how many lemon not has_color yellow',
           'Count how many lemon not has_taste juicy',
           'Count how many lemon not has_taste sour',
           'Count how many lemon not has_taste sweet',
           'Count how many lemon not original_from china',
           'Count how many lettuce has_color green',
           'Count how many lettuce has_shape round',
           'Count how many lettuce original_from egypt',
           'Count how many lettuce not has_color green',
           'Count how many lettuce not has_shape round',
           'Count how many lettuce not original_from egypt',
           'Count how many lime has_color green',
           'Count how many lime has_taste juicy',
           'Count how many lime has_taste sour',
           'Count how many lime has_taste sweet',
           'Count how many lime original_from china',
           'Count how many lime not has_color green',
           'Count how many lime not has_taste juicy',
           'Count how many lime not has_taste sour',
           'Count how many lime not has_taste sweet',
           'Count how many lime not original_from china',
           'Count how many milk has_nutrition fat',
           'Count how many milk has_nutrition protein',
           'Count how many milk has_taste sweet',
           'Count how many milk not has_nutrition fat',
           'Count how many milk not has_nutrition protein',
           'Count how many milk not has_taste sweet',
           'Count how many mushroom has_color white',
           'Count how many mushroom not has_color white',
           'Count how many noodle has_shape long',

In [54]:
ent_not_df

,e1_classes,e1_entity,r1_relation,e2_classes,e2_entity,r2_relation,e3_classes,e3_entity,not
0,"[Vegetable, Food, Thing]",tomato,original_from,"[Country, Thing]",america,,,,
0,"[Vegetable, Food, Thing]",tomato,original_from,"[Country, Thing]",america,,,,not
1,"[Vegetable, Food, Thing]",tomato,has_shape,"[Shape, Thing]",round,,,,
1,"[Vegetable, Food, Thing]",tomato,has_shape,"[Shape, Thing]",round,,,,not
2,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",juicy,,,,
2,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",juicy,,,,not
3,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",sweet,,,,
3,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",sweet,,,,not
4,"[Vegetable, Food, Thing]",tomato,has_color,"[Color, Thing]",red,,,,
4,"[Vegetable, Food, Thing]",tomato,has_color,"[Color, Thing]",red,,,,not
5,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",juicy,,,,
5,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",juicy,,,,not
6,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",sweet,,,,
6,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",sweet,,,,not
7,"[Vegetable, Food, Thing]",broccoli,has_color,"[Color, Thing]",green,,,,
7,"[Vegetable, Food, Thing]",broccoli,has_color,"[Color, Thing]",green,,,,not
8,"[Vegetable, Food, Thing]",chilli,original_from,"[Country, Thing]",america,,,,
8,"[Vegetable, Food, Thing]",chilli,original_from,"[Country, Thing]",america,,,,not
9,"[Vegetable, Food, Thing]",chilli,has_taste,"[Taste, Thing]",spicy,,,,
9,"[Vegetable, Food, Thing]",chilli,has_taste,"[Taste, Thing]",spicy,,,,not
10,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",green,,,,
10,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",green,,,,not
11,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",red,,,,
11,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",red,,,,not
12,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",yellow,,,,
12,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",yellow,,,,not
13,"[Vegetable, Food, Thing]",carrot,has_shape,"[Shape, Thing]",long,,,,
13,"[Vegetable, Food, Thing]",carrot,has_shape,"[Shape, Thing]",long,,,,not
14,"[Vegetable, Food, Thing]",carrot,has_taste,"[Taste, Thing]",woody,,,,
14,"[Vegetable, Food, Thing]",carrot,has_taste,"[Taste, Thing]",woody,,,,not
15,"[Vegetable, Food, Thing]",carrot,has_color,"[Color, Thing]",yellow,,,,
15,"[Vegetable, Food, Thing]",carrot,has_color,"[Color, Thing]",yellow,,,,not
16,"[Vegetable, Food, Thing]",capsicum,original_from,"[Country, Thing]",america,,,,
16,"[Vegetable, Food, Thing]",capsicum,original_from,"[Country, Thing]",america,,,,not
17,"[Vegetable, Food, Thing]",capsicum,has_taste,"[Taste, Thing]",spicy,,,,
17,"[Vegetable, Food, Thing]",capsicum,has_taste,"[Taste, Thing]",spicy,,,,not
18,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",green,,,,
18,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",green,,,,not
19,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",red,,,,
19,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",red,,,,not
20,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",yellow,,,,
20,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",yellow,,,,not
21,"[Vegetable, Food, Thing]",cucumber,original_from,"[Country, Thing]",india,,,,
21,"[Vegetable, Food, Thing]",cucumber,original_from,"[Country, Thing]",india,,,,not
22,"[Vegetable, Food, Thing]",cucumber,has_shape,"[Shape, Thing]",long,,,,
22,"[Vegetable, Food, Thing]",cucumber,has_shape,"[Shape, Thing]",long,,,,not
23,"[Vegetable, Food, Thing]",cucumber,has_taste,"[Taste, Thing]",juicy,,,,
23,"[Vegetable, Food, Thing]",cucumber,has_taste,"[Taste, Thing]",juicy,,,,not
24,"[Vegetable, Food, Thing]",cucumber,has_color,"[Color, Thing]",green,,,,
24,"[Vegetable, Food, Thing]",cucumber,has_color,"[Color, Thing]",green,,,,not
25,"[Vegetable, Food, Thing]",cabbage,has_taste,"[Taste, Thing]",sweet,,,,
25,"[Vegetable, Food, Thing]",cabbage,has_taste,"[Taste, Thing]",sweet,,,,not
26,"[Vegetable, Food, Thing]",garlic,original_from,"[Country, Thing]",asia,,,,
26,"[Vegetable, Food, Thing]",garlic,original_from,"[Country, Thing]",asia,,,,not
27,"[Vegetable, Food, Thing]",garlic,has_taste,"[Taste, Thing]",pungent,,,,
27,"[Vegetable, Food, Thing]",garlic,has_taste,"[Taste, Thing]",pungent,,,,not
28,"[Vegetable, Food, Thing]",garlic,has_color,"[Color, Thing]",white,,,,
28,"[Vegetable, Food, Thing]",garlic,has_color,"[Color, Thing]",white,,,,not
29,"[Vegetable, Food, Thing]",lettuce,original_from,"[Country, Thing]",egypt,,,,
29,"[Vegetable, Food, Thing]",lettuce,original_from,"[Country, Thing]",egypt,,,,not
30,"[Vegetable, Food, Thing]",lettuce,has_shape,"[Shape, Thing]",round,,,,
30,"[Vegetable, Food, Thing]",lettuce,has_shape,"[Shape, Thing]",round,,,,not
31,"[Vegetable, Food, Thing]",lettuce,has_color,"[Color, Thing]",green,,,,
31,"[Vegetable, Food, Thing]",lettuce,has_color,"[Color, Thing]",green,,,,not
32,"[Vegetable, Food, Thing]",mushroom,has_color,"[Color, Thing]",white,,,,
32,"[Vegetable, Food, Thing]",mushroom,has_color,"[Color, Thing]",white,,,,not
33,"[Vegetable, Food, Thing]",onion,original_from,"[Country, Thing]",australia,,,,
33,"[Vegetable, Food, Thing]",onion,original_from,"[Country, Thing]",australia,,,,not
34,"[Vegetable, Food, Thing]",onion,original_from,"[Country, Thing]",new_zealand,,,,
34,"[Vegetable, Food, Thing]",onion,original_from,"[Country, Thing]",new_zealand,,,,not
35,"[Vegetable, Food, Thing]",onion,has_shape,"[Shape, Thing]",round,,,,
35,"[Vegetable, Food, Thing]",onion,has_shape,"[Shape, Thing]",round,,,,not
36,"[Vegetable, Food, Thing]",onion,has_taste,"[Taste, Thing]",pungent,,,,
36,"[Vegetable, Food, Thing]",onion,has_taste,"[Taste, Thing]",pungent,,,,not
37,"[Vegetable, Food, Thing]",onion,has_color,"[Color, Thing]",yellow,,,,
37,"[Vegetable, Food, Thing]",onion,has_color,"[Color, Thing]",yellow,,,,not
38,"[Vegetable, Food, Thing]",onion,has_color,"[Color, Thing]",purple,,,,
38,"[Vegetable, Food, Thing]",onion,has_color,"[Color, Thing]",purple,,,,not
39,"[Vegetable, Food, Thing]",potato,original_from,"[Country, Thing]",america,,,,
39,"[Vegetable, Food, Thing]",potato,original_from,"[Country, Thing]",america,,,,not
40,"[Vegetable, Food, Thing]",potato,has_taste,"[Taste, Thing]",sweet,,,,
40,"[Vegetable, Food, Thing]",potato,has_taste,"[Taste, Thing]",sweet,,,,not
41,"[Vegetable, Food, Thing]",pumpkin,original_from,"[Country, Thing]",mexica,,,,
41,"[Vegetable, Food, Thing]",pumpkin,original_from,"[Country, Thing]",mexica,,,,not
42,"[Vegetable, Food, Thing]",pumpkin,has_taste,"[Taste, Thing]",sweet,,,,
42,"[Vegetable, Food, Thing]",pumpkin,has_taste,"[Taste, Thing]",sweet,,,,not
43,"[Vegetable, Food, Thing]",pumpkin,has_color,"[Color, Thing]",yellow,,,,
43,"[Vegetable, Food, Thing]",pumpkin,has_color,"[Color, Thing]",yellow,,,,not
44,"[Vegetable, Food, Thing]",eggplant,has_shape,"[Shape, Thing]",long,,,,
44,"[Vegetable, Food, Thing]",eggplant,has_shape,"[Shape, Thing]",long,,,,not
45,"[Vegetable, Food, Thing]",eggplant,has_taste,"[Taste, Thing]",sweet,,,,
45,"[Vegetable, Food, Thing]",eggplant,has_taste,"[Taste, Thing]",sweet,,,,not
46,"[Vegetable, Food, Thing]",eggplant,has_color,"[Color, Thing]",purple,,,,
46,"[Vegetable, Food, Thing]",eggplant,has_color,"[Color, Thing]",purple,,,,not
47,"[Vegetable, Food, Thing]",pepper,has_taste,"[Taste, Thing]",spicy,,,,
47,"[Vegetable, Food, Thing]",pepper,has_taste,"[Taste, Thing]",spicy,,,,not
48,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",green,,,,
48,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",green,,,,not
49,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",red,,,,
49,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",red,,,,not
50,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",yellow,,,,
50,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",yellow,,,,not
51,"[Fruit, Food, Thing]",orange,has_color,"[Color, Thing]",yellow,,,,
51,"[Fruit, Food, Thing]",orange,has_color,"[Color, Thing]",yellow,,,,not
52,"[Fruit, Food, Thing]",apple,original_from,"[Country, Thing]",america,,,,
52,"[Fruit, Food, Thing]",apple,original_from,"[Country, Thing]",america,,,,not
53,"[Fruit, Food, Thing]",apple,has_color,"[Color, Thing]",green,,,,
53,"[Fruit, Food, Thing]",apple,has_color,"[Color, Thing]",green,,,,not
54,"[Fruit, Food, Thing]",apple,has_color,"[Color, Thing]",red,,,,
54,"[Fruit, Food, Thing]",apple,has_color,"[Color, Thing]",red,,,,not
55,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,original_from,"[Country, Thing]",america,
55,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,original_from,"[Country, Thing]",america,not
56,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,has_taste,"[Taste, Thing]",sweet,
56,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,has_taste,"[Taste, Thing]",sweet,not
57,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,has_color,"[Color, Thing]",green,
57,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,has_color,"[Color, Thing]",green,not
58,"[Fruit, Food, Thing]",banana,has_shape,"[Shape, Thing]",long,,,,
58,"[Fruit, Food, Thing]",banana,has_shape,"[Shape, Thing]",long,,,,not
59,"[Fruit, Food, Thing]",banana,has_color,"[Color, Thing]",yellow,,,,
59,"[Fruit, Food, Thing]",banana,has_color,"[Color, Thing]",yellow,,,,not
60,"[Fruit, Food, Thing]",lemon,original_from,"[Country, Thing]",china,,,,
60,"[Fruit, Food, Thing]",lemon,original_from,"[Country, Thing]",china,,,,not
61,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",sweet,,,,
61,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",sweet,,,,not
62,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",sour,,,,
62,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",sour,,,,not
63,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",juicy,,,,
63,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",juicy,,,,not
64,"[Fruit, Food, Thing]",lemon,has_color,"[Color, Thing]",yellow,,,,
64,"[Fruit, Food, Thing]",lemon,has_color,"[Color, Thing]",yellow,,,,not
65,"[Fruit, Food, Thing]",plum,original_from,"[Country, Thing]",china,,,,
65,"[Fruit, Food, Thing]",plum,original_from,"[Country, Thing]",china,,,,not
66,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",sweet,,,,
66,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",sweet,,,,not
67,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",sour,,,,
67,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",sour,,,,not
68,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",juicy,,,,
68,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",juicy,,,,not
69,"[Fruit, Food, Thing]",plum,has_color,"[Color, Thing]",purple,,,,
69,"[Fruit, Food, Thing]",plum,has_color,"[Color, Thing]",purple,,,,not
70,"[Fruit, Food, Thing]",lime,original_from,"[Country, Thing]",china,,,,
70,"[Fruit, Food, Thing]",lime,original_from,"[Country, Thing]",china,,,,not
71,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",sweet,,,,
71,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",sweet,,,,not
72,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",sour,,,,
72,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",sour,,,,not
73,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",juicy,,,,
73,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",juicy,,,,not
74,"[Fruit, Food, Thing]",lime,has_color,"[Color, Thing]",green,,,,
74,"[Fruit, Food, Thing]",lime,has_color,"[Color, Thing]",green,,,,not
75,"[Fruit, Food, Thing]",kiwifruit,original_from,"[Country, Thing]",new_zealand,,,,
75,"[Fruit, Food, Thing]",kiwifruit,original_from,"[Country, Thing]",new_zealand,,,,not
76,"[Fruit, Food, Thing]",kiwifruit,has_shape,"[Shape, Thing]",round,,,,
76,"[Fruit, Food, Thing]",kiwifruit,has_shape,"[Shape, Thing]",round,,,,not
77,"[Fruit, Food, Thing]",kiwifruit,has_color,"[Color, Thing]",green,,,,
77,"[Fruit, Food, Thing]",kiwifruit,has_color,"[Color, Thing]",green,,,,not
78,"[Fruit, Food, Thing]",avocado,original_from,"[Country, Thing]",america,,,,
78,"[Fruit, Food, Thing]",avocado,original_from,"[Country, Thing]",america,,,,not
79,"[Fruit, Food, Thing]",avocado,has_shape,"[Shape, Thing]",round,,,,
79,"[Fruit, Food, Thing]",avocado,has_shape,"[Shape, Thing]",round,,,,not
80,"[Fruit, Food, Thing]",avocado,has_taste,"[Taste, Thing]",grassy,,,,
80,"[Fruit, Food, Thing]",avocado,has_taste,"[Taste, Thing]",grassy,,,,not
81,"[Fruit, Food, Thing]",avocado,has_color,"[Color, Thing]",green,,,,
81,"[Fruit, Food, Thing]",avocado,has_color,"[Color, Thing]",green,,,,not
82,"[Fruit, Food, Thing]",pear,has_shape,"[Shape, Thing]",round,,,,
82,"[Fruit, Food, Thing]",pear,has_shape,"[Shape, Thing]",round,,,,not
83,"[Fruit, Food, Thing]",pear,has_taste,"[Taste, Thing]",juicy,,,,
83,"[Fruit, Food, Thing]",pear,has_taste,"[Taste, Thing]",juicy,,,,not
84,"[Fruit, Food, Thing]",pear,has_taste,"[Taste, Thing]",sweet,,,,
84,"[Fruit, Food, Thing]",pear,has_taste,"[Taste, Thing]",sweet,,,,not
85,"[Fruit, Food, Thing]",pear,has_color,"[Color, Thing]",green,,,,
85,"[Fruit, Food, Thing]",pear,has_color,"[Color, Thing]",green,,,,not
86,"[Fruit, Food, Thing]",pear,has_color,"[Color, Thing]",yellow,,,,
86,"[Fruit, Food, Thing]",pear,has_color,"[Color, Thing]",yellow,,,,not
87,"[Fruit, Food, Thing]",green_apple,original_from,"[Country, Thing]",america,,,,
87,"[Fruit, Food, Thing]",green_apple,original_from,"[Country, Thing]",america,,,,not
88,"[Fruit, Food, Thing]",green_apple,has_taste,"[Taste, Thing]",sweet,,,,
88,"[Fruit, Food, Thing]",green_apple,has_taste,"[Taste, Thing]",sweet,,,,not
89,"[Fruit, Food, Thing]",green_apple,has_color,"[Color, Thing]",green,,,,
89,"[Fruit, Food, Thing]",green_apple,has_color,"[Color, Thing]",green,,,,not
90,"[Fruit, Food, Thing]",red_apple,original_from,"[Country, Thing]",america,,,,
90,"[Fruit, Food, Thing]",red_apple,original_from,"[Country, Thing]",america,,,,not
91,"[Fruit, Food, Thing]",red_apple,has_taste,"[Taste, Thing]",sweet,,,,
91,"[Fruit, Food, Thing]",red_apple,has_taste,"[Taste, Thing]",sweet,,,,not
92,"[Fruit, Food, Thing]",red_apple,has_color,"[Color, Thing]",red,,,,
92,"[Fruit, Food, Thing]",red_apple,has_color,"[Color, Thing]",red,,,,not
93,"[Meat, Food, Thing]",beaf,has_taste,"[Taste, Thing]",meaty,,,,
93,"[Meat, Food, Thing]",beaf,has_taste,"[Taste, Thing]",meaty,,,,not
94,"[Meat, Food, Thing]",beaf,has_color,"[Color, Thing]",red,,,,
94,"[Meat, Food, Thing]",beaf,has_color,"[Color, Thing]",red,,,,not
95,"[Meat, Food, Thing]",chicken,has_taste,"[Taste, Thing]",meaty,,,,
95,"[Meat, Food, Thing]",chicken,has_taste,"[Taste, Thing]",meaty,,,,not
96,"[Meat, Food, Thing]",chicken,has_color,"[Color, Thing]",white,,,,
96,"[Meat, Food, Thing]",chicken,has_color,"[Color, Thing]",white,,,,not
97,"[Meat, Food, Thing]",lamb,has_taste,"[Taste, Thing]",meaty,,,,
97,"[Meat, Food, Thing]",lamb,has_taste,"[Taste, Thing]",meaty,,,,not
98,"[Meat, Food, Thing]",lamb,has_color,"[Color, Thing]",red,,,,
98,"[Meat, Food, Thing]",lamb,has_color,"[Color, Thing]",red,,,,not
99,"[Meat, Food, Thing]",pork,has_taste,"[Taste, Thing]",meaty,,,,
99,"[Meat, Food, Thing]",pork,has_taste,"[Taste, Thing]",meaty,,,,not
100,"[Meat, Food, Thing]",pork,has_color,"[Color, Thing]",red,,,,
100,"[Meat, Food, Thing]",pork,has_color,"[Color, Thing]",red,,,,not
101,"[Fish, Food, Thing]",salmon,has_nutrition,"[Nutrition, Thing]",fat,,,,
101,"[Fish, Food, Thing]",salmon,has_nutrition,"[Nutrition, Thing]",fat,,,,not
102,"[Fish, Food, Thing]",salmon,has_nutrition,"[Nutrition, Thing]",protein,,,,
102,"[Fish, Food, Thing]",salmon,has_nutrition,"[Nutrition, Thing]",protein,,,,not
103,"[Fish, Food, Thing]",salmon,has_taste,"[Taste, Thing]",fishy,,,,
103,"[Fish, Food, Thing]",salmon,has_taste,"[Taste, Thing]",fishy,,,,not
104,"[Fish, Food, Thing]",shrimp,has_nutrition,"[Nutrition, Thing]",protein,,,,
104,"[Fish, Food, Thing]",shrimp,has_nutrition,"[Nutrition, Thing]",protein,,,,not
105,"[Fish, Food, Thing]",shrimp,has_taste,"[Taste, Thing]",fishy,,,,
105,"[Fish, Food, Thing]",shrimp,has_taste,"[Taste, Thing]",fishy,,,,not
106,"[Fish, Food, Thing]",squid,has_nutrition,"[Nutrition, Thing]",protein,,,,
106,"[Fish, Food, Thing]",squid,has_nutrition,"[Nutrition, Thing]",protein,,,,not
107,"[Fish, Food, Thing]",squid,has_taste,"[Taste, Thing]",fishy,,,,
107,"[Fish, Food, Thing]",squid,has_taste,"[Taste, Thing]",fishy,,,,not
108,"[Fish, Food, Thing]",fillet,has_nutrition,"[Nutrition, Thing]",fat,,,,
108,"[Fish, Food, Thing]",fillet,has_nutrition,"[Nutrition, Thing]",fat,,,,not
109,"[Fish, Food, Thing]",fillet,has_nutrition,"[Nutrition, Thing]",protein,,,,
109,"[Fish, Food, Thing]",fillet,has_nutrition,"[Nutrition, Thing]",protein,,,,not
110,"[Fish, Food, Thing]",fillet,has_taste,"[Taste, Thing]",fishy,,,,
110,"[Fish, Food, Thing]",fillet,has_taste,"[Taste, Thing]",fishy,,,,not
111,"[Dairy, Food, Thing]",egg,has_nutrition,"[Nutrition, Thing]",protein,,,,
111,"[Dairy, Food, Thing]",egg,has_nutrition,"[Nutrition, Thing]",protein,,,,not
112,"[Dairy, Food, Thing]",yoghurt,has_nutrition,"[Nutrition, Thing]",protein,,,,
112,"[Dairy, Food, Thing]",yoghurt,has_nutrition,"[Nutrition, Thing]",protein,,,,not
113,"[Dairy, Food, Thing]",yoghurt,has_taste,"[Taste, Thing]",sweet,,,,
113,"[Dairy, Food, Thing]",yoghurt,has_taste,"[Taste, Thing]",sweet,,,,not
114,"[Dairy, Food, Thing]",cheese,has_nutrition,"[Nutrition, Thing]",protein,,,,
114,"[Dairy, Food, Thing]",cheese,has_nutrition,"[Nutrition, Thing]",protein,,,,not
115,"[Dairy, Food, Thing]",cheese,has_nutrition,"[Nutrition, Thing]",fat,,,,
115,"[Dairy, Food, Thing]",cheese,has_nutrition,"[Nutrition, Thing]",fat,,,,not
116,"[Dairy, Food, Thing]",milk,has_nutrition,"[Nutrition, Thing]",protein,,,,
116,"[Dairy, Food, Thing]",milk,has_nutrition,"[Nutrition, Thing]",protein,,,,not
117,"[Dairy, Food, Thing]",milk,has_nutrition,"[Nutrition, Thing]",fat,,,,
117,"[Dairy, Food, Thing]",milk,has_nutrition,"[Nutrition, Thing]",fat,,,,not
118,"[Dairy, Food, Thing]",milk,has_taste,"[Taste, Thing]",sweet,,,,
118,"[Dairy, Food, Thing]",milk,has_taste,"[Taste, Thing]",sweet,,,,not
119,"[Grain, Food, Thing]",rice,has_shape,"[Shape, Thing]",round,,,,
119,"[Grain, Food, Thing]",rice,has_shape,"[Shape, Thing]",round,,,,not
120,"[Grain, Food, Thing]",rice,has_shape,"[Shape, Thing]",long,,,,
120,"[Grain, Food, Thing]",rice,has_shape,"[Shape, Thing]",long,,,,not
121,"[Grain, Food, Thing]",noodle,has_shape,"[Shape, Thing]",long,,,,
121,"[Grain, Food, Thing]",noodle,has_shape,"[Shape, Thing]",long,,,,not
122,"[Grain, Food, Thing]",pasta,has_shape,"[Shape, Thing]",round,,,,
122,"[Grain, Food, Thing]",pasta,has_shape,"[Shape, Thing]",round,,,,not
123,"[Grain, Food, Thing]",pasta,has_shape,"[Shape, Thing]",long,,,,
123,"[Grain, Food, Thing]",pasta,has_shape,"[Shape, Thing]",long,,,,not
124,"[Grain, Food, Thing]",bread,has_shape,"[Shape, Thing]",long,,,,
124,"[Grain, Food, Thing]",bread,has_shape,"[Shape, Thing]",long,,,,not
125,"[Grain, Food, Thing]",bread,has_taste,"[Taste, Thing]",tangy,,,,
125,"[Grain, Food, Thing]",bread,has_taste,"[Taste, Thing]",tangy,,,,not
126,"[Grain, Food, Thing]",corn,original_from,"[Country, Thing]",america,,,,
126,"[Grain, Food, Thing]",corn,original_from,"[Country, Thing]",america,,,,not
127,"[Grain, Food, Thing]",corn,has_color,"[Color, Thing]",yellow,,,,
127,"[Grain, Food, Thing]",corn,has_color,"[Color, Thing]",yellow,,,,not

In [24]:
# Copy the index into a list, then generate the answers which match the questions. 
# This is the final correct answer. 
# This is for generate the answers which match the questions. 


my_list = [324, 300, 306, 327, 303, 309, 246, 252, 240, 249, 255, 243, 97, 25, 19, 205, 79, 247, 253, 355, 349, 241, 31, 7, 199, 145, 61, 13, 379, 91, 1, 133, 55, 43, 100, 28, 22, 208, 82, 250, 256, 358, 352, 244, 34, 10, 202, 148, 64, 16, 382, 94, 4, 136, 58, 46, 96, 114, 120, 84, 150, 144, 138, 90, 132, 99, 117, 123, 87, 153, 147, 141, 93, 135, 354, 348, 378, 357, 351, 381, 192, 204, 198, 195, 207, 201, 98, 26, 20, 206, 80, 248, 254, 356, 350, 242, 32, 8, 200, 146, 62, 14, 380, 92, 2, 134, 56, 44, 101, 29, 23, 209, 83, 251, 257, 359, 353, 245, 35, 11, 203, 149, 65, 17, 383, 95, 5, 137, 59, 47, 24, 18, 78, 30, 6, 60, 12, 0, 54, 42, 27, 21, 81, 33, 9, 63, 15, 3, 57, 45]

my_set = set(my_list)

count = 0

# for idx, row in cls_not_df.iterrows():

random_qu = np.random.choice(incl_not_questions, 100)
print(random_qu)
# for idx, row in enumerate(incl_not_questions):
# #     if count in my_set:
# #         print(row)
# #     print(count)
# #     print(str(cls_not_df.iloc[[my_list[idx]][0]]))
#     print(row)
#     print(str(cls_not_df.iloc[[my_list[idx]][0]]['e1_entity']))
# #     if idx >= 5:
# #         print(f"{row[5]} {row[10]} {row[15]}")
# #         print(f"{e1_entity_x} {combine_x} {e2_entity_y}")
# #         break
#     count += 1
# # print(lde.index[:5])

['Count how many Vegetable not has_taste spicy'
 'Count how many capsicum not original_from america'
 'Count how many green_apple not has_color green'
 'Count how many Fruit not has_color green'
 'Count how many tomato not has_shape round'
 'Count how many pork not has_taste meaty'
 'Count how many rice not has_shape round'
 'Count how many green_apple not has_taste sweet'
 'Count how many salmon has_taste fishy'
 'Count how many yoghurt has_nutrition protein']

In [ ]:
print(len(cls_not_df))
print(len(incl_not_questions))

In [ ]:
sorted(cls_not_df.columns)

In [ ]:
# Time for logic - Step 2 -Table with "and, or" 
# Key goal here is to add a column which has either "and" "or". 
cls_idx_not_df = not_df.explode('e1_classes').reset_index(drop=True).reset_index()
cls_idx_not_df['combine'] = [['and', 'or'] for i in cls_idx_not_df.index]
print('OK-Table2: cls_idx_not_df is the table with "not", "and", "or"')

cls_idx_not_df[0:10]

In [ ]:
# Time for logic - step3 - Table: logic_df and lde - Merge two tables! 
# Table logic_df: Merge two same tables: cls_idx_not_df together
# logic_df table adding a rule: index_x != index_y, and e1_classes != Thing. 
# Table lde is the logic_df's explode 

logic_df=(
    pd.merge(cls_idx_not_df, cls_idx_not_df, on=['e1_classes'])
    .query("index_x!=index_y and e1_classes!='Thing'")
)
logic_df
logic_df_explode = logic_df.explode('not_x').explode('combine_x')
lde = logic_df_explode

print('OK-Table3: lde, merge two tables "cls_idx_not_df", with not, and, or and explode')
# lde
lde[0:100]

In [ ]:
pprint(len(cls_idx_not_df))
pprint(len(logic_df))
pprint(lde.shape)

In [ ]:
pprint(lde[10:300])

In [ ]:
# Time for Logic - Step 4 - Generate logic_2 questions

logic_2_questions = 'What ' + unique_concat(
    lde.e1_classes.str.cat(sep=' ', others=[lde['not_x'], lde.r1_relation_x, lde.e2_entity_x, lde['combine_x'], 
                                            lde.r1_relation_y, lde.e2_entity_y]),
)
pprint(f'{len(logic_2_questions)} logic_2 questions in total')
# pprint(logic_2_questions.tolist()[:10])
pprint(logic_2_questions.tolist())
logic_2 = pd.DataFrame(logic_2_questions)
logic_2.to_csv('./logic_2_questions.csv', index=True, header=True)

In [ ]:
# Table lde1 = e1_classes NOT Food for particular questions
lde1 = lde.copy()
lde1 = pd.DataFrame(lde1).query("e1_classes!='Food'")
print('OK-Table: lde1')
lde1[0:100]

In [ ]:
# %%timeit -n 1 
# Time for Logic - Step 5 - Generate extra logic_2 questions
# What food in the image are not vegetable but have protein fat or have taste juicy? 

question_template = lde1.e1_classes.str.cat(sep=' ', others=[
#      lde1['not_x'],
#      lde1.e1_classes,
#      # Add additional word into cat function. change it to .series. 
#      pd.Series(['and'] * len(lde1)).values,  
     lde1['not_x'],
     lde1.r1_relation_x,
     lde1.e2_entity_x,
     lde1['combine_x'],
     lde1.r1_relation_y,
     lde1.e2_entity_y
])

some_questions = unique_concat('What food in the image are ' + question_template)
some_questions[:10]

In [ ]:
# Time for Logic - Step 5.1 - Method2 - Generate extra logic_2 questions
# What food in the image are not vegetable but have protein fat or have taste juicy? 

some_questions = (
    ('What food ' + ' in the image are ' + lde['not_x'] + ' ' + lde1.e1_classes  + ' and ' + ' '+ lde['not_x'] + ' ' + lde.r1_relation_x + ' ' + lde.e2_entity_x + ' '
      + lde['combine_x'] + ' ' + lde.r1_relation_y + ' ' + lde.e2_entity_y).unique().tolist() ) 
some_questions[500:1000]
# logic_2_ext = pd.DataFrame(some_questions)
# logic_2_ext.to_csv('~/git_paper_1/vqa_integration/logic_2_ext_questions.csv', index=True, header=True)

In [ ]:
print('list lenth', len(some_questions))

In [ ]:
# Copy the index into a list, then generate the answers which match the questions. 

my_list = [18796, 18776, 18784, 18797, 18777, 18785, 18676, 18664, 18668, 18677, 18665, 18669, 18732, 18720, 18744, 18733, 18721, 18745, 18798, 18778, 18786, 18799, 18779, 18787, 18678, 18666, 18670, 18679, 18667, 18671, 18734, 18722, 18746, 18735, 18723, 18747, 18328, 18304, 18308, 18329, 18305, 18309, 18340, 18348, 18344, 18341, 18349, 18345, 18376, 18380, 18388, 18377, 18381, 18389, 18330, 18306, 18310, 18331, 18307, 18311, 18342, 18350, 18346, 18343, 18351, 18347, 18378, 18382, 18390, 18379, 18383, 18391, 5336, 5284, 5276, 5400, 5316, 5420, 5424, 5496, 5492, 5428, 5280, 5268, 5388, 5356, 5304, 5272, 5512, 5324, 5264, 5348, 5300, 5292, 5337, 5285, 5277, 5401, 5317, 5421, 5425, 5497, 5493, 5429, 5281, 5269, 5389, 5357, 5305, 5273, 5513, 5325, 5265, 5349, 5301, 5293, 2056, 2016, 2000, 2124, 2036, 2144, 2148, 2220, 2216, 2152, 2004, 1992, 2112, 2080, 2024, 1996, 2236, 2044, 1988, 2072, 2020, 2012, 2057, 2017, 2001, 2125, 2037, 2145, 2149, 2221, 2217, 2153, 2005, 1993, 2113, 2081, 2025, 1997, 2237, 2045, 1989, 2073, 2021, 2013, 1552, 1500, 1528, 1620, 1532, 1640, 1644, 1716, 1712, 1648, 1496, 1488, 1608, 1576, 1520, 1492, 1732, 1540, 1484, 1568, 1516, 1508, 1553, 1501, 1529, 1621, 1533, 1641, 1645, 1717, 1713, 1649, 1497, 1489, 1609, 1577, 1521, 1493, 1733, 1541, 1485, 1569, 1517, 1509, 9620, 9568, 9560, 9600, 9704, 9708, 9780, 9776, 9712, 9564, 9552, 9676, 9644, 9588, 9556, 9796, 9608, 9548, 9636, 9584, 9576, 9621, 9569, 9561, 9601, 9705, 9709, 9781, 9777, 9713, 9565, 9553, 9677, 9645, 9589, 9557, 9797, 9609, 9549, 9637, 9585, 9577, 4072, 4024, 4016, 4140, 4056, 4160, 4164, 4236, 4232, 4168, 4020, 4008, 4128, 4096, 4044, 4012, 4252, 4060, 4004, 4088, 4040, 4032, 4073, 4025, 4017, 4141, 4057, 4161, 4165, 4237, 4233, 4169, 4021, 4009, 4129, 4097, 4045, 4013, 4253, 4061, 4005, 4089, 4041, 4033, 10880, 10828, 10820, 10948, 10860, 10992, 10968, 11040, 11036, 10972, 10824, 10812, 10936, 10904, 10848, 10816, 11056, 10868, 10808, 10896, 10844, 10836, 10881, 10829, 10821, 10949, 10861, 10993, 10969, 11041, 11037, 10973, 10825, 10813, 10937, 10905, 10849, 10817, 11057, 10869, 10809, 10897, 10845, 10837, 11132, 11080, 11072, 11200, 11112, 11220, 11228, 11292, 11288, 11224, 11076, 11064, 11188, 11156, 11100, 11068, 11308, 11120, 11060, 11148, 11096, 11088, 11133, 11081, 11073, 11201, 11113, 11221, 11229, 11293, 11289, 11225, 11077, 11065, 11189, 11157, 11101, 11069, 11309, 11121, 11061, 11149, 11097, 11089, 15668, 15616, 15608, 15736, 15648, 15756, 15760, 15832, 15828, 15764, 15612, 15600, 15724, 15692, 15636, 15604, 15844, 15656, 15596, 15684, 15632, 15624, 15669, 15617, 15609, 15737, 15649, 15757, 15761, 15833, 15829, 15765, 15613, 15601, 15725, 15693, 15637, 15605, 15845, 15657, 15597, 15685, 15633, 15625, 15416, 15364, 15356, 15484, 15396, 15504, 15508, 15576, 15584, 15512, 15360, 15348, 15472, 15440, 15384, 15352, 15592, 15404, 15344, 15432, 15380, 15372, 15417, 15365, 15357, 15485, 15397, 15505, 15509, 15577, 15585, 15513, 15361, 15349, 15473, 15441, 15385, 15353, 15593, 15405, 15345, 15433, 15381, 15373, 11384, 11332, 11324, 11452, 11364, 11472, 11476, 11544, 11540, 11484, 11328, 11316, 11440, 11408, 11352, 11320, 11560, 11372, 11312, 11400, 11348, 11340, 11385, 11333, 11325, 11453, 11365, 11473, 11477, 11545, 11541, 11485, 11329, 11317, 11441, 11409, 11353, 11321, 11561, 11373, 11313, 11401, 11349, 11341, 1804, 1752, 1748, 1872, 1784, 1892, 1896, 1968, 1964, 1900, 1740, 1860, 1828, 1772, 1744, 1984, 1792, 1736, 1820, 1768, 1760, 1805, 1753, 1749, 1873, 1785, 1893, 1897, 1969, 1965, 1901, 1741, 1861, 1829, 1773, 1745, 1985, 1793, 1737, 1821, 1769, 1761, 1048, 996, 988, 1116, 1028, 1136, 1140, 1212, 1208, 1144, 992, 1076, 1104, 1072, 1016, 984, 1228, 1036, 980, 1064, 1012, 1004, 1049, 997, 989, 1117, 1029, 1137, 1141, 1213, 1209, 1145, 993, 1077, 1105, 1073, 1017, 985, 1229, 1037, 981, 1065, 1013, 1005, 8864, 8812, 8804, 8928, 8844, 8948, 8952, 9024, 9020, 8956, 8808, 8796, 8924, 8888, 8832, 8800, 9040, 8852, 8792, 8880, 8828, 8820, 8865, 8813, 8805, 8929, 8845, 8949, 8953, 9025, 9021, 8957, 8809, 8797, 8925, 8889, 8833, 8801, 9041, 8853, 8793, 8881, 8829, 8821, 6848, 6796, 6788, 6912, 6828, 6932, 6936, 7008, 7004, 6940, 6792, 6780, 6900, 6816, 6784, 7024, 6836, 6776, 6864, 6812, 6804, 6849, 6797, 6789, 6913, 6829, 6933, 6937, 7009, 7005, 6941, 6793, 6781, 6901, 6817, 6785, 7025, 6837, 6777, 6865, 6813, 6805, 3316, 3268, 3260, 3384, 3296, 3404, 3408, 3480, 3476, 3412, 3264, 3252, 3372, 3340, 3256, 3496, 3304, 3248, 3332, 3284, 3276, 3317, 3269, 3261, 3385, 3297, 3405, 3409, 3481, 3477, 3413, 3265, 3253, 3373, 3341, 3257, 3497, 3305, 3249, 3333, 3285, 3277, 1300, 1248, 1240, 1368, 1280, 1388, 1392, 1464, 1460, 1396, 1244, 1236, 1356, 1324, 1268, 1320, 1480, 1288, 1232, 1316, 1264, 1256, 1301, 1249, 1241, 1369, 1281, 1389, 1393, 1465, 1461, 1397, 1245, 1237, 1357, 1325, 1269, 1321, 1481, 1289, 1233, 1317, 1265, 1257, 16676, 16624, 16616, 16744, 16656, 16764, 16768, 16840, 16836, 16772, 16620, 16608, 16732, 16700, 16644, 16612, 16664, 16604, 16692, 16640, 16632, 16677, 16625, 16617, 16745, 16657, 16765, 16769, 16841, 16837, 16773, 16621, 16609, 16733, 16701, 16645, 16613, 16665, 16605, 16693, 16641, 16633, 4576, 4528, 4520, 4644, 4560, 4664, 4668, 4740, 4736, 4672, 4524, 4512, 4632, 4600, 4548, 4516, 4756, 4608, 4508, 4592, 4544, 4536, 4577, 4529, 4521, 4645, 4561, 4665, 4669, 4741, 4737, 4673, 4525, 4513, 4633, 4601, 4549, 4517, 4757, 4609, 4509, 4593, 4545, 4537, 796, 744, 736, 864, 776, 884, 888, 960, 956, 892, 740, 728, 852, 820, 764, 732, 976, 784, 748, 812, 760, 752, 797, 745, 737, 865, 777, 885, 889, 961, 957, 893, 741, 729, 853, 821, 765, 733, 977, 785, 749, 813, 761, 753, 6344, 6292, 6284, 6408, 6324, 6428, 6432, 6504, 6500, 6436, 6288, 6276, 6396, 6364, 6312, 6280, 6520, 6332, 6272, 6308, 6300, 6345, 6293, 6285, 6409, 6325, 6429, 6433, 6505, 6501, 6437, 6289, 6277, 6397, 6365, 6313, 6281, 6521, 6333, 6273, 6309, 6301, 3064, 3016, 3008, 3132, 3044, 3152, 3156, 3228, 3224, 3160, 3012, 3000, 3120, 3088, 3032, 3004, 3244, 3052, 2996, 3080, 3024, 3065, 3017, 3009, 3133, 3045, 3153, 3157, 3229, 3225, 3161, 3013, 3001, 3121, 3089, 3033, 3005, 3245, 3053, 2997, 3081, 3025, 2560, 2512, 2504, 2628, 2540, 2648, 2652, 2724, 2720, 2656, 2508, 2496, 2616, 2584, 2528, 2500, 2740, 2548, 2492, 2576, 2524, 2561, 2513, 2505, 2629, 2541, 2649, 2653, 2725, 2721, 2657, 2509, 2497, 2617, 2585, 2529, 2501, 2741, 2549, 2493, 2577, 2525, 5338, 5286, 5278, 5402, 5318, 5422, 5426, 5498, 5494, 5430, 5282, 5270, 5390, 5358, 5306, 5274, 5514, 5326, 5266, 5350, 5302, 5294, 5339, 5287, 5279, 5403, 5319, 5423, 5427, 5499, 5495, 5431, 5283, 5271, 5391, 5359, 5307, 5275, 5515, 5327, 5267, 5351, 5303, 5295, 2058, 2018, 2002, 2126, 2038, 2146, 2150, 2222, 2218, 2154, 2006, 1994, 2114, 2082, 2026, 1998, 2238, 2046, 1990, 2074, 2022, 2014, 2059, 2019, 2003, 2127, 2039, 2147, 2151, 2223, 2219, 2155, 2007, 1995, 2115, 2083, 2027, 1999, 2239, 2047, 1991, 2075, 2023, 2015, 1554, 1502, 1530, 1622, 1534, 1642, 1646, 1718, 1714, 1650, 1498, 1490, 1610, 1578, 1522, 1494, 1734, 1542, 1486, 1570, 1518, 1510, 1555, 1503, 1531, 1623, 1535, 1643, 1647, 1719, 1715, 1651, 1499, 1491, 1611, 1579, 1523, 1495, 1735, 1543, 1487, 1571, 1519, 1511, 9622, 9570, 9562, 9602, 9706, 9710, 9782, 9778, 9714, 9566, 9554, 9678, 9646, 9590, 9558, 9798, 9610, 9550, 9638, 9586, 9578, 9623, 9571, 9563, 9603, 9707, 9711, 9783, 9779, 9715, 9567, 9555, 9679, 9647, 9591, 9559, 9799, 9611, 9551, 9639, 9587, 9579, 4074, 4026, 4018, 4142, 4058, 4162, 4166, 4238, 4234, 4170, 4022, 4010, 4130, 4098, 4046, 4014, 4254, 4062, 4006, 4090, 4042, 4034, 4075, 4027, 4019, 4143, 4059, 4163, 4167, 4239, 4235, 4171, 4023, 4011, 4131, 4099, 4047, 4015, 4255, 4063, 4007, 4091, 4043, 4035, 10882, 10830, 10822, 10950, 10862, 10994, 10970, 11042, 11038, 10974, 10826, 10814, 10938, 10906, 10850, 10818, 11058, 10870, 10810, 10898, 10846, 10838, 10883, 10831, 10823, 10951, 10863, 10995, 10971, 11043, 11039, 10975, 10827, 10815, 10939, 10907, 10851, 10819, 11059, 10871, 10811, 10899, 10847, 10839, 11134, 11082, 11074, 11202, 11114, 11222, 11230, 11294, 11290, 11226, 11078, 11066, 11190, 11158, 11102, 11070, 11310, 11122, 11062, 11150, 11098, 11090, 11135, 11083, 11075, 11203, 11115, 11223, 11231, 11295, 11291, 11227, 11079, 11067, 11191, 11159, 11103, 11071, 11311, 11123, 11063, 11151, 11099, 11091, 15670, 15618, 15610, 15738, 15650, 15758, 15762, 15834, 15830, 15766, 15614, 15602, 15726, 15694, 15638, 15606, 15846, 15658, 15598, 15686, 15634, 15626, 15671, 15619, 15611, 15739, 15651, 15759, 15763, 15835, 15831, 15767, 15615, 15603, 15727, 15695, 15639, 15607, 15847, 15659, 15599, 15687, 15635, 15627, 15418, 15366, 15358, 15486, 15398, 15506, 15510, 15578, 15586, 15514, 15362, 15350, 15474, 15442, 15386, 15354, 15594, 15406, 15346, 15434, 15382, 15374, 15419, 15367, 15359, 15487, 15399, 15507, 15511, 15579, 15587, 15515, 15363, 15351, 15475, 15443, 15387, 15355, 15595, 15407, 15347, 15435, 15383, 15375, 11386, 11334, 11326, 11454, 11366, 11474, 11478, 11546, 11542, 11486, 11330, 11318, 11442, 11410, 11354, 11322, 11562, 11374, 11314, 11402, 11350, 11342, 11387, 11335, 11327, 11455, 11367, 11475, 11479, 11547, 11543, 11487, 11331, 11319, 11443, 11411, 11355, 11323, 11563, 11375, 11315, 11403, 11351, 11343, 1806, 1754, 1750, 1874, 1786, 1894, 1898, 1970, 1966, 1902, 1742, 1862, 1830, 1774, 1746, 1986, 1794, 1738, 1822, 1770, 1762, 1807, 1755, 1751, 1875, 1787, 1895, 1899, 1971, 1967, 1903, 1743, 1863, 1831, 1775, 1747, 1987, 1795, 1739, 1823, 1771, 1763, 1050, 998, 990, 1118, 1030, 1138, 1142, 1214, 1210, 1146, 994, 1078, 1106, 1074, 1018, 986, 1230, 1038, 982, 1066, 1014, 1006, 1051, 999, 991, 1119, 1031, 1139, 1143, 1215, 1211, 1147, 995, 1079, 1107, 1075, 1019, 987, 1231, 1039, 983, 1067, 1015, 1007, 8866, 8814, 8806, 8930, 8846, 8950, 8954, 9026, 9022, 8958, 8810, 8798, 8926, 8890, 8834, 8802, 9042, 8854, 8794, 8882, 8830, 8822, 8867, 8815, 8807, 8931, 8847, 8951, 8955, 9027, 9023, 8959, 8811, 8799, 8927, 8891, 8835, 8803, 9043, 8855, 8795, 8883, 8831, 8823, 6850, 6798, 6790, 6914, 6830, 6934, 6938, 7010, 7006, 6942, 6794, 6782, 6902, 6818, 6786, 7026, 6838, 6778, 6866, 6814, 6806, 6851, 6799, 6791, 6915, 6831, 6935, 6939, 7011, 7007, 6943, 6795, 6783, 6903, 6819, 6787, 7027, 6839, 6779, 6867, 6815, 6807, 3318, 3270, 3262, 3386, 3298, 3406, 3410, 3482, 3478, 3414, 3266, 3254, 3374, 3342, 3258, 3498, 3306, 3250, 3334, 3286, 3278, 3319, 3271, 3263, 3387, 3299, 3407, 3411, 3483, 3479, 3415, 3267, 3255, 3375, 3343, 3259, 3499, 3307, 3251, 3335, 3287, 3279, 1302, 1250, 1242, 1370, 1282, 1390, 1394, 1466, 1462, 1398, 1246, 1238, 1358, 1326, 1270, 1322, 1482, 1290, 1234, 1318, 1266, 1258, 1303, 1251, 1243, 1371, 1283, 1391, 1395, 1467, 1463, 1399, 1247, 1239, 1359, 1327, 1271, 1323, 1483, 1291, 1235, 1319, 1267, 1259, 16678, 16626, 16618, 16746, 16658, 16766, 16770, 16842, 16838, 16774, 16622, 16610, 16734, 16702, 16646, 16614, 16666, 16606, 16694, 16642, 16634, 16679, 16627, 16619, 16747, 16659, 16767, 16771, 16843, 16839, 16775, 16623, 16611, 16735, 16703, 16647, 16615, 16667, 16607, 16695, 16643, 16635, 4578, 4530, 4522, 4646, 4562, 4666, 4670, 4742, 4738, 4674, 4526, 4514, 4634, 4602, 4550, 4518, 4758, 4610, 4510, 4594, 4546, 4538, 4579, 4531, 4523, 4647, 4563, 4667, 4671, 4743, 4739, 4675, 4527, 4515, 4635, 4603, 4551, 4519, 4759, 4611, 4511, 4595, 4547, 4539, 798, 746, 738, 866, 778, 886, 890, 962, 958, 894, 742, 730, 854, 822, 766, 734, 978, 786, 750, 814, 762, 754, 799, 747, 739, 867, 779, 887, 891, 963, 959, 895, 743, 731, 855, 823, 767, 735, 979, 787, 751, 815, 763, 755, 6346, 6294, 6286, 6410, 6326, 6430, 6434, 6506, 6502, 6438, 6290, 6278, 6398, 6366, 6314, 6282, 6522, 6334, 6274, 6310, 6302, 6347, 6295, 6287, 6411, 6327, 6431, 6435, 6507, 6503, 6439, 6291, 6279, 6399, 6367, 6315, 6283, 6523, 6335, 6275, 6311, 6303, 3066, 3018, 3010, 3134, 3046, 3154, 3158, 3230, 3226, 3162, 3014, 3002, 3122, 3090, 3034, 3006, 3246, 3054, 2998, 3082, 3026, 3067, 3019, 3011, 3135, 3047, 3155, 3159, 3231, 3227, 3163, 3015, 3003, 3123, 3091, 3035, 3007, 3247, 3055, 2999, 3083, 3027, 2562, 2514, 2506, 2630, 2542, 2650, 2654, 2726, 2722, 2658, 2510, 2498, 2618, 2586, 2530, 2502, 2742, 2550, 2494, 2578, 2526, 2563, 2515, 2507, 2631, 2543, 2651, 2655, 2727, 2723, 2659, 2511, 2499, 2619, 2587, 2531, 2503, 2743, 2551, 2495, 2579, 2527, 17144, 17136, 17140, 17128, 17168, 17164, 17160, 17132, 17156, 17145, 17137, 17141, 17129, 17169, 17165, 17161, 17133, 17157, 17004, 17044, 17000, 16992, 17032, 17028, 17024, 16996, 17020, 17005, 17045, 17001, 16993, 17033, 17029, 17025, 16997, 17021, 17072, 17068, 17124, 17060, 17100, 17096, 17092, 17064, 17088, 17073, 17069, 17125, 17061, 17101, 17097, 17093, 17065, 17089, 16868, 16860, 16864, 16880, 16896, 16892, 16888, 16856, 16884, 16869, 16861, 16865, 16881, 16897, 16893, 16889, 16857, 16885, 17620, 17612, 17616, 17604, 17644, 17640, 17608, 17636, 17621, 17613, 17617, 17605, 17645, 17641, 17609, 17637, 17552, 17544, 17548, 17536, 17576, 17572, 17540, 17568, 17553, 17545, 17549, 17537, 17577, 17573, 17541, 17569, 17484, 17476, 17480, 17468, 17508, 17504, 17516, 17472, 17500, 17485, 17477, 17481, 17469, 17509, 17505, 17517, 17473, 17501, 16936, 16928, 16932, 16924, 16964, 16960, 16956, 16968, 16952, 16937, 16929, 16933, 16925, 16965, 16961, 16957, 16969, 16953, 17416, 17408, 17412, 17400, 17440, 17436, 17432, 17404, 17417, 17409, 17413, 17401, 17441, 17437, 17433, 17405, 17146, 17138, 17142, 17130, 17170, 17166, 17162, 17134, 17158, 17147, 17139, 17143, 17131, 17171, 17167, 17163, 17135, 17159, 17006, 17046, 17002, 16994, 17034, 17030, 17026, 16998, 17022, 17007, 17047, 17003, 16995, 17035, 17031, 17027, 16999, 17023, 17074, 17070, 17126, 17062, 17102, 17098, 17094, 17066, 17090, 17075, 17071, 17127, 17063, 17103, 17099, 17095, 17067, 17091, 16870, 16862, 16866, 16882, 16898, 16894, 16890, 16858, 16886, 16871, 16863, 16867, 16883, 16899, 16895, 16891, 16859, 16887, 17622, 17614, 17618, 17606, 17646, 17642, 17610, 17638, 17623, 17615, 17619, 17607, 17647, 17643, 17611, 17639, 17554, 17546, 17550, 17538, 17578, 17574, 17542, 17570, 17555, 17547, 17551, 17539, 17579, 17575, 17543, 17571, 17486, 17478, 17482, 17470, 17510, 17506, 17518, 17474, 17502, 17487, 17479, 17483, 17471, 17511, 17507, 17519, 17475, 17503, 16938, 16930, 16934, 16926, 16966, 16962, 16958, 16970, 16954, 16939, 16931, 16935, 16927, 16967, 16963, 16959, 16971, 16955, 17418, 17410, 17414, 17402, 17442, 17438, 17434, 17406, 17419, 17411, 17415, 17403, 17443, 17439, 17435, 17407, 18912, 18908, 18924, 18913, 18909, 18925, 18888, 18896, 18904, 18889, 18897, 18905, 18992, 18988, 18993, 18989, 18914, 18910, 18926, 18915, 18911, 18927, 18890, 18898, 18906, 18891, 18899, 18907, 18994, 18990, 18995, 18991, 18124, 18116, 18108, 18125, 18117, 18109, 18168, 18164, 18169, 18165, 18080, 18088, 18084, 18081, 18089, 18085, 18126, 18118, 18110, 18127, 18119, 18111, 18170, 18166, 18171, 18167, 18082, 18090, 18086, 18083, 18091, 18087, 288, 272, 308, 276, 264, 296, 268, 260, 292, 284, 289, 273, 309, 277, 265, 297, 269, 261, 293, 285, 172, 200, 204, 168, 160, 192, 164, 156, 188, 180, 173, 201, 205, 169, 161, 193, 165, 157, 189, 181, 696, 688, 692, 680, 716, 684, 676, 712, 704, 697, 689, 693, 681, 717, 685, 677, 713, 705, 224, 220, 256, 212, 244, 216, 208, 240, 232, 225, 221, 257, 213, 245, 217, 209, 241, 233, 68, 60, 100, 64, 88, 56, 52, 84, 76, 69, 61, 101, 65, 89, 57, 53, 85, 77, 540, 532, 568, 536, 524, 528, 520, 556, 548, 541, 533, 569, 537, 525, 529, 521, 557, 549, 120, 112, 152, 116, 108, 140, 104, 136, 128, 121, 113, 153, 117, 109, 141, 105, 137, 129, 16, 8, 48, 12, 0, 36, 4, 20, 32, 24, 17, 9, 49, 13, 1, 37, 5, 21, 33, 25, 488, 480, 516, 484, 472, 504, 476, 468, 496, 489, 481, 517, 485, 473, 505, 477, 469, 497, 384, 376, 412, 380, 368, 400, 372, 364, 396, 385, 377, 413, 381, 369, 401, 373, 365, 397, 290, 274, 310, 278, 266, 298, 270, 262, 294, 286, 291, 275, 311, 279, 267, 299, 271, 263, 295, 287, 174, 202, 206, 170, 162, 194, 166, 158, 190, 182, 175, 203, 207, 171, 163, 195, 167, 159, 191, 183, 698, 690, 694, 682, 718, 686, 678, 714, 706, 699, 691, 695, 683, 719, 687, 679, 715, 707, 226, 222, 258, 214, 246, 218, 210, 242, 234, 227, 223, 259, 215, 247, 219, 211, 243, 235, 70, 62, 102, 66, 90, 58, 54, 86, 78, 71, 63, 103, 67, 91, 59, 55, 87, 79, 542, 534, 570, 538, 526, 530, 522, 558, 550, 543, 535, 571, 539, 527, 531, 523, 559, 551, 122, 114, 154, 118, 110, 142, 106, 138, 130, 123, 115, 155, 119, 111, 143, 107, 139, 131, 18, 10, 50, 14, 2, 38, 6, 22, 34, 26, 19, 11, 51, 15, 3, 39, 7, 23, 35, 27, 490, 482, 518, 486, 474, 506, 478, 470, 498, 491, 483, 519, 487, 475, 507, 479, 471, 499, 386, 378, 414, 382, 370, 402, 374, 366, 398, 387, 379, 415, 383, 371, 403, 375, 367, 399]

my_set = set(my_list)

count = 0
for idx, row in lde.iterrows():
    if count in my_set:
        print(logic_2_questions[idx] + ' ' + f"{row[5]} {row[10]} {row[15]}") 
#         print(f"{row[5]} {row[10]} {row[15]}")
#         print(f"{e1_entity_x} {combine_x} {e2_entity_y}")
    count += 1
# print(lde.index[:5])

In [ ]:
# Copy the index into a list, then generate the answers which match the questions. 

my_list = [18796, 18776, 18784, 18797, 18777, 18785, 18676, 18664, 18668, 18677, 18665, 18669, 18732, 18720, 18744, 18733, 18721, 18745, 18798, 18778, 18786, 18799, 18779, 18787, 18678, 18666, 18670, 18679, 18667, 18671, 18734, 18722, 18746, 18735, 18723, 18747, 18328, 18304, 18308, 18329, 18305, 18309, 18340, 18348, 18344, 18341, 18349, 18345, 18376, 18380, 18388, 18377, 18381, 18389, 18330, 18306, 18310, 18331, 18307, 18311, 18342, 18350, 18346, 18343, 18351, 18347, 18378, 18382, 18390, 18379, 18383, 18391, 5336, 5284, 5276, 5400, 5316, 5420, 5424, 5496, 5492, 5428, 5280, 5268, 5388, 5356, 5304, 5272, 5512, 5324, 5264, 5348, 5300, 5292, 5337, 5285, 5277, 5401, 5317, 5421, 5425, 5497, 5493, 5429, 5281, 5269, 5389, 5357, 5305, 5273, 5513, 5325, 5265, 5349, 5301, 5293, 2056, 2016, 2000, 2124, 2036, 2144, 2148, 2220, 2216, 2152, 2004, 1992, 2112, 2080, 2024, 1996, 2236, 2044, 1988, 2072, 2020, 2012, 2057, 2017, 2001, 2125, 2037, 2145, 2149, 2221, 2217, 2153, 2005, 1993, 2113, 2081, 2025, 1997, 2237, 2045, 1989, 2073, 2021, 2013, 1552, 1500, 1528, 1620, 1532, 1640, 1644, 1716, 1712, 1648, 1496, 1488, 1608, 1576, 1520, 1492, 1732, 1540, 1484, 1568, 1516, 1508, 1553, 1501, 1529, 1621, 1533, 1641, 1645, 1717, 1713, 1649, 1497, 1489, 1609, 1577, 1521, 1493, 1733, 1541, 1485, 1569, 1517, 1509, 9620, 9568, 9560, 9600, 9704, 9708, 9780, 9776, 9712, 9564, 9552, 9676, 9644, 9588, 9556, 9796, 9608, 9548, 9636, 9584, 9576, 9621, 9569, 9561, 9601, 9705, 9709, 9781, 9777, 9713, 9565, 9553, 9677, 9645, 9589, 9557, 9797, 9609, 9549, 9637, 9585, 9577, 4072, 4024, 4016, 4140, 4056, 4160, 4164, 4236, 4232, 4168, 4020, 4008, 4128, 4096, 4044, 4012, 4252, 4060, 4004, 4088, 4040, 4032, 4073, 4025, 4017, 4141, 4057, 4161, 4165, 4237, 4233, 4169, 4021, 4009, 4129, 4097, 4045, 4013, 4253, 4061, 4005, 4089, 4041, 4033, 10880, 10828, 10820, 10948, 10860, 10992, 10968, 11040, 11036, 10972, 10824, 10812, 10936, 10904, 10848, 10816, 11056, 10868, 10808, 10896, 10844, 10836, 10881, 10829, 10821, 10949, 10861, 10993, 10969, 11041, 11037, 10973, 10825, 10813, 10937, 10905, 10849, 10817, 11057, 10869, 10809, 10897, 10845, 10837, 11132, 11080, 11072, 11200, 11112, 11220, 11228, 11292, 11288, 11224, 11076, 11064, 11188, 11156, 11100, 11068, 11308, 11120, 11060, 11148, 11096, 11088, 11133, 11081, 11073, 11201, 11113, 11221, 11229, 11293, 11289, 11225, 11077, 11065, 11189, 11157, 11101, 11069, 11309, 11121, 11061, 11149, 11097, 11089, 15668, 15616, 15608, 15736, 15648, 15756, 15760, 15832, 15828, 15764, 15612, 15600, 15724, 15692, 15636, 15604, 15844, 15656, 15596, 15684, 15632, 15624, 15669, 15617, 15609, 15737, 15649, 15757, 15761, 15833, 15829, 15765, 15613, 15601, 15725, 15693, 15637, 15605, 15845, 15657, 15597, 15685, 15633, 15625, 15416, 15364, 15356, 15484, 15396, 15504, 15508, 15576, 15584, 15512, 15360, 15348, 15472, 15440, 15384, 15352, 15592, 15404, 15344, 15432, 15380, 15372, 15417, 15365, 15357, 15485, 15397, 15505, 15509, 15577, 15585, 15513, 15361, 15349, 15473, 15441, 15385, 15353, 15593, 15405, 15345, 15433, 15381, 15373, 11384, 11332, 11324, 11452, 11364, 11472, 11476, 11544, 11540, 11484, 11328, 11316, 11440, 11408, 11352, 11320, 11560, 11372, 11312, 11400, 11348, 11340, 11385, 11333, 11325, 11453, 11365, 11473, 11477, 11545, 11541, 11485, 11329, 11317, 11441, 11409, 11353, 11321, 11561, 11373, 11313, 11401, 11349, 11341, 1804, 1752, 1748, 1872, 1784, 1892, 1896, 1968, 1964, 1900, 1740, 1860, 1828, 1772, 1744, 1984, 1792, 1736, 1820, 1768, 1760, 1805, 1753, 1749, 1873, 1785, 1893, 1897, 1969, 1965, 1901, 1741, 1861, 1829, 1773, 1745, 1985, 1793, 1737, 1821, 1769, 1761, 1048, 996, 988, 1116, 1028, 1136, 1140, 1212, 1208, 1144, 992, 1076, 1104, 1072, 1016, 984, 1228, 1036, 980, 1064, 1012, 1004, 1049, 997, 989, 1117, 1029, 1137, 1141, 1213, 1209, 1145, 993, 1077, 1105, 1073, 1017, 985, 1229, 1037, 981, 1065, 1013, 1005, 8864, 8812, 8804, 8928, 8844, 8948, 8952, 9024, 9020, 8956, 8808, 8796, 8924, 8888, 8832, 8800, 9040, 8852, 8792, 8880, 8828, 8820, 8865, 8813, 8805, 8929, 8845, 8949, 8953, 9025, 9021, 8957, 8809, 8797, 8925, 8889, 8833, 8801, 9041, 8853, 8793, 8881, 8829, 8821, 6848, 6796, 6788, 6912, 6828, 6932, 6936, 7008, 7004, 6940, 6792, 6780, 6900, 6816, 6784, 7024, 6836, 6776, 6864, 6812, 6804, 6849, 6797, 6789, 6913, 6829, 6933, 6937, 7009, 7005, 6941, 6793, 6781, 6901, 6817, 6785, 7025, 6837, 6777, 6865, 6813, 6805, 3316, 3268, 3260, 3384, 3296, 3404, 3408, 3480, 3476, 3412, 3264, 3252, 3372, 3340, 3256, 3496, 3304, 3248, 3332, 3284, 3276, 3317, 3269, 3261, 3385, 3297, 3405, 3409, 3481, 3477, 3413, 3265, 3253, 3373, 3341, 3257, 3497, 3305, 3249, 3333, 3285, 3277, 1300, 1248, 1240, 1368, 1280, 1388, 1392, 1464, 1460, 1396, 1244, 1236, 1356, 1324, 1268, 1320, 1480, 1288, 1232, 1316, 1264, 1256, 1301, 1249, 1241, 1369, 1281, 1389, 1393, 1465, 1461, 1397, 1245, 1237, 1357, 1325, 1269, 1321, 1481, 1289, 1233, 1317, 1265, 1257, 16676, 16624, 16616, 16744, 16656, 16764, 16768, 16840, 16836, 16772, 16620, 16608, 16732, 16700, 16644, 16612, 16664, 16604, 16692, 16640, 16632, 16677, 16625, 16617, 16745, 16657, 16765, 16769, 16841, 16837, 16773, 16621, 16609, 16733, 16701, 16645, 16613, 16665, 16605, 16693, 16641, 16633, 4576, 4528, 4520, 4644, 4560, 4664, 4668, 4740, 4736, 4672, 4524, 4512, 4632, 4600, 4548, 4516, 4756, 4608, 4508, 4592, 4544, 4536, 4577, 4529, 4521, 4645, 4561, 4665, 4669, 4741, 4737, 4673, 4525, 4513, 4633, 4601, 4549, 4517, 4757, 4609, 4509, 4593, 4545, 4537, 796, 744, 736, 864, 776, 884, 888, 960, 956, 892, 740, 728, 852, 820, 764, 732, 976, 784, 748, 812, 760, 752, 797, 745, 737, 865, 777, 885, 889, 961, 957, 893, 741, 729, 853, 821, 765, 733, 977, 785, 749, 813, 761, 753, 6344, 6292, 6284, 6408, 6324, 6428, 6432, 6504, 6500, 6436, 6288, 6276, 6396, 6364, 6312, 6280, 6520, 6332, 6272, 6308, 6300, 6345, 6293, 6285, 6409, 6325, 6429, 6433, 6505, 6501, 6437, 6289, 6277, 6397, 6365, 6313, 6281, 6521, 6333, 6273, 6309, 6301, 3064, 3016, 3008, 3132, 3044, 3152, 3156, 3228, 3224, 3160, 3012, 3000, 3120, 3088, 3032, 3004, 3244, 3052, 2996, 3080, 3024, 3065, 3017, 3009, 3133, 3045, 3153, 3157, 3229, 3225, 3161, 3013, 3001, 3121, 3089, 3033, 3005, 3245, 3053, 2997, 3081, 3025, 2560, 2512, 2504, 2628, 2540, 2648, 2652, 2724, 2720, 2656, 2508, 2496, 2616, 2584, 2528, 2500, 2740, 2548, 2492, 2576, 2524, 2561, 2513, 2505, 2629, 2541, 2649, 2653, 2725, 2721, 2657, 2509, 2497, 2617, 2585, 2529, 2501, 2741, 2549, 2493, 2577, 2525, 5338, 5286, 5278, 5402, 5318, 5422, 5426, 5498, 5494, 5430, 5282, 5270, 5390, 5358, 5306, 5274, 5514, 5326, 5266, 5350, 5302, 5294, 5339, 5287, 5279, 5403, 5319, 5423, 5427, 5499, 5495, 5431, 5283, 5271, 5391, 5359, 5307, 5275, 5515, 5327, 5267, 5351, 5303, 5295, 2058, 2018, 2002, 2126, 2038, 2146, 2150, 2222, 2218, 2154, 2006, 1994, 2114, 2082, 2026, 1998, 2238, 2046, 1990, 2074, 2022, 2014, 2059, 2019, 2003, 2127, 2039, 2147, 2151, 2223, 2219, 2155, 2007, 1995, 2115, 2083, 2027, 1999, 2239, 2047, 1991, 2075, 2023, 2015, 1554, 1502, 1530, 1622, 1534, 1642, 1646, 1718, 1714, 1650, 1498, 1490, 1610, 1578, 1522, 1494, 1734, 1542, 1486, 1570, 1518, 1510, 1555, 1503, 1531, 1623, 1535, 1643, 1647, 1719, 1715, 1651, 1499, 1491, 1611, 1579, 1523, 1495, 1735, 1543, 1487, 1571, 1519, 1511, 9622, 9570, 9562, 9602, 9706, 9710, 9782, 9778, 9714, 9566, 9554, 9678, 9646, 9590, 9558, 9798, 9610, 9550, 9638, 9586, 9578, 9623, 9571, 9563, 9603, 9707, 9711, 9783, 9779, 9715, 9567, 9555, 9679, 9647, 9591, 9559, 9799, 9611, 9551, 9639, 9587, 9579, 4074, 4026, 4018, 4142, 4058, 4162, 4166, 4238, 4234, 4170, 4022, 4010, 4130, 4098, 4046, 4014, 4254, 4062, 4006, 4090, 4042, 4034, 4075, 4027, 4019, 4143, 4059, 4163, 4167, 4239, 4235, 4171, 4023, 4011, 4131, 4099, 4047, 4015, 4255, 4063, 4007, 4091, 4043, 4035, 10882, 10830, 10822, 10950, 10862, 10994, 10970, 11042, 11038, 10974, 10826, 10814, 10938, 10906, 10850, 10818, 11058, 10870, 10810, 10898, 10846, 10838, 10883, 10831, 10823, 10951, 10863, 10995, 10971, 11043, 11039, 10975, 10827, 10815, 10939, 10907, 10851, 10819, 11059, 10871, 10811, 10899, 10847, 10839, 11134, 11082, 11074, 11202, 11114, 11222, 11230, 11294, 11290, 11226, 11078, 11066, 11190, 11158, 11102, 11070, 11310, 11122, 11062, 11150, 11098, 11090, 11135, 11083, 11075, 11203, 11115, 11223, 11231, 11295, 11291, 11227, 11079, 11067, 11191, 11159, 11103, 11071, 11311, 11123, 11063, 11151, 11099, 11091, 15670, 15618, 15610, 15738, 15650, 15758, 15762, 15834, 15830, 15766, 15614, 15602, 15726, 15694, 15638, 15606, 15846, 15658, 15598, 15686, 15634, 15626, 15671, 15619, 15611, 15739, 15651, 15759, 15763, 15835, 15831, 15767, 15615, 15603, 15727, 15695, 15639, 15607, 15847, 15659, 15599, 15687, 15635, 15627, 15418, 15366, 15358, 15486, 15398, 15506, 15510, 15578, 15586, 15514, 15362, 15350, 15474, 15442, 15386, 15354, 15594, 15406, 15346, 15434, 15382, 15374, 15419, 15367, 15359, 15487, 15399, 15507, 15511, 15579, 15587, 15515, 15363, 15351, 15475, 15443, 15387, 15355, 15595, 15407, 15347, 15435, 15383, 15375, 11386, 11334, 11326, 11454, 11366, 11474, 11478, 11546, 11542, 11486, 11330, 11318, 11442, 11410, 11354, 11322, 11562, 11374, 11314, 11402, 11350, 11342, 11387, 11335, 11327, 11455, 11367, 11475, 11479, 11547, 11543, 11487, 11331, 11319, 11443, 11411, 11355, 11323, 11563, 11375, 11315, 11403, 11351, 11343, 1806, 1754, 1750, 1874, 1786, 1894, 1898, 1970, 1966, 1902, 1742, 1862, 1830, 1774, 1746, 1986, 1794, 1738, 1822, 1770, 1762, 1807, 1755, 1751, 1875, 1787, 1895, 1899, 1971, 1967, 1903, 1743, 1863, 1831, 1775, 1747, 1987, 1795, 1739, 1823, 1771, 1763, 1050, 998, 990, 1118, 1030, 1138, 1142, 1214, 1210, 1146, 994, 1078, 1106, 1074, 1018, 986, 1230, 1038, 982, 1066, 1014, 1006, 1051, 999, 991, 1119, 1031, 1139, 1143, 1215, 1211, 1147, 995, 1079, 1107, 1075, 1019, 987, 1231, 1039, 983, 1067, 1015, 1007, 8866, 8814, 8806, 8930, 8846, 8950, 8954, 9026, 9022, 8958, 8810, 8798, 8926, 8890, 8834, 8802, 9042, 8854, 8794, 8882, 8830, 8822, 8867, 8815, 8807, 8931, 8847, 8951, 8955, 9027, 9023, 8959, 8811, 8799, 8927, 8891, 8835, 8803, 9043, 8855, 8795, 8883, 8831, 8823, 6850, 6798, 6790, 6914, 6830, 6934, 6938, 7010, 7006, 6942, 6794, 6782, 6902, 6818, 6786, 7026, 6838, 6778, 6866, 6814, 6806, 6851, 6799, 6791, 6915, 6831, 6935, 6939, 7011, 7007, 6943, 6795, 6783, 6903, 6819, 6787, 7027, 6839, 6779, 6867, 6815, 6807, 3318, 3270, 3262, 3386, 3298, 3406, 3410, 3482, 3478, 3414, 3266, 3254, 3374, 3342, 3258, 3498, 3306, 3250, 3334, 3286, 3278, 3319, 3271, 3263, 3387, 3299, 3407, 3411, 3483, 3479, 3415, 3267, 3255, 3375, 3343, 3259, 3499, 3307, 3251, 3335, 3287, 3279, 1302, 1250, 1242, 1370, 1282, 1390, 1394, 1466, 1462, 1398, 1246, 1238, 1358, 1326, 1270, 1322, 1482, 1290, 1234, 1318, 1266, 1258, 1303, 1251, 1243, 1371, 1283, 1391, 1395, 1467, 1463, 1399, 1247, 1239, 1359, 1327, 1271, 1323, 1483, 1291, 1235, 1319, 1267, 1259, 16678, 16626, 16618, 16746, 16658, 16766, 16770, 16842, 16838, 16774, 16622, 16610, 16734, 16702, 16646, 16614, 16666, 16606, 16694, 16642, 16634, 16679, 16627, 16619, 16747, 16659, 16767, 16771, 16843, 16839, 16775, 16623, 16611, 16735, 16703, 16647, 16615, 16667, 16607, 16695, 16643, 16635, 4578, 4530, 4522, 4646, 4562, 4666, 4670, 4742, 4738, 4674, 4526, 4514, 4634, 4602, 4550, 4518, 4758, 4610, 4510, 4594, 4546, 4538, 4579, 4531, 4523, 4647, 4563, 4667, 4671, 4743, 4739, 4675, 4527, 4515, 4635, 4603, 4551, 4519, 4759, 4611, 4511, 4595, 4547, 4539, 798, 746, 738, 866, 778, 886, 890, 962, 958, 894, 742, 730, 854, 822, 766, 734, 978, 786, 750, 814, 762, 754, 799, 747, 739, 867, 779, 887, 891, 963, 959, 895, 743, 731, 855, 823, 767, 735, 979, 787, 751, 815, 763, 755, 6346, 6294, 6286, 6410, 6326, 6430, 6434, 6506, 6502, 6438, 6290, 6278, 6398, 6366, 6314, 6282, 6522, 6334, 6274, 6310, 6302, 6347, 6295, 6287, 6411, 6327, 6431, 6435, 6507, 6503, 6439, 6291, 6279, 6399, 6367, 6315, 6283, 6523, 6335, 6275, 6311, 6303, 3066, 3018, 3010, 3134, 3046, 3154, 3158, 3230, 3226, 3162, 3014, 3002, 3122, 3090, 3034, 3006, 3246, 3054, 2998, 3082, 3026, 3067, 3019, 3011, 3135, 3047, 3155, 3159, 3231, 3227, 3163, 3015, 3003, 3123, 3091, 3035, 3007, 3247, 3055, 2999, 3083, 3027, 2562, 2514, 2506, 2630, 2542, 2650, 2654, 2726, 2722, 2658, 2510, 2498, 2618, 2586, 2530, 2502, 2742, 2550, 2494, 2578, 2526, 2563, 2515, 2507, 2631, 2543, 2651, 2655, 2727, 2723, 2659, 2511, 2499, 2619, 2587, 2531, 2503, 2743, 2551, 2495, 2579, 2527, 17144, 17136, 17140, 17128, 17168, 17164, 17160, 17132, 17156, 17145, 17137, 17141, 17129, 17169, 17165, 17161, 17133, 17157, 17004, 17044, 17000, 16992, 17032, 17028, 17024, 16996, 17020, 17005, 17045, 17001, 16993, 17033, 17029, 17025, 16997, 17021, 17072, 17068, 17124, 17060, 17100, 17096, 17092, 17064, 17088, 17073, 17069, 17125, 17061, 17101, 17097, 17093, 17065, 17089, 16868, 16860, 16864, 16880, 16896, 16892, 16888, 16856, 16884, 16869, 16861, 16865, 16881, 16897, 16893, 16889, 16857, 16885, 17620, 17612, 17616, 17604, 17644, 17640, 17608, 17636, 17621, 17613, 17617, 17605, 17645, 17641, 17609, 17637, 17552, 17544, 17548, 17536, 17576, 17572, 17540, 17568, 17553, 17545, 17549, 17537, 17577, 17573, 17541, 17569, 17484, 17476, 17480, 17468, 17508, 17504, 17516, 17472, 17500, 17485, 17477, 17481, 17469, 17509, 17505, 17517, 17473, 17501, 16936, 16928, 16932, 16924, 16964, 16960, 16956, 16968, 16952, 16937, 16929, 16933, 16925, 16965, 16961, 16957, 16969, 16953, 17416, 17408, 17412, 17400, 17440, 17436, 17432, 17404, 17417, 17409, 17413, 17401, 17441, 17437, 17433, 17405, 17146, 17138, 17142, 17130, 17170, 17166, 17162, 17134, 17158, 17147, 17139, 17143, 17131, 17171, 17167, 17163, 17135, 17159, 17006, 17046, 17002, 16994, 17034, 17030, 17026, 16998, 17022, 17007, 17047, 17003, 16995, 17035, 17031, 17027, 16999, 17023, 17074, 17070, 17126, 17062, 17102, 17098, 17094, 17066, 17090, 17075, 17071, 17127, 17063, 17103, 17099, 17095, 17067, 17091, 16870, 16862, 16866, 16882, 16898, 16894, 16890, 16858, 16886, 16871, 16863, 16867, 16883, 16899, 16895, 16891, 16859, 16887, 17622, 17614, 17618, 17606, 17646, 17642, 17610, 17638, 17623, 17615, 17619, 17607, 17647, 17643, 17611, 17639, 17554, 17546, 17550, 17538, 17578, 17574, 17542, 17570, 17555, 17547, 17551, 17539, 17579, 17575, 17543, 17571, 17486, 17478, 17482, 17470, 17510, 17506, 17518, 17474, 17502, 17487, 17479, 17483, 17471, 17511, 17507, 17519, 17475, 17503, 16938, 16930, 16934, 16926, 16966, 16962, 16958, 16970, 16954, 16939, 16931, 16935, 16927, 16967, 16963, 16959, 16971, 16955, 17418, 17410, 17414, 17402, 17442, 17438, 17434, 17406, 17419, 17411, 17415, 17403, 17443, 17439, 17435, 17407, 18912, 18908, 18924, 18913, 18909, 18925, 18888, 18896, 18904, 18889, 18897, 18905, 18992, 18988, 18993, 18989, 18914, 18910, 18926, 18915, 18911, 18927, 18890, 18898, 18906, 18891, 18899, 18907, 18994, 18990, 18995, 18991, 18124, 18116, 18108, 18125, 18117, 18109, 18168, 18164, 18169, 18165, 18080, 18088, 18084, 18081, 18089, 18085, 18126, 18118, 18110, 18127, 18119, 18111, 18170, 18166, 18171, 18167, 18082, 18090, 18086, 18083, 18091, 18087, 288, 272, 308, 276, 264, 296, 268, 260, 292, 284, 289, 273, 309, 277, 265, 297, 269, 261, 293, 285, 172, 200, 204, 168, 160, 192, 164, 156, 188, 180, 173, 201, 205, 169, 161, 193, 165, 157, 189, 181, 696, 688, 692, 680, 716, 684, 676, 712, 704, 697, 689, 693, 681, 717, 685, 677, 713, 705, 224, 220, 256, 212, 244, 216, 208, 240, 232, 225, 221, 257, 213, 245, 217, 209, 241, 233, 68, 60, 100, 64, 88, 56, 52, 84, 76, 69, 61, 101, 65, 89, 57, 53, 85, 77, 540, 532, 568, 536, 524, 528, 520, 556, 548, 541, 533, 569, 537, 525, 529, 521, 557, 549, 120, 112, 152, 116, 108, 140, 104, 136, 128, 121, 113, 153, 117, 109, 141, 105, 137, 129, 16, 8, 48, 12, 0, 36, 4, 20, 32, 24, 17, 9, 49, 13, 1, 37, 5, 21, 33, 25, 488, 480, 516, 484, 472, 504, 476, 468, 496, 489, 481, 517, 485, 473, 505, 477, 469, 497, 384, 376, 412, 380, 368, 400, 372, 364, 396, 385, 377, 413, 381, 369, 401, 373, 365, 397, 290, 274, 310, 278, 266, 298, 270, 262, 294, 286, 291, 275, 311, 279, 267, 299, 271, 263, 295, 287, 174, 202, 206, 170, 162, 194, 166, 158, 190, 182, 175, 203, 207, 171, 163, 195, 167, 159, 191, 183, 698, 690, 694, 682, 718, 686, 678, 714, 706, 699, 691, 695, 683, 719, 687, 679, 715, 707, 226, 222, 258, 214, 246, 218, 210, 242, 234, 227, 223, 259, 215, 247, 219, 211, 243, 235, 70, 62, 102, 66, 90, 58, 54, 86, 78, 71, 63, 103, 67, 91, 59, 55, 87, 79, 542, 534, 570, 538, 526, 530, 522, 558, 550, 543, 535, 571, 539, 527, 531, 523, 559, 551, 122, 114, 154, 118, 110, 142, 106, 138, 130, 123, 115, 155, 119, 111, 143, 107, 139, 131, 18, 10, 50, 14, 2, 38, 6, 22, 34, 26, 19, 11, 51, 15, 3, 39, 7, 23, 35, 27, 490, 482, 518, 486, 474, 506, 478, 470, 498, 491, 483, 519, 487, 475, 507, 479, 471, 499, 386, 378, 414, 382, 370, 402, 374, 366, 398, 387, 379, 415, 383, 371, 403, 375, 367, 399]

my_set = set(my_list)

count = 0
for idx, row in lde.iterrows():
    if count in my_set:
        print(f"{row[5]} {row[10]} {row[15]}") 
#         print(f"{row[5]} {row[10]} {row[15]}")
#         print(f"{e1_entity_x} {combine_x} {e2_entity_y}")
    count += 1
# print(lde.index[:5])

In [ ]:
# Generate answers by using unique_concat function. 

logic_2_questions_answers = 'Count how many ' + unique_concat(
    lde.e1_classes.str.cat(sep=' ', others=[lde['not_x'], lde.r1_relation_x, lde.e2_entity_x, lde['combine_x'], 
                                            lde.r1_relation_y, lde.e2_entity_y]),
)
pprint(f'{len(logic_2_questions)} logic_2 questions in total')
pprint(logic_2_questions.tolist()[:3000])
logic_2 = pd.DataFrame(logic_2_questions)
logic_2.to_csv('~/LORA_DATA/generated/logic_2_questions.csv', index=True, header=True)

In [ ]:
print(lde.info())

In [ ]:
big_question_set = unique_concat(incl_not_questions, logic_2_questions)
pprint(f'{len(big_question_set)} questions in total')
pprint(big_question_set.tolist())

In [ ]:
# Query answers for 2 logic questions

def query_ontology(class_name, relation_name, entity_name):

    query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s
    WHERE {""" + f"""
        ?s onto:{relation_name} onto:{entity_name} .
    """ + '}'
    r1 = list(graph.query_owlready(query))
    return r1

def get_ontology_answer(class_name, relation_name, entity_name, not_modifier=False, index = -1):
    print('get new answer',class_name, relation_name, entity_name,index )
    if not_modifier:
        query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s 
        WHERE {
            ?s rdf:type ?type. ?type rdfs:subClassOf+ onto:Food . 
            FILTER NOT EXISTS { """  + f""" ?s onto:{relation_name} onto:{entity_name} . """ + \
            """} FILTER NOT EXISTS {?s rdfs:subClassOf ?t . } }""" 
        r2 = list(graph.query_owlready(query)) 
        print(index, 'index r2',r2 )
        return r2 
    else:
        results:list = query_ontology(class_name, relation_name, entity_name)
        return results


def compute_logical_relation(a1, a1_operator, a2):
    result = []

    # a1,a2,a3 = [set() if a == 'not_answer' else set(a) for a in [a1,a2,a3]]
    a1, a2 = set(a1), set(a2)
    if a1_operator == 'and':
        result = a1.intersection(a2)
    else:
        result = a1.union(a2)

    return result


from itertools import chain

a1 = lde.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_x, row.e2_entity_x, row.not_x, row.name), axis=1)
filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
flatten1  = [filter_function(val) for val in a1]
lde['a1'] = flatten1



a2 = lde.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_y, row.e2_entity_y, row.not_y), axis=1)
filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
flatten2  = [filter_function(val) for val in a2] 
lde['a2'] = flatten2


lde['fa'] = lde.apply(lambda row: compute_logical_relation(row.a1, row.combine_x,  row.a2), axis=1)

print('Answer:')
lde.head(50)

In [ ]:
def query_ontology(class_name, relation_name, entity_name):

    query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s
    WHERE {""" + f"""
        ?s onto:{relation_name} onto:{entity_name} .
    """ + '}'
    r1 = list(graph.query_owlready(query))
    return r1

def get_ontology_answer(class_name, relation_name, entity_name, not_modifier=False):
    if not_modifier:
        query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s 
        WHERE {
            ?s rdf:type ?type. ?type rdfs:subClassOf+ onto:Food . 
            FILTER NOT EXISTS { """  + f""" ?s onto:{relation_name} onto:{entity_name} . """ + \
            """} FILTER NOT EXISTS {?s rdfs:subClassOf ?t . } }""" 
        r2 = list(graph.query_owlready(query)) 
        return r2 
    else:
        results:list = query_ontology(class_name, relation_name, entity_name)
        return results


def compute_logical_relation(a1, a1_operator, a2, a2_operator, a3):
    result = []

    # a1,a2,a3 = [set() if a == 'not_answer' else set(a) for a in [a1,a2,a3]]
    a1, a2, a3 = set(a1), set(a2), set(a3)
    if a1_operator == 'and':
        result1 = a1.intersection(a2)
    else:
        result1 = a1.union(a2)

    if a2_operator == 'and':
        result = result1.intersection(a3)
    else:
        result = result1.union(a3)

    return result

# The below code is to add a null into the table. 
#     if len(result) == 0:
#         return np.nan
#     return list(result)


from itertools import chain
#a1 = c3e.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_x, row.e2_entity_x, row.not_x), axis=1)
a1 = lde.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_x, row.e2_entity_x, row.not_x), axis=1)
filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
flatten1  = [filter_function(val) for val in a1]
lde['a1'] = flatten1



a2 = lde.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_y, row.e2_entity_y, row.not_y), axis=1)
filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
flatten2  = [filter_function(val) for val in a2] 
lde['a2'] = flatten2


a3 = lde.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation, row.e2_entity), axis=1)
filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
flatten3  = [filter_function(val) for val in a3] 
lde['a3'] = flatten3

#c3e['fa'] = c3e.apply(lambda row: compute_logical_relation(row.a1, row.combine_x,  row.a2, row.combine_y, row.a3), axis=1)
lde['fa'] = qadb1.apply(lambda row: compute_logical_relation(row.a1, row.combine_x,  row.a2, row.combine_y, row.a3), axis=1)

print('Answer:')
# c3e.head(500)
lde.head(50)

In [ ]:
# --- Time for logic - Part 2 - Logic_2_Question ---Full code for logic 2. 
import numpy as np
import re
import random
multi_space = re.compile('\\s+')
multi_space_v = np.vectorize(lambda x: multi_space.sub(' ', x))

def unique_concat(*args):
    return np.char.array(multi_space_v(np.unique(np.concatenate(args))))

# just doing not first...
# key goal here is to add a column which has either "" or "not" and then simply explode and insert into question

not_df = string_df1.copy()
not_df['not'] = [['', 'not'] for i in not_df.index]
ent_not_df = not_df.explode('not')
cls_not_df = ent_not_df.explode('e1_classes')
incl_not_questions = 'Count how many ' + unique_concat(
    ent_not_df.e1_entity.str.cat(sep=' ', others=[ent_not_df['not'], ent_not_df.r1_relation, ent_not_df.e2_entity]),
    cls_not_df.e1_classes.str.cat(sep=' ', others=[cls_not_df['not'], cls_not_df.r1_relation, cls_not_df.e2_entity])
)
# tech note: can call incl_not_questions.tolist() to get list
# results: the resulting "questions" don't make perfect english sense at this point, that's a harder more time consuming problem to solve


# now adding and/or into this mix
# my thoughts at this point: group on an entity or a class at the first level and then generate expressions
# using "other properties for the same class"
# key thought: trying to generate different properties for the same "individual" or "entity" 
# doesn't make sense as for something like tomato, all tomatoes will have the same properties, 
# while not all the same foods will have the same properties

#  ent_idx_not_df = not_df.reset_index()
cls_idx_not_df = not_df.explode('e1_classes').reset_index(drop=True).reset_index()
#pprint(cls_idx_not_df)

cls_idx_not_df['combine'] = [['and', 'or'] for i in cls_idx_not_df.index]
logic_df=(
    pd.merge(cls_idx_not_df, cls_idx_not_df, on=['e1_classes'])
    .query("index_x!=index_y and e1_classes!='Thing'")

)
lde = logic_df.explode('not_x').explode('combine_x')

logic_2_questions = 'Count how many ' + unique_concat(
    lde.e1_classes.str.cat(sep=' ', others=[lde['not_x'], lde.r1_relation_x, lde.e2_entity_x, lde['combine_x'], 
                                            lde.r1_relation_y, lde.e2_entity_y]),
)

# now we have not questions for both individuals and class, and also some simple 2 case logic questions we can combine:

big_question_set = unique_concat(incl_not_questions, logic_2_questions)
pprint(f'{len(big_question_set)} questions in total')
# import random
pprint(random.sample(big_question_set.tolist(), 1000), width=120)
#pprint(big_question_set)
# for this simple set of 3 indivudal foods with properties, that have 2 sub-classes and one parent class, 
# We already have 152 questions. The sky is the limit now :) get creative!

# ;)

In [ ]:
# --- Time for logic - Part 3 - Logic_3_Question ---

#pd.options.display.max_columns=2000

pd.set_option("display.max_rows", None, "display.max_columns", None)
cls_3_combine=(
    pd.merge(logic_df, cls_idx_not_df, on=['e1_classes'])
    .query("index!=index_y and index!=index_x")
    #.query("not (r1_relation_x==r1_realtion_y and e1_entity_x == e1_entity_y or r1)")
    
)
c3e = cls_3_combine.explode('not_x').explode('combine_x').explode('not_y').explode('combine_y')

logic_3_questions = 'Count how many ' + unique_concat(
    c3e.e1_classes.str.cat(sep=' ', others=[c3e['not_x'], c3e.r1_relation_x, c3e.e2_entity_x, c3e['combine_x'], c3e['not_y'], c3e.r1_relation_y, c3e.e2_entity_y, c3e['combine_y'], c3e.r1_relation, c3e.e2_entity]),
)
pprint(f'{len(logic_3_questions)} logic_3 questions in total')
logic_3_questions.tolist()[:5000]
#logic_3_questions.tolist()[1000:2000]
# pprint('table')
# c3e

In [ ]:
# --- Time for logic - Part 3 - Logic_3_Question --- Save Questions to CSV file. 

#pd.options.display.max_columns=2000

pd.set_option("display.max_rows", None, "display.max_columns", None)
cls_3_combine=(
    pd.merge(logic_df, cls_idx_not_df, on=['e1_classes'])
    .query("index!=index_y and index!=index_x")
    #.query("not (r1_relation_x==r1_realtion_y and e1_entity_x == e1_entity_y or r1)")
    
)
c3e = cls_3_combine.explode('not_x').explode('combine_x').explode('not_y').explode('combine_y')

logic_3_questions = 'Count how many ' + unique_concat(
    c3e.e1_classes.str.cat(sep=' ', others=[c3e['not_x'], c3e.r1_relation_x, c3e.e2_entity_x, c3e['combine_x'], c3e['not_y'], c3e.r1_relation_y, c3e.e2_entity_y, c3e['combine_y'], c3e.r1_relation, c3e.e2_entity]),
)
pprint(f'{len(logic_3_questions)} logic_3 questions in total')
question = logic_3_questions.tolist()[:233888]
qdf = pd.DataFrame(question)
qdf.to_csv('~/git_paper_1/vqa_integration/batch_questions.csv', index=True, header=True)
#logic_3_questions.tolist()[1000:2000]
# pprint('table')
# c3e

In [ ]:
logic_df.head()

In [ ]:
c3e.head()

In [ ]:
qadb = c3e.copy()
qadb1 = qadb.iloc[:10000]
qadb1
# ansdb2 = ansdb.iloc[2001:4000]
# ansdb3 = ansdb.iloc[4001:6000]
# ansdb4 = ansdb.iloc[6001:8000]
# ansdb5 = ansdb.iloc[8001:10000]
# ansdb6 = ansdb.iloc[10001:12000]
# ansdb7 = ansdb.iloc[12001:14000]
# ansdb8 = ansdb.iloc[:5]
# ansdb9 = ansdb.iloc[:5]
# ansdb10 = ansdb.iloc[:5]

In [ ]:
# Generate Answers Code
# class_name    # relation_name     # entity_name
# Food        has_child_food      orange
# graph = default_world.as_rdflib_graph()


def query_ontology(class_name, relation_name, entity_name):

    query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s
    WHERE {""" + f"""
        ?s onto:{relation_name} onto:{entity_name} .
    """ + '}'
    r1 = list(graph.query_owlready(query))
    return r1

def get_ontology_answer(class_name, relation_name, entity_name, not_modifier=False):
    if not_modifier:
        query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s 
        WHERE {
            ?s rdf:type ?type. ?type rdfs:subClassOf+ onto:Food . 
            FILTER NOT EXISTS { """  + f""" ?s onto:{relation_name} onto:{entity_name} . """ + \
            """} FILTER NOT EXISTS {?s rdfs:subClassOf ?t . } }""" 
        r2 = list(graph.query_owlready(query)) 
        return r2 
    else:
        results:list = query_ontology(class_name, relation_name, entity_name)
        return results


def compute_logical_relation(a1, a1_operator, a2, a2_operator, a3):
    result = []

    # a1,a2,a3 = [set() if a == 'not_answer' else set(a) for a in [a1,a2,a3]]
    a1, a2, a3 = set(a1), set(a2), set(a3)
    if a1_operator == 'and':
        result1 = a1.intersection(a2)
    else:
        result1 = a1.union(a2)

    if a2_operator == 'and':
        result = result1.intersection(a3)
    else:
        result = result1.union(a3)

    return result

# The below code is to add a null into the table. 
#     if len(result) == 0:
#         return np.nan
#     return list(result)


from itertools import chain
#a1 = c3e.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_x, row.e2_entity_x, row.not_x), axis=1)
a1 = qadb1.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_x, row.e2_entity_x, row.not_x), axis=1)
filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
flatten1  = [filter_function(val) for val in a1]
qadb1['a1'] = flatten1



a2 = qadb1.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_y, row.e2_entity_y, row.not_y), axis=1)
filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
flatten2  = [filter_function(val) for val in a2] 
qadb1['a2'] = flatten2


a3 = qadb1.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation, row.e2_entity), axis=1)
filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
flatten3  = [filter_function(val) for val in a3] 
qadb1['a3'] = flatten3

#c3e['fa'] = c3e.apply(lambda row: compute_logical_relation(row.a1, row.combine_x,  row.a2, row.combine_y, row.a3), axis=1)
qadb1['fa'] = qadb1.apply(lambda row: compute_logical_relation(row.a1, row.combine_x,  row.a2, row.combine_y, row.a3), axis=1)

print('Answer:')
# c3e.head(500)
qadb1.head(50)

In [ ]:
# c3e
len(qadb1)

In [ ]:
logic_3_questions = 'Count how many ' + unique_concat(
    c3e.e1_classes.str.cat(sep=' ', others=[c3e['not_x'], c3e.r1_relation_x, c3e.e2_entity_x, qadb1['a1'].astype(str), c3e['combine_x'], 
                                            c3e['not_y'], c3e.r1_relation_y, c3e.e2_entity_y, qadb1['a2'].astype(str), c3e['combine_y'], 
                                            c3e.r1_relation, c3e.e2_entity, qadb1['a3'].astype(str), 
                                            qadb1['fa'].astype(str)]),
)
pprint(f'{len(logic_3_questions)} logic_3 questions in total')
logic_3_questions.tolist()[:500]

In [ ]:
# logic_3_qa = 'Count how many ' + unique_concat(
#     c3e.e1_classes.str.cat(sep=' ', others=[c3e['not_x'], c3e.r1_relation_x, c3e.e2_entity_x, c3e['fa'], c3e['combine_x'], c3e['not_y'], c3e.r1_relation_y, c3e.e2_entity_y, c3e['fa'], c3e['combine_y'], c3e.r1_relation, c3e.e2_entity, c3e['fa']]),
# )

logic_3_qa = 'Count how many ' + unique_concat(
    c3e.e1_classes.str.cat(sep=' ', others=[c3e['fa'].astype(str)]),
)
logic_3_qa

In [ ]:
# Testing Code
# import rdflib
# import sparql
# from SPARQLWrapper import SPARQLWrapper, JSON
# from rdflib import Graph, Literal, RDF, URIRef
# from rdflib.namespace import FOAF, XSD
# from equal_iri import make_equal_iri
# onto = get_ontology("http://test.org/onto.owl")#.load()


world = default_world.as_rdflib_graph()

query = "PREFIX onto: <" + onto.base_iri + "> SELECT ?p ?o WHERE {onto:tomato ?p ?o}"
r = list(world.query_owlready(query))
print(r)

print('OK1')
r2 = list(default_world.sparql("""
    SELECT (COUNT(?x) as ?nb)
    { ?x a owl:Class . }
    """))
print(r2)
print('ok2')

r3 = list(default_world.sparql("""
    SELECT ?x
    { ?x a owl:ObjectProperty . }
    """))
print(r3)

In [ ]:
sorted(c3e.columns)

In [ ]:
query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s ?p ?o 
WHERE { 
    ?s ?p ?o
}
"""   
list(graph.query_owlready(query))

In [ ]:
def get_data():
    class_names = list(default_world.sparql("""
        SELECT DISTINCT ?x WHERE{ 
            ?x a owl:Class . }
        """))
    print('class_names:', class_names)
    
    obj_property_names = list(default_world.sparql("""
        SELECT DISTINCT ?x WHERE{ 
            ?x a owl:ObjectProperty . }
        """))
    print('obj_property_names:', obj_property_names)
    
    individual_names = list(default_world.sparql("""
        SELECT DISTINCT ?x WHERE{ 
            ?x a owl:NamedIndividual . }
        """))
    print('individual_names:', individual_names)
    
get_data()

In [ ]:
query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s 
WHERE {
    ?s rdf:type ?type. ?type rdfs:subClassOf+ onto:Food .
    FILTER NOT EXISTS {?s onto:has_for_taste onto:sweet .}
    FILTER NOT EXISTS {?s rdfs:subClassOf ?t .}
}
"""   
list(graph.query_owlready(query))

In [ ]:
# FYI: the below is testing code. 
from itertools import chain
a1 = c3e.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_x, row.e2_entity_x, row.not_x), axis=1)
filter_fun = lambda item: item if isinstance(item, str) else item[0]
flatten1  = [filter_fun(val) for val in a1]
flatten2  = [filter_fun(val) for val in a1]
flatten3  = [filter_fun(val) for val in a1]

an1 = pd.Series(flatten1) 
an2 = pd.Series(flatten2)
an3 = pd.Series(flatten3)
cat = pd.concat([an1, an2, an3], axis=1)
cat