In [13]:
# JY, - Import dictionaries
# Import OWLReady
import owlready2
from owlready2 import *
from itertools import chain
import rdflib
#import sparql
from SPARQLWrapper import SPARQLWrapper, JSON
from rdflib import Graph, Literal, RDF, URIRef
from rdflib.namespace import FOAF, XSD
graph = default_world.as_rdflib_graph()

# Import Pandas, Numpy
import pandas as pd
from pprint import pprint
import numpy as np
import re
pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)


print('ok - import dictionaries')

ok - import dictionaries

In [15]:
import owlready2
from owlready2 import *
from itertools import chain
import rdflib
#import sparql
from SPARQLWrapper import SPARQLWrapper, JSON
from rdflib import Graph, Literal, RDF, URIRef
from rdflib.namespace import FOAF, XSD
graph = default_world.as_rdflib_graph()

onto = get_ontology("http://test.org/onto.owl")

with onto:
     
    class Food(Thing):
        pass
    class Vegetable(Food):
        pass
    class Fruit(Food):
        pass
    class Meat(Food):
        pass  
    class Fish(Food):
        pass
    class Grain(Food):
        pass
    class Dairy(Food):
        pass    
    
    class Tool(Thing):
        pass
    class Kitchenware(Tool):
        pass
    class Tableware(Tool):
        pass

    
    class Taste(Thing):
        pass
    class Country(Thing):
        pass
    class Color(Thing):
        pass   
    class Nutrition(Thing):
        pass  
    class Function(Thing):
        pass 
    class Shape(Thing):
        pass 
    
     
    class original_from(ObjectProperty):
        domain    = [Food]
        range     = [Country]
    class has_taste(ObjectProperty):
        domain    = [Food]
        range     = [Taste]
    class has_child_food(ObjectProperty):
        domain = [Food]
        range  = [Food]
    class has_color(ObjectProperty):
        domain    = [Food]
        range     = [Color]    
    class has_nutrition(ObjectProperty):
        domain    = [Food]
        range     = [Nutrition] 
        
    class has_function(ObjectProperty):
        domain    = [Tool]
        range     = [Function] 
    class has_shape(ObjectProperty):
        domain    = [Tool]
        range     = [Shape] 
    class has_sub_function(ObjectProperty):
        domain = [Tool]
        range  = [Tool]
        
           
        
    juicy = Taste('juicy')
    sweet = Taste('sweet')
    sour = Taste('sour')
    bitter = Taste('bitter')
    salty = Taste('salty')
    spicy = Taste('spicy')
    fruity = Taste('fruity')
    grassy = Taste('grassy')
    woody = Taste('woody')
    pungent = Taste('pungent')
    meaty = Taste('meaty')
    fishy = Taste('fishy')
    tangy = Taste('tangy')
    
    
    australia = Country('australia')
    new_zealand = Country('new_zealand')
    china = Country('china')
    canada = Country('canada')
    mexica = Country('mexica')
    america = Country('america')
    europe = Country('europe')
    asia = Country('asia')
    egypt = Country('egypt')
    india = Country('india')
    
    green = Color('green')
    red = Color('red')
    yellow = Color('yellow')
    white = Color('white')
    purple = Color('purple')
    
    protein = Nutrition('protein')
    fat = Nutrition('fat')
    
    fry = Function('fry')
    boil = Function('boil')
    drinking = Function('drinking')
    poking = Function('poking')
    stabbing = Function('stabbing')
    cutting = Function('cutting')
    servefood = Function('servefood')
    
    
    long = Shape('long')
    round = Shape('round')
    circular = Shape('circular')
    solid = Shape('solid')
    liquid = Shape('liquid')
    

    tomato = Vegetable("tomato", has_shape=[round], has_color=[red], has_taste=[juicy, sweet], original_from=[america])
    broccoli = Vegetable("broccoli", has_color=[green], has_taste=[juicy, sweet])
    bean = Vegetable("bean", has_color=[green], original_from=[australia, new_zealand]) 
    chilli = Vegetable("chilli", has_taste=[spicy], has_color=[green, red, yellow], original_from=[america])
    carrot = Vegetable("carrot", has_shape=[long], has_color=[yellow], has_taste=[woody])
    capsicum = Vegetable("capsicum", has_taste=[spicy], has_color=[green, red, yellow], original_from=[america])
    cucumber = Vegetable("cucumber", has_shape=[long], has_color=[green], has_taste=[juicy], original_from=[india])
    squash = Vegetable("squash", has_shape=[long], has_color=[green])
    cabbage = Vegetable("cabbage", has_taste=[sweet])
    ginger = Vegetable("ginger", has_taste=[pungent], original_from=[asia])
    garlic = Vegetable("garlic", has_color=[white], has_taste=[pungent], original_from=[asia])
    leek = Vegetable("leek", has_taste=[pungent], original_from=[australia, new_zealand])
    lettuce = Vegetable("lettuce", has_shape=[round], has_color=[green], original_from=[egypt])
    mushroom = Vegetable("mushroom", has_color=[white])
    onion = Vegetable("onion", has_shape=[round], has_color=[yellow, purple], has_taste=[pungent], original_from=[australia, new_zealand])
    potato = Vegetable("potato", has_taste=[sweet], original_from=[america])
    pumpkin = Vegetable("pumpkin", has_taste=[sweet],has_color=[yellow], original_from=[mexica])
    parsley = Vegetable("parsley", has_color=[green], original_from=[mexica])
    green_onion = Vegetable("green_onion", has_shape=[long], has_color=[white, green], has_taste=[pungent], original_from=[australia, new_zealand]) 
    eggplant= Vegetable("eggplant", has_shape=[long], has_color=[purple], has_taste=[sweet] )
    asparagus= Vegetable("asparagus", has_shape=[long], has_color=[green], has_taste=[sweet])
    pepper = Vegetable("pepper", has_color=[green, red, yellow], has_taste=[spicy])
    
    
    orange = Fruit("orange", has_color=[yellow], has_for_taste=[sweet, sour, juicy])
    apple = Fruit("apple", has_color=[green, red], has_for_taste=[sweet], original_from=[america])
    banana = Fruit("banana", has_shape=[long], has_color=[yellow], has_for_taste=[sweet])
    lemon = Fruit("lemon", has_color=[yellow], has_taste=[sweet, sour, juicy], original_from=[china])
    plum = Fruit("plum", has_color=[purple], has_taste=[sweet, sour, juicy], original_from=[china])
    lime = Fruit("lime", has_color=[green], has_taste=[sweet, sour, juicy], original_from=[china])

    
    melon = Fruit("melon", has_taste=[sweet])
    kiwifruit = Fruit("kiwifruit", has_shape=[round], has_color=[green], original_from=[new_zealand])
    strawberry = Fruit("strawberry", has_color=[red], has_taste=[sweet])
    raspberry = Fruit("raspberry", has_color=[red], has_taste=[sweet])
    pineapple = Fruit("pineapple", has_color=[yellow], has_taste=[sweet])
    mandarin = Fruit("mandarin", has_color=[yellow], has_taste=[sweet, juicy])
    avocado = Fruit("avocado", has_shape=[round], has_color=[green], has_taste=[grassy], original_from=[america])
    watermelon = Fruit("watermelon", has_color=[green, red], has_taste=[sweet, juicy])
    grape = Fruit("grape", has_color=[green, red], has_taste=[juicy, sweet])
    cherry = Fruit("cherry", has_color=[red], has_taste=[sweet])
    pear = Fruit("pear", has_shape=[round], has_color=[green, yellow], has_taste=[juicy, sweet])
   

    green_apple = Fruit("green_apple", has_color=[green], has_taste=[sweet], original_from=[america])
    red_apple = Fruit("red_apple", has_color=[red], has_taste=[sweet], original_from=[america])

    apple = Fruit("apple", has_child_food=[red_apple])
    apple = Fruit("apple", has_child_food=[green_apple])
    
    beaf = Meat("beaf", has_taste=[meaty], has_color=[red])
    chicken = Meat("chicken", has_taste=[meaty], has_color=[white])
    lamb = Meat("lamb", has_taste=[meaty], has_color=[red])
    pork = Meat("pork", has_taste=[meaty], has_color=[red])
    
    salmon = Fish("salmon", has_taste=[fishy], has_nutrition=[fat, protein])
    shrimp = Fish("shrimp", has_taste=[fishy], has_nutrition=[protein])
    squid = Fish("squid", has_taste=[fishy], has_nutrition=[protein])
    fillet = Fish("fillet", has_taste=[fishy], has_nutrition=[fat, protein])
    
    egg = Dairy("egg", has_nutrition=[protein])
    yoghurt = Dairy("yoghurt", has_taste=[sweet], has_nutrition=[protein])
    cheese = Dairy("cheese", has_nutrition=[protein, fat])
    milk = Dairy("milk", has_nutrition=[protein, fat], has_taste = [sweet])
    
    rice = Grain("rice", has_shape=[round, long])
    noodle = Grain("noodle", has_shape=[long])
    pasta = Grain("pasta", has_shape=[round, long])
    bread = Grain("bread", has_shape=[long], has_taste=[tangy])
    corn = Grain("corn", has_color=[yellow], original_from=[america])
    
    
    pan = Kitchenware('pan', has_function=[fry], has_color=[red])   
    pot = Kitchenware('pot', has_function=[boil], has_color=[red])  
    chopping_board = Kitchenware('chopping_board', has_function=[cutting])  

    spoon = Tableware('spoon', has_function=[drinking])
    fork = Tableware('fork', has_function=[poking, stabbing])
    knife = Tableware('knife', has_function=[cutting])
    plate = Tableware('plate', has_function=[servefood], has_shape=[circular])

    plate = Tableware('plate', has_function=[servefood], has_shape=[circular], has_sub_function=[chopping_board])

  
    print('ok-onto1')

ok-onto1

In [19]:
print(list(onto.individuals()))

[onto.juicy, onto.sweet, onto.sour, onto.bitter, onto.salty, onto.spicy, onto.fruity, onto.grassy, onto.woody, onto.pungent, onto.meaty, onto.fishy, onto.tangy, onto.australia, onto.new_zealand, onto.china, onto.canada, onto.mexica, onto.america, onto.europe, onto.asia, onto.egypt, onto.india, onto.green, onto.red, onto.yellow, onto.white, onto.purple, onto.protein, onto.fat, onto.fry, onto.boil, onto.drinking, onto.poking, onto.stabbing, onto.cutting, onto.servefood, onto.long, onto.round, onto.circular, onto.solid, onto.liquid, onto.tomato, onto.broccoli, onto.chilli, onto.carrot, onto.capsicum, onto.cucumber, onto.cabbage, onto.garlic, onto.lettuce, onto.mushroom, onto.onion, onto.potato, onto.pumpkin, onto.eggplant, onto.pepper, onto.orange, onto.apple, onto.banana, onto.lemon, onto.plum, onto.lime, onto.kiwifruit, onto.avocado, onto.pear, onto.green_apple, onto.red_apple, onto.beaf, onto.chicken, onto.lamb, onto.pork, onto.salmon, onto.shrimp, onto.squid, onto.fillet, onto.egg, onto.yoghurt, onto.cheese, onto.milk, onto.rice, onto.noodle, onto.pasta, onto.bread, onto.corn, onto.pan, onto.pot, onto.chopping_board, onto.spoon, onto.fork, onto.knife, onto.plate]

In [25]:
# JY, - First part - Unroll ontology 
# --- First method set, recursive methods to turn objects and relations into some sort of consistent format ---
# --- Output: list of tuples to represent the entity and all its relationships including a depth tracker ---

# recursive method to get class hierarchy
def get_types_hierarchy(x):
    if issubclass(x, Thing):
        # to filter out Thing's, uncomment below
        # if x is not Thing:
        return [x, *get_types_hierarchy(x.__bases__[0])]
    return []

# gets a tuple representing a relationship (recursive with get_object_pairs)
def get_relation_pairs(o, depth=1):
    if depth>=10:
        print('Warning, depth of 10 hit, check for cycles')
        return []
    return [('relation', p, get_object_pairs(getattr(o, p._name), depth=depth+1)) 
    for p in o.get_properties() if ObjectPropertyClass]

# gets a tuple representing a pair of objects (recursive with get_relation_pairs), [0, 1, 2, 3] = [entity, types, x, relation_pairs]
def get_object_pairs(objects, limit_domain=[], depth=1):
    return [(
        'entity',
        get_types_hierarchy(type(x)),
        x,
        get_relation_pairs(x, depth))
        for x in objects 
        if len(limit_domain)==0 or any([isinstance(x, y) for y in limit_domain])]


# --- JY - Get ready to build a table from unrolled ontology. 
# --- Second method set, recursive method sets to unroll the hierarchy, ---
# --- Output: collapsed list of dicts with each level of entity/relationship numbered as e1/r1, e2/r2 etc. ---

# works with dictify to flatten out the hierarchy to a one-dict per entity/relationship combination including recurse
def dict_collapse(e, depth=1):
    has_relationships = len(e[3])>0
    if has_relationships:
        return [{f'e{depth}': e[0:3], f'r{depth}': r[0:2], 'n': dictify(r[2], depth+1)} for r in e[3]]
    else:
        return [{f'e{depth}': e[0:3], f'r{depth}': None, 'n': []}]

# removes the "n" column which is used to indicate another level of recursion
def drop_n(d):
    return {k:v for k,v in d.items() if k!='n'}

# helper to flatten nested lists, put two sublists into a combined list. 
def flatten(l):
    return list(chain.from_iterable(l))

# Removes a single level of recursion then calls itself again
def flatten_dicts(dict_list):
    # handle case of no next level and case of having a next level then recurse
    recursed_set = [{**drop_n(e), **n} for e in dict_list for n in e['n']]
    if any(['n' in e for e in recursed_set]):
        recursed_set = flatten_dicts(recursed_set)
    return recursed_set + \
        [drop_n(e) for e in dict_list if len(e['n'])==0]

# controller method to orchestrate the other 2
def dictify(object_pairs, depth=1):
    if depth >= 10:
        print('Warning, depth of 10 hit, check for cycles')
        return []
    collapsed_dicts = flatten([dict_collapse(e, depth) for e in object_pairs])
    return flatten_dicts(collapsed_dicts)

# --- JY Build the table 
# --- Third method set, no more recursion, these methods are just helpful to coerce to a table-like format, could easily write your own methods instead :) ---
# --- Output: dictionary with an entity or list of classes per column making it easier to filter and work with ---

# convert the whole ontology to a table format
from collections import ChainMap
def tablify(object_tuple_dict):
    def generate_entity_dict(k, v):
        if v is None:
            return {}
        elif v[0]=='entity':
            return {f'{k}_classes': v[1], f'{k}_entity': v[2]}
        else:
            return {f'{k}_relation': v[1]}
        
    return [dict(ChainMap(*[generate_entity_dict(k,v) for k,v in x.items()])) for x in object_tuple_dict]

# convert all the entities and classes to strings for easy sentence generation
def stringify_table(dict_table_format):
    return [{k: [x.name for x in v] if isinstance(v, list) else v._name for k,v in x.items()} for x in dict_table_format]

print('ok-Unroll Ontology Functions')
# --- Actually using the above methods! ---

ok-Unroll Ontology Functions

In [27]:
# these 2 do the main bulk of the work, you could happily write a function to process object_tuple_dict directly
object_pairs = get_object_pairs(onto.individuals(), [onto.Food])
object_tuple_dict = dictify(object_pairs)

# or use these to get a table sort of format that we can do further processing on to generate questions!
dict_table_format = tablify(object_tuple_dict)
string_table = stringify_table(dict_table_format)

table_cols_threelevels = ['e1_classes', 'e1_entity', 'r1_relation', 'e2_classes', 'e2_entity', 'r2_relation', 'e3_classes', 'e3_entity']

string_df = pd.DataFrame(string_table)[table_cols_threelevels]
print('Table: string_df, Onto: Food')
string_df[0:10]

Table: string_df, Onto: Food

,e1_classes,e1_entity,r1_relation,e2_classes,e2_entity,r2_relation,e3_classes,e3_entity
0,"[Vegetable, Food, Thing]",tomato,has_color,"[Color, Thing]",red,NaN,NaN,NaN
1,"[Vegetable, Food, Thing]",tomato,original_from,"[Country, Thing]",america,NaN,NaN,NaN
2,"[Vegetable, Food, Thing]",tomato,has_shape,"[Shape, Thing]",round,NaN,NaN,NaN
3,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",juicy,NaN,NaN,NaN
4,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",sweet,NaN,NaN,NaN
5,"[Vegetable, Food, Thing]",broccoli,has_color,"[Color, Thing]",green,NaN,NaN,NaN
6,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",juicy,NaN,NaN,NaN
7,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",sweet,NaN,NaN,NaN
8,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",green,NaN,NaN,NaN
9,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",red,NaN,NaN,NaN

In [30]:
# these 2 do the main bulk of the work, you could happily write a function to process object_tuple_dict directly
object_pairs = get_object_pairs(onto.individuals(), [onto.Food])
object_tuple_dict = dictify(object_pairs)

# or use these to get a table sort of format that we can do further processing on to generate questions!
dict_table_format = tablify(object_tuple_dict)
string_table = stringify_table(dict_table_format)

# can make an entity df with the individuals/classes if you want to access properties and inspect them, etc.
# entity_df = pd.DataFrame(dict_table_format)
# entity_df.explode('e2_classes').explode('e1_classes')
table_cols_threelevels = ['e1_classes', 'e1_entity', 'r1_relation', 'e2_classes', 'e2_entity', 'r2_relation', 'e3_classes', 'e3_entity']

# or can make a string df use the "string_table" for sentence generation purposes
string_df1 = pd.DataFrame(string_table)[table_cols_threelevels].fillna('').query("r1_relation!=''")
print('print ok-Table0: string_df1. fillna ''and r1_relation is not null')
string_df1

print ok-Table0: string_df1. fillna and r1_relation is not null

,e1_classes,e1_entity,r1_relation,e2_classes,e2_entity,r2_relation,e3_classes,e3_entity
0,"[Vegetable, Food, Thing]",tomato,has_color,"[Color, Thing]",red,,,
1,"[Vegetable, Food, Thing]",tomato,original_from,"[Country, Thing]",america,,,
2,"[Vegetable, Food, Thing]",tomato,has_shape,"[Shape, Thing]",round,,,
3,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",juicy,,,
4,"[Vegetable, Food, Thing]",tomato,has_taste,"[Taste, Thing]",sweet,,,
5,"[Vegetable, Food, Thing]",broccoli,has_color,"[Color, Thing]",green,,,
6,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",juicy,,,
7,"[Vegetable, Food, Thing]",broccoli,has_taste,"[Taste, Thing]",sweet,,,
8,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",green,,,
9,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",red,,,
10,"[Vegetable, Food, Thing]",chilli,has_color,"[Color, Thing]",yellow,,,
11,"[Vegetable, Food, Thing]",chilli,original_from,"[Country, Thing]",america,,,
12,"[Vegetable, Food, Thing]",chilli,has_taste,"[Taste, Thing]",spicy,,,
13,"[Vegetable, Food, Thing]",carrot,has_color,"[Color, Thing]",yellow,,,
14,"[Vegetable, Food, Thing]",carrot,has_shape,"[Shape, Thing]",long,,,
15,"[Vegetable, Food, Thing]",carrot,has_taste,"[Taste, Thing]",woody,,,
16,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",green,,,
17,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",red,,,
18,"[Vegetable, Food, Thing]",capsicum,has_color,"[Color, Thing]",yellow,,,
19,"[Vegetable, Food, Thing]",capsicum,original_from,"[Country, Thing]",america,,,
20,"[Vegetable, Food, Thing]",capsicum,has_taste,"[Taste, Thing]",spicy,,,
21,"[Vegetable, Food, Thing]",cucumber,has_color,"[Color, Thing]",green,,,
22,"[Vegetable, Food, Thing]",cucumber,original_from,"[Country, Thing]",india,,,
23,"[Vegetable, Food, Thing]",cucumber,has_shape,"[Shape, Thing]",long,,,
24,"[Vegetable, Food, Thing]",cucumber,has_taste,"[Taste, Thing]",juicy,,,
25,"[Vegetable, Food, Thing]",cabbage,has_taste,"[Taste, Thing]",sweet,,,
26,"[Vegetable, Food, Thing]",garlic,has_color,"[Color, Thing]",white,,,
27,"[Vegetable, Food, Thing]",garlic,original_from,"[Country, Thing]",asia,,,
28,"[Vegetable, Food, Thing]",garlic,has_taste,"[Taste, Thing]",pungent,,,
29,"[Vegetable, Food, Thing]",lettuce,has_color,"[Color, Thing]",green,,,
30,"[Vegetable, Food, Thing]",lettuce,original_from,"[Country, Thing]",egypt,,,
31,"[Vegetable, Food, Thing]",lettuce,has_shape,"[Shape, Thing]",round,,,
32,"[Vegetable, Food, Thing]",mushroom,has_color,"[Color, Thing]",white,,,
33,"[Vegetable, Food, Thing]",onion,has_color,"[Color, Thing]",yellow,,,
34,"[Vegetable, Food, Thing]",onion,has_color,"[Color, Thing]",purple,,,
35,"[Vegetable, Food, Thing]",onion,original_from,"[Country, Thing]",australia,,,
36,"[Vegetable, Food, Thing]",onion,original_from,"[Country, Thing]",new_zealand,,,
37,"[Vegetable, Food, Thing]",onion,has_shape,"[Shape, Thing]",round,,,
38,"[Vegetable, Food, Thing]",onion,has_taste,"[Taste, Thing]",pungent,,,
39,"[Vegetable, Food, Thing]",potato,original_from,"[Country, Thing]",america,,,
40,"[Vegetable, Food, Thing]",potato,has_taste,"[Taste, Thing]",sweet,,,
41,"[Vegetable, Food, Thing]",pumpkin,has_color,"[Color, Thing]",yellow,,,
42,"[Vegetable, Food, Thing]",pumpkin,original_from,"[Country, Thing]",mexica,,,
43,"[Vegetable, Food, Thing]",pumpkin,has_taste,"[Taste, Thing]",sweet,,,
44,"[Vegetable, Food, Thing]",eggplant,has_color,"[Color, Thing]",purple,,,
45,"[Vegetable, Food, Thing]",eggplant,has_shape,"[Shape, Thing]",long,,,
46,"[Vegetable, Food, Thing]",eggplant,has_taste,"[Taste, Thing]",sweet,,,
47,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",green,,,
48,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",red,,,
49,"[Vegetable, Food, Thing]",pepper,has_color,"[Color, Thing]",yellow,,,
50,"[Vegetable, Food, Thing]",pepper,has_taste,"[Taste, Thing]",spicy,,,
51,"[Fruit, Food, Thing]",orange,has_color,"[Color, Thing]",yellow,,,
52,"[Fruit, Food, Thing]",apple,has_color,"[Color, Thing]",green,,,
53,"[Fruit, Food, Thing]",apple,has_color,"[Color, Thing]",red,,,
54,"[Fruit, Food, Thing]",apple,original_from,"[Country, Thing]",america,,,
55,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,has_color,"[Color, Thing]",green
56,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,original_from,"[Country, Thing]",america
57,"[Fruit, Food, Thing]",apple,has_child_food,"[Fruit, Food, Thing]",green_apple,has_taste,"[Taste, Thing]",sweet
58,"[Fruit, Food, Thing]",banana,has_color,"[Color, Thing]",yellow,,,
59,"[Fruit, Food, Thing]",banana,has_shape,"[Shape, Thing]",long,,,
60,"[Fruit, Food, Thing]",lemon,has_color,"[Color, Thing]",yellow,,,
61,"[Fruit, Food, Thing]",lemon,original_from,"[Country, Thing]",china,,,
62,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",sweet,,,
63,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",sour,,,
64,"[Fruit, Food, Thing]",lemon,has_taste,"[Taste, Thing]",juicy,,,
65,"[Fruit, Food, Thing]",plum,has_color,"[Color, Thing]",purple,,,
66,"[Fruit, Food, Thing]",plum,original_from,"[Country, Thing]",china,,,
67,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",sweet,,,
68,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",sour,,,
69,"[Fruit, Food, Thing]",plum,has_taste,"[Taste, Thing]",juicy,,,
70,"[Fruit, Food, Thing]",lime,has_color,"[Color, Thing]",green,,,
71,"[Fruit, Food, Thing]",lime,original_from,"[Country, Thing]",china,,,
72,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",sweet,,,
73,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",sour,,,
74,"[Fruit, Food, Thing]",lime,has_taste,"[Taste, Thing]",juicy,,,
75,"[Fruit, Food, Thing]",kiwifruit,has_color,"[Color, Thing]",green,,,
76,"[Fruit, Food, Thing]",kiwifruit,original_from,"[Country, Thing]",new_zealand,,,
77,"[Fruit, Food, Thing]",kiwifruit,has_shape,"[Shape, Thing]",round,,,
78,"[Fruit, Food, Thing]",avocado,has_color,"[Color, Thing]",green,,,
79,"[Fruit, Food, Thing]",avocado,original_from,"[Country, Thing]",america,,,
80,"[Fruit, Food, Thing]",avocado,has_shape,"[Shape, Thing]",round,,,
81,"[Fruit, Food, Thing]",avocado,has_taste,"[Taste, Thing]",grassy,,,
82,"[Fruit, Food, Thing]",pear,has_color,"[Color, Thing]",green,,,
83,"[Fruit, Food, Thing]",pear,has_color,"[Color, Thing]",yellow,,,
84,"[Fruit, Food, Thing]",pear,has_shape,"[Shape, Thing]",round,,,
85,"[Fruit, Food, Thing]",pear,has_taste,"[Taste, Thing]",juicy,,,
86,"[Fruit, Food, Thing]",pear,has_taste,"[Taste, Thing]",sweet,,,
87,"[Fruit, Food, Thing]",green_apple,has_color,"[Color, Thing]",green,,,
88,"[Fruit, Food, Thing]",green_apple,original_from,"[Country, Thing]",america,,,
89,"[Fruit, Food, Thing]",green_apple,has_taste,"[Taste, Thing]",sweet,,,
90,"[Fruit, Food, Thing]",red_apple,has_color,"[Color, Thing]",red,,,
91,"[Fruit, Food, Thing]",red_apple,original_from,"[Country, Thing]",america,,,
92,"[Fruit, Food, Thing]",red_apple,has_taste,"[Taste, Thing]",sweet,,,
93,"[Meat, Food, Thing]",beaf,has_color,"[Color, Thing]",red,,,
94,"[Meat, Food, Thing]",beaf,has_taste,"[Taste, Thing]",meaty,,,
95,"[Meat, Food, Thing]",chicken,has_color,"[Color, Thing]",white,,,
96,"[Meat, Food, Thing]",chicken,has_taste,"[Taste, Thing]",meaty,,,
97,"[Meat, Food, Thing]",lamb,has_color,"[Color, Thing]",red,,,
98,"[Meat, Food, Thing]",lamb,has_taste,"[Taste, Thing]",meaty,,,
99,"[Meat, Food, Thing]",pork,has_color,"[Color, Thing]",red,,,
100,"[Meat, Food, Thing]",pork,has_taste,"[Taste, Thing]",meaty,,,
101,"[Fish, Food, Thing]",salmon,has_nutrition,"[Nutrition, Thing]",fat,,,
102,"[Fish, Food, Thing]",salmon,has_nutrition,"[Nutrition, Thing]",protein,,,
103,"[Fish, Food, Thing]",salmon,has_taste,"[Taste, Thing]",fishy,,,
104,"[Fish, Food, Thing]",shrimp,has_nutrition,"[Nutrition, Thing]",protein,,,
105,"[Fish, Food, Thing]",shrimp,has_taste,"[Taste, Thing]",fishy,,,
106,"[Fish, Food, Thing]",squid,has_nutrition,"[Nutrition, Thing]",protein,,,
107,"[Fish, Food, Thing]",squid,has_taste,"[Taste, Thing]",fishy,,,
108,"[Fish, Food, Thing]",fillet,has_nutrition,"[Nutrition, Thing]",fat,,,
109,"[Fish, Food, Thing]",fillet,has_nutrition,"[Nutrition, Thing]",protein,,,
110,"[Fish, Food, Thing]",fillet,has_taste,"[Taste, Thing]",fishy,,,
111,"[Dairy, Food, Thing]",egg,has_nutrition,"[Nutrition, Thing]",protein,,,
112,"[Dairy, Food, Thing]",yoghurt,has_nutrition,"[Nutrition, Thing]",protein,,,
113,"[Dairy, Food, Thing]",yoghurt,has_taste,"[Taste, Thing]",sweet,,,
114,"[Dairy, Food, Thing]",cheese,has_nutrition,"[Nutrition, Thing]",protein,,,
115,"[Dairy, Food, Thing]",cheese,has_nutrition,"[Nutrition, Thing]",fat,,,
116,"[Dairy, Food, Thing]",milk,has_nutrition,"[Nutrition, Thing]",protein,,,
117,"[Dairy, Food, Thing]",milk,has_nutrition,"[Nutrition, Thing]",fat,,,
118,"[Dairy, Food, Thing]",milk,has_taste,"[Taste, Thing]",sweet,,,
119,"[Grain, Food, Thing]",rice,has_shape,"[Shape, Thing]",round,,,
120,"[Grain, Food, Thing]",rice,has_shape,"[Shape, Thing]",long,,,
121,"[Grain, Food, Thing]",noodle,has_shape,"[Shape, Thing]",long,,,
122,"[Grain, Food, Thing]",pasta,has_shape,"[Shape, Thing]",round,,,
123,"[Grain, Food, Thing]",pasta,has_shape,"[Shape, Thing]",long,,,
124,"[Grain, Food, Thing]",bread,has_shape,"[Shape, Thing]",long,,,
125,"[Grain, Food, Thing]",bread,has_taste,"[Taste, Thing]",tangy,,,
126,"[Grain, Food, Thing]",corn,has_color,"[Color, Thing]",yellow,,,
127,"[Grain, Food, Thing]",corn,original_from,"[Country, Thing]",america,,,

In [127]:
# Print some test questions

exp = string_df1.explode('e2_classes').explode('e1_classes').drop(columns=['e1_entity']).drop_duplicates(subset=[
        'e1_classes',
        'r1_relation',
        'e2_classes',
        'e2_entity'
    ]).reset_index(drop=True)

exp

,e1_classes,r1_relation,e2_classes,e2_entity,r2_relation,e3_classes,e3_entity
0,Vegetable,has_color,Color,red,,,
1,Food,has_color,Color,red,,,
2,Thing,has_color,Color,red,,,
3,Vegetable,has_color,Thing,red,,,
4,Food,has_color,Thing,red,,,
5,Thing,has_color,Thing,red,,,
6,Vegetable,original_from,Country,america,,,
7,Food,original_from,Country,america,,,
8,Thing,original_from,Country,america,,,
9,Vegetable,original_from,Thing,america,,,
10,Food,original_from,Thing,america,,,
11,Thing,original_from,Thing,america,,,
12,Vegetable,has_shape,Shape,round,,,
13,Food,has_shape,Shape,round,,,
14,Thing,has_shape,Shape,round,,,
15,Vegetable,has_shape,Thing,round,,,
16,Food,has_shape,Thing,round,,,
17,Thing,has_shape,Thing,round,,,
18,Vegetable,has_taste,Taste,juicy,,,
19,Food,has_taste,Taste,juicy,,,
20,Thing,has_taste,Taste,juicy,,,
21,Vegetable,has_taste,Thing,juicy,,,
22,Food,has_taste,Thing,juicy,,,
23,Thing,has_taste,Thing,juicy,,,
24,Vegetable,has_taste,Taste,sweet,,,
25,Food,has_taste,Taste,sweet,,,
26,Thing,has_taste,Taste,sweet,,,
27,Vegetable,has_taste,Thing,sweet,,,
28,Food,has_taste,Thing,sweet,,,
29,Thing,has_taste,Thing,sweet,,,
30,Vegetable,has_color,Color,green,,,
31,Food,has_color,Color,green,,,
32,Thing,has_color,Color,green,,,
33,Vegetable,has_color,Thing,green,,,
34,Food,has_color,Thing,green,,,
35,Thing,has_color,Thing,green,,,
36,Vegetable,has_color,Color,yellow,,,
37,Food,has_color,Color,yellow,,,
38,Thing,has_color,Color,yellow,,,
39,Vegetable,has_color,Thing,yellow,,,
40,Food,has_color,Thing,yellow,,,
41,Thing,has_color,Thing,yellow,,,
42,Vegetable,has_taste,Taste,spicy,,,
43,Food,has_taste,Taste,spicy,,,
44,Thing,has_taste,Taste,spicy,,,
45,Vegetable,has_taste,Thing,spicy,,,
46,Food,has_taste,Thing,spicy,,,
47,Thing,has_taste,Thing,spicy,,,
48,Vegetable,has_shape,Shape,long,,,
49,Food,has_shape,Shape,long,,,
50,Thing,has_shape,Shape,long,,,
51,Vegetable,has_shape,Thing,long,,,
52,Food,has_shape,Thing,long,,,
53,Thing,has_shape,Thing,long,,,
54,Vegetable,has_taste,Taste,woody,,,
55,Food,has_taste,Taste,woody,,,
56,Thing,has_taste,Taste,woody,,,
57,Vegetable,has_taste,Thing,woody,,,
58,Food,has_taste,Thing,woody,,,
59,Thing,has_taste,Thing,woody,,,
60,Vegetable,original_from,Country,india,,,
61,Food,original_from,Country,india,,,
62,Thing,original_from,Country,india,,,
63,Vegetable,original_from,Thing,india,,,
64,Food,original_from,Thing,india,,,
65,Thing,original_from,Thing,india,,,
66,Vegetable,has_color,Color,white,,,
67,Food,has_color,Color,white,,,
68,Thing,has_color,Color,white,,,
69,Vegetable,has_color,Thing,white,,,
70,Food,has_color,Thing,white,,,
71,Thing,has_color,Thing,white,,,
72,Vegetable,original_from,Country,asia,,,
73,Food,original_from,Country,asia,,,
74,Thing,original_from,Country,asia,,,
75,Vegetable,original_from,Thing,asia,,,
76,Food,original_from,Thing,asia,,,
77,Thing,original_from,Thing,asia,,,
78,Vegetable,has_taste,Taste,pungent,,,
79,Food,has_taste,Taste,pungent,,,
80,Thing,has_taste,Taste,pungent,,,
81,Vegetable,has_taste,Thing,pungent,,,
82,Food,has_taste,Thing,pungent,,,
83,Thing,has_taste,Thing,pungent,,,
84,Vegetable,original_from,Country,egypt,,,
85,Food,original_from,Country,egypt,,,
86,Thing,original_from,Country,egypt,,,
87,Vegetable,original_from,Thing,egypt,,,
88,Food,original_from,Thing,egypt,,,
89,Thing,original_from,Thing,egypt,,,
90,Vegetable,has_color,Color,purple,,,
91,Food,has_color,Color,purple,,,
92,Thing,has_color,Color,purple,,,
93,Vegetable,has_color,Thing,purple,,,
94,Food,has_color,Thing,purple,,,
95,Thing,has_color,Thing,purple,,,
96,Vegetable,original_from,Country,australia,,,
97,Food,original_from,Country,australia,,,
98,Thing,original_from,Country,australia,,,
99,Vegetable,original_from,Thing,australia,,,
100,Food,original_from,Thing,australia,,,
101,Thing,original_from,Thing,australia,,,
102,Vegetable,original_from,Country,new_zealand,,,
103,Food,original_from,Country,new_zealand,,,
104,Thing,original_from,Country,new_zealand,,,
105,Vegetable,original_from,Thing,new_zealand,,,
106,Food,original_from,Thing,new_zealand,,,
107,Thing,original_from,Thing,new_zealand,,,
108,Vegetable,original_from,Country,mexica,,,
109,Food,original_from,Country,mexica,,,
110,Thing,original_from,Country,mexica,,,
111,Vegetable,original_from,Thing,mexica,,,
112,Food,original_from,Thing,mexica,,,
113,Thing,original_from,Thing,mexica,,,
114,Fruit,has_color,Color,yellow,,,
115,Fruit,has_color,Thing,yellow,,,
116,Fruit,has_color,Color,green,,,
117,Fruit,has_color,Thing,green,,,
118,Fruit,has_color,Color,red,,,
119,Fruit,has_color,Thing,red,,,
120,Fruit,original_from,Country,america,,,
121,Fruit,original_from,Thing,america,,,
122,Fruit,has_child_food,Fruit,green_apple,has_color,"[Color, Thing]",green
123,Food,has_child_food,Fruit,green_apple,has_color,"[Color, Thing]",green
124,Thing,has_child_food,Fruit,green_apple,has_color,"[Color, Thing]",green
125,Fruit,has_child_food,Food,green_apple,has_color,"[Color, Thing]",green
126,Food,has_child_food,Food,green_apple,has_color,"[Color, Thing]",green
127,Thing,has_child_food,Food,green_apple,has_color,"[Color, Thing]",green
128,Fruit,has_child_food,Thing,green_apple,has_color,"[Color, Thing]",green
129,Food,has_child_food,Thing,green_apple,has_color,"[Color, Thing]",green
130,Thing,has_child_food,Thing,green_apple,has_color,"[Color, Thing]",green
131,Fruit,has_shape,Shape,long,,,
132,Fruit,has_shape,Thing,long,,,
133,Fruit,original_from,Country,china,,,
134,Food,original_from,Country,china,,,
135,Thing,original_from,Country,china,,,
136,Fruit,original_from,Thing,china,,,
137,Food,original_from,Thing,china,,,
138,Thing,original_from,Thing,china,,,
139,Fruit,has_taste,Taste,sweet,,,
140,Fruit,has_taste,Thing,sweet,,,
141,Fruit,has_taste,Taste,sour,,,
142,Food,has_taste,Taste,sour,,,
143,Thing,has_taste,Taste,sour,,,
144,Fruit,has_taste,Thing,sour,,,
145,Food,has_taste,Thing,sour,,,
146,Thing,has_taste,Thing,sour,,,
147,Fruit,has_taste,Taste,juicy,,,
148,Fruit,has_taste,Thing,juicy,,,
149,Fruit,has_color,Color,purple,,,
150,Fruit,has_color,Thing,purple,,,
151,Fruit,original_from,Country,new_zealand,,,
152,Fruit,original_from,Thing,new_zealand,,,
153,Fruit,has_shape,Shape,round,,,
154,Fruit,has_shape,Thing,round,,,
155,Fruit,has_taste,Taste,grassy,,,
156,Food,has_taste,Taste,grassy,,,
157,Thing,has_taste,Taste,grassy,,,
158,Fruit,has_taste,Thing,grassy,,,
159,Food,has_taste,Thing,grassy,,,
160,Thing,has_taste,Thing,grassy,,,
161,Meat,has_color,Color,red,,,
162,Meat,has_color,Thing,red,,,
163,Meat,has_taste,Taste,meaty,,,
164,Food,has_taste,Taste,meaty,,,
165,Thing,has_taste,Taste,meaty,,,
166,Meat,has_taste,Thing,meaty,,,
167,Food,has_taste,Thing,meaty,,,
168,Thing,has_taste,Thing,meaty,,,
169,Meat,has_color,Color,white,,,
170,Meat,has_color,Thing,white,,,
171,Fish,has_nutrition,Nutrition,fat,,,
172,Food,has_nutrition,Nutrition,fat,,,
173,Thing,has_nutrition,Nutrition,fat,,,
174,Fish,has_nutrition,Thing,fat,,,
175,Food,has_nutrition,Thing,fat,,,
176,Thing,has_nutrition,Thing,fat,,,
177,Fish,has_nutrition,Nutrition,protein,,,
178,Food,has_nutrition,Nutrition,protein,,,
179,Thing,has_nutrition,Nutrition,protein,,,
180,Fish,has_nutrition,Thing,protein,,,
181,Food,has_nutrition,Thing,protein,,,
182,Thing,has_nutrition,Thing,protein,,,
183,Fish,has_taste,Taste,fishy,,,
184,Food,has_taste,Taste,fishy,,,
185,Thing,has_taste,Taste,fishy,,,
186,Fish,has_taste,Thing,fishy,,,
187,Food,has_taste,Thing,fishy,,,
188,Thing,has_taste,Thing,fishy,,,
189,Dairy,has_nutrition,Nutrition,protein,,,
190,Dairy,has_nutrition,Thing,protein,,,
191,Dairy,has_taste,Taste,sweet,,,
192,Dairy,has_taste,Thing,sweet,,,
193,Dairy,has_nutrition,Nutrition,fat,,,
194,Dairy,has_nutrition,Thing,fat,,,
195,Grain,has_shape,Shape,round,,,
196,Grain,has_shape,Thing,round,,,
197,Grain,has_shape,Shape,long,,,
198,Grain,has_shape,Thing,long,,,
199,Grain,has_taste,Taste,tangy,,,
200,Food,has_taste,Taste,tangy,,,
201,Thing,has_taste,Taste,tangy,,,
202,Grain,has_taste,Thing,tangy,,,
203,Food,has_taste,Thing,tangy,,,
204,Thing,has_taste,Thing,tangy,,,
205,Grain,has_color,Color,yellow,,,
206,Grain,has_color,Thing,yellow,,,
207,Grain,original_from,Country,america,,,
208,Grain,original_from,Thing,america,,,

In [109]:
# Generate some test questions with
questions = 'What ' + exp.e1_classes.str.cat(
    sep=' ',
    others=[
        exp.r1_relation,
        exp.e2_entity
    ]
)

pprint(f'{len(questions)} questions in total')
pprint(questions)

'209 questions in total'
0                  What Vegetable has_color red
1                       What Food has_color red
2                      What Thing has_color red
3                  What Vegetable has_color red
4                       What Food has_color red
5                      What Thing has_color red
6          What Vegetable original_from america
7               What Food original_from america
8              What Thing original_from america
9          What Vegetable original_from america
10              What Food original_from america
11             What Thing original_from america
12               What Vegetable has_shape round
13                    What Food has_shape round
14                   What Thing has_shape round
15               What Vegetable has_shape round
16                    What Food has_shape round
17                   What Thing has_shape round
18               What Vegetable has_taste juicy
19                    What Food has_taste juicy
20                   What Thing has_taste juicy
21               What Vegetable has_taste juicy
22                    What Food has_taste juicy
23                   What Thing has_taste juicy
24               What Vegetable has_taste sweet
25                    What Food has_taste sweet
26                   What Thing has_taste sweet
27               What Vegetable has_taste sweet
28                    What Food has_taste sweet
29                   What Thing has_taste sweet
30               What Vegetable has_color green
31                    What Food has_color green
32                   What Thing has_color green
33               What Vegetable has_color green
34                    What Food has_color green
35                   What Thing has_color green
36              What Vegetable has_color yellow
37                   What Food has_color yellow
38                  What Thing has_color yellow
39              What Vegetable has_color yellow
40                   What Food has_color yellow
41                  What Thing has_color yellow
42               What Vegetable has_taste spicy
43                    What Food has_taste spicy
44                   What Thing has_taste spicy
45               What Vegetable has_taste spicy
46                    What Food has_taste spicy
47                   What Thing has_taste spicy
48                What Vegetable has_shape long
49                     What Food has_shape long
50                    What Thing has_shape long
51                What Vegetable has_shape long
52                     What Food has_shape long
53                    What Thing has_shape long
54               What Vegetable has_taste woody
55                    What Food has_taste woody
56                   What Thing has_taste woody
57               What Vegetable has_taste woody
58                    What Food has_taste woody
59                   What Thing has_taste woody
60           What Vegetable original_from india
61                What Food original_from india
62               What Thing original_from india
63           What Vegetable original_from india
64                What Food original_from india
65               What Thing original_from india
66               What Vegetable has_color white
67                    What Food has_color white
68                   What Thing has_color white
69               What Vegetable has_color white
70                    What Food has_color white
71                   What Thing has_color white
72            What Vegetable original_from asia
73                 What Food original_from asia
74                What Thing original_from asia
75            What Vegetable original_from asia
76                 What Food original_from asia
77                What Thing original_from asia
78             What Vegetable has_taste pungent
79                  What Food has_taste pungent
80                 What Thing has_taste pungent
81             What Vegetable has_taste pungent
82                  What Food has_taste pungent
83                 What Thing has_taste pungent
84           What Vegetable original_from egypt
85                What Food original_from egypt
86               What Thing original_from egypt
87           What Vegetable original_from egypt
88                What Food original_from egypt
89               What Thing original_from egypt
90              What Vegetable has_color purple
91                   What Food has_color purple
92                  What Thing has_color purple
93              What Vegetable has_color purple
94                   What Food has_color purple
95                  What Thing has_color purple
96       What Vegetable original_from australia
97            What Food original_from australia
98           What Thing original_from australia
99       What Vegetable original_from australia
100           What Food original_from australia
101          What Thing original_from australia
102    What Vegetable original_from new_zealand
103         What Food original_from new_zealand
104        What Thing original_from new_zealand
105    What Vegetable original_from new_zealand
106         What Food original_from new_zealand
107        What Thing original_from new_zealand
108         What Vegetable original_from mexica
109              What Food original_from mexica
110             What Thing original_from mexica
111         What Vegetable original_from mexica
112              What Food original_from mexica
113             What Thing original_from mexica
114                 What Fruit has_color yellow
115                 What Fruit has_color yellow
116                  What Fruit has_color green
117                  What Fruit has_color green
118                    What Fruit has_color red
119                    What Fruit has_color red
120            What Fruit original_from america
121            What Fruit original_from america
122       What Fruit has_child_food green_apple
123        What Food has_child_food green_apple
124       What Thing has_child_food green_apple
125       What Fruit has_child_food green_apple
126        What Food has_child_food green_apple
127       What Thing has_child_food green_apple
128       What Fruit has_child_food green_apple
129        What Food has_child_food green_apple
130       What Thing has_child_food green_apple
131                   What Fruit has_shape long
132                   What Fruit has_shape long
133              What Fruit original_from china
134               What Food original_from china
135              What Thing original_from china
136              What Fruit original_from china
137               What Food original_from china
138              What Thing original_from china
139                  What Fruit has_taste sweet
140                  What Fruit has_taste sweet
141                   What Fruit has_taste sour
142                    What Food has_taste sour
143                   What Thing has_taste sour
144                   What Fruit has_taste sour
145                    What Food has_taste sour
146                   What Thing has_taste sour
147                  What Fruit has_taste juicy
148                  What Fruit has_taste juicy
149                 What Fruit has_color purple
150                 What Fruit has_color purple
151        What Fruit original_from new_zealand
152        What Fruit original_from new_zealand
153                  What Fruit has_shape round
154                  What Fruit has_shape round
155                 What Fruit has_taste grassy
156                  What Food has_taste grassy
157                 What Thing has_taste grassy
158                 What Fruit has_taste grassy
159                  What Food has_taste grassy
160                 What Thing has_taste grassy
161                     What Meat has_color red
162                     What Meat has_color red
163                   What Meat has_taste meaty
164                   What Food has_taste meaty
165                  What Thing has_taste meaty
166                   What Meat has_taste meaty
167                   What Food has_taste meaty
168                  What Thing has_taste meaty
169                   What Meat has_color white
170                   What Meat has_color white
171                 What Fish has_nutrition fat
172                 What Food has_nutrition fat
173                What Thing has_nutrition fat
174                 What Fish has_nutrition fat
175                 What Food has_nutrition fat
176                What Thing has_nutrition fat
177             What Fish has_nutrition protein
178             What Food has_nutrition protein
179            What Thing has_nutrition protein
180             What Fish has_nutrition protein
181             What Food has_nutrition protein
182            What Thing has_nutrition protein
183                   What Fish has_taste fishy
184                   What Food has_taste fishy
185                  What Thing has_taste fishy
186                   What Fish has_taste fishy
187                   What Food has_taste fishy
188                  What Thing has_taste fishy
189            What Dairy has_nutrition protein
190            What Dairy has_nutrition protein
191                  What Dairy has_taste sweet
192                  What Dairy has_taste sweet
193                What Dairy has_nutrition fat
194                What Dairy has_nutrition fat
195                  What Grain has_shape round
196                  What Grain has_shape round
197                   What Grain has_shape long
198                   What Grain has_shape long
199                  What Grain has_taste tangy
200                   What Food has_taste tangy
201                  What Thing has_taste tangy
202                  What Grain has_taste tangy
203                   What Food has_taste tangy
204                  What Thing has_taste tangy
205                 What Grain has_color yellow
206                 What Grain has_color yellow
207            What Grain original_from america
208            What Grain original_from america
Name: e1_classes, dtype: object

In [125]:
exp.head()

  e1_classes r1_relation e2_classes e2_entity r2_relation e3_classes e3_entity
0  Vegetable   has_color      Color       red
1       Food   has_color      Color       red
2      Thing   has_color      Color       red
3  Vegetable   has_color      Thing       red
4       Food   has_color      Thing       red

In [121]:
# Generate Answers Code
# class_name    # relation_name     # entity_name
# Food        has_child_food      orange
# graph = default_world.as_rdflib_graph()


def query_ontology(class_name, relation_name, entity_name):

    query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s
    WHERE {""" + f"""
        ?s onto:{relation_name} onto:{entity_name} .
    """ + '}'
    r1 = list(graph.query_owlready(query))
    return r1

def get_ontology_answer(class_name, relation_name, entity_name, not_modifier=False):
    if not_modifier:
        query = "PREFIX onto: <" + onto.base_iri + """> SELECT ?s 
        WHERE {
            ?s rdf:type ?type. ?type rdfs:subClassOf+ onto:Food . 
            FILTER NOT EXISTS { """  + f""" ?s onto:{relation_name} onto:{entity_name} . """ + \
            """} FILTER NOT EXISTS {?s rdfs:subClassOf ?t . } }""" 
        r2 = list(graph.query_owlready(query)) 
        return r2 
    else:
        results:list = query_ontology(class_name, relation_name, entity_name)
        return results


# def compute_logical_relation(a1, a1_operator, a2, a2_operator):
#     result = []

#     # a1,a2,a3 = [set() if a == 'not_answer' else set(a) for a in [a1,a2,a3]]
#     # a1, a2, a3 = set(a1), set(a2), set(a3)
#     a1, a2  = set(a1), set(a2)
#     if a1_operator == 'and':
#         result1 = a1.intersection(a2)
#     else:
#         result1 = a1.union(a2)

#     return result

# The below code is to add a null into the table. 
#     if len(result) == 0:
#         return np.nan
#     return list(result)


# 	e1_classes	r1_relation	e2_classes	e2_entity	r2_relation	e3_classes	e3_entity
# 0	Vegetable	has_color	Color	red	

from itertools import chain
#a1 = c3e.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_x, row.e2_entity_x, row.not_x), axis=1)
a1 = exp.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation, row.e2_entity), axis=1)
# filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
# flatten1  = [filter_function(val) for val in a1]
# print(flatten1)

# qadb1['a1'] = flatten1



# a2 = qadb1.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation_y, row.e2_entity_y, row.not_y), axis=1)
# filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
# flatten2  = [filter_function(val) for val in a2] 
# qadb1['a2'] = flatten2


# a3 = qadb1.apply(lambda row: get_ontology_answer(row.e1_classes, row.r1_relation, row.e2_entity), axis=1)
# filter_function = lambda item: item if isinstance(item, str) else [str(it) for it in item[0]]
# flatten3  = [filter_function(val) for val in a3] 
# qadb1['a3'] = flatten3

#c3e['fa'] = c3e.apply(lambda row: compute_logical_relation(row.a1, row.combine_x,  row.a2, row.combine_y, row.a3), axis=1)
# ?qadb1['fa'] = qadb1.apply(lambda row: compute_logical_relation(row.a1, row.combine_x,  row.a2, row.combine_y, row.a3), axis=1)

print('Answer:')
# c3e.head(500)
# qadb1.head(50)

[['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.broccoli'], ['onto.broccoli'], ['onto.broccoli'], ['onto.broccoli'], ['onto.broccoli'], ['onto.broccoli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.chilli'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.carrot'], ['onto.cucumber'], ['onto.cucumber'], ['onto.cucumber'], ['onto.cucumber'], ['onto.cucumber'], ['onto.cucumber'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.garlic'], ['onto.lettuce'], ['onto.lettuce'], ['onto.lettuce'], ['onto.lettuce'], ['onto.lettuce'], ['onto.lettuce'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.pumpkin'], ['onto.pumpkin'], ['onto.pumpkin'], ['onto.pumpkin'], ['onto.pumpkin'], ['onto.pumpkin'], ['onto.chilli'], ['onto.chilli'], ['onto.broccoli'], ['onto.broccoli'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.tomato'], ['onto.apple'], ['onto.apple'], ['onto.apple'], ['onto.apple'], ['onto.apple'], ['onto.apple'], ['onto.apple'], ['onto.apple'], ['onto.apple'], ['onto.carrot'], ['onto.carrot'], ['onto.lemon'], ['onto.lemon'], ['onto.lemon'], ['onto.lemon'], ['onto.lemon'], ['onto.lemon'], ['onto.tomato'], ['onto.tomato'], ['onto.lemon'], ['onto.lemon'], ['onto.lemon'], ['onto.lemon'], ['onto.lemon'], ['onto.lemon'], ['onto.tomato'], ['onto.tomato'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.onion'], ['onto.tomato'], ['onto.tomato'], ['onto.avocado'], ['onto.avocado'], ['onto.avocado'], ['onto.avocado'], ['onto.avocado'], ['onto.avocado'], ['onto.tomato'], ['onto.tomato'], ['onto.beaf'], ['onto.beaf'], ['onto.beaf'], ['onto.beaf'], ['onto.beaf'], ['onto.beaf'], ['onto.garlic'], ['onto.garlic'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.salmon'], ['onto.tomato'], ['onto.tomato'], ['onto.salmon'], ['onto.salmon'], ['onto.tomato'], ['onto.tomato'], ['onto.carrot'], ['onto.carrot'], ['onto.bread'], ['onto.bread'], ['onto.bread'], ['onto.bread'], ['onto.bread'], ['onto.bread'], ['onto.chilli'], ['onto.chilli'], ['onto.tomato'], ['onto.tomato']]
Answer:

In [139]:
print(a1[0])
exp.iloc[[0]]

[[onto.tomato], [onto.chilli], [onto.capsicum], [onto.pepper], [onto.apple], [onto.red_apple], [onto.beaf], [onto.lamb], [onto.pork], [onto.pan], [onto.pot]]

  e1_classes r1_relation e2_classes e2_entity r2_relation e3_classes e3_entity
0  Vegetable   has_color      Color       red

In [146]:
if len(exp) == len(questions): 
    print('Yar')

Yar

In [171]:
answers = pd.Series(a1)
base_path = os.getcwd()

In [175]:
questions.to_csv(os.path.join(base_path, 'questions.txt'), index=False, header=False)
answers.to_csv(os.path.join(base_path, 'answers.txt'), index=False, header=False)
qa_df = pd.DataFrame({
    'question': questions,
    'answer': answers
})
qa_df.to_csv(os.path.join(base_path, 'qa_dataset.csv'), index=False)